FROM ubuntu:24.04

ENV NO_COLOR=true
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN echo "Types: deb" > /etc/apt/sources.list.d/plucky.sources && \
    echo "URIs: http://archive.ubuntu.com/ubuntu/" >> /etc/apt/sources.list.d/plucky.sources && \
    echo "Suites: plucky plucky-updates plucky-backports" >> /etc/apt/sources.list.d/plucky.sources && \
    echo "Components: main restricted universe multiverse" >> /etc/apt/sources.list.d/plucky.sources && \
    echo "Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg" >> /etc/apt/sources.list.d/plucky.sources && \
    echo "" >> /etc/apt/sources.list.d/plucky.sources && \
    echo "Types: deb" >> /etc/apt/sources.list.d/plucky.sources && \
    echo "URIs: http://security.ubuntu.com/ubuntu/" >> /etc/apt/sources.list.d/plucky.sources && \
    echo "Suites: plucky-security" >> /etc/apt/sources.list.d/plucky.sources && \
    echo "Components: main restricted universe multiverse" >> /etc/apt/sources.list.d/plucky.sources && \
    echo "Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg" >> /etc/apt/sources.list.d/plucky.sources

RUN echo "Package: *" > /etc/apt/preferences.d/plucky-pin && \
    echo "Pin: release n=plucky" >> /etc/apt/preferences.d/plucky-pin && \
    echo "Pin-Priority: -10" >> /etc/apt/preferences.d/plucky-pin && \
    echo "" >> /etc/apt/preferences.d/plucky-pin && \
    echo "Package: kcov" >> /etc/apt/preferences.d/plucky-pin && \
    echo "Pin: release n=plucky" >> /etc/apt/preferences.d/plucky-pin && \
    echo "Pin-Priority: 500" >> /etc/apt/preferences.d/plucky-pin

RUN apt-get update -qq && apt-get install -qq --no-install-recommends -y \
    curl xz-utils ca-certificates kcov minisign git && \
    rm -rf /var/lib/apt/lists/*

ARG ZIG_VERSION=0.16.0
RUN curl -sSL --fail -o zig.tar.xz "https://ziglang.org/download/${ZIG_VERSION}/zig-x86_64-linux-${ZIG_VERSION}.tar.xz" && \
    mkdir -p /usr/local/zig && \
    tar -xf zig.tar.xz -C /usr/local/zig --strip-components=1 && \
    rm zig.tar.xz

ENV PATH=/usr/local/zig:$PATH
RUN zig version

ADD . /app
WORKDIR /app

RUN zig build test-coverage --summary all
RUN --security=insecure kcov --clean --cobertura-only --include-pattern=src/ coverage zig-out/bin/test || true

RUN mkdir -p /output
RUN if [ -f coverage/cov.xml ]; then cp coverage/cov.xml /output/cobertura.xml; fi
