// <auto-generated>
//   This code was generated by openapi2zig 0.5.0 (bca68ad) on 2026-08-28 20:38:41 UTC
//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
//   Checksum: 47a4714dd62a5432
// </auto-generated>

const std = @import("std");

pub fn Owned(comptime T: type) type {
    return struct {
        allocator: std.mem.Allocator,
        body: []u8,
        parsed: std.json.Parsed(T),

        pub fn deinit(self: *@This()) void {
            self.parsed.deinit();
            self.allocator.free(self.body);
        }

        pub fn value(self: *@This()) *T {
            return &self.parsed.value;
        }
    };
}

pub const RawResponse = struct {
    allocator: std.mem.Allocator,
    status: std.http.Status,
    body: []u8,

    pub fn deinit(self: *@This()) void {
        self.allocator.free(self.body);
    }
};

pub const ParseErrorResponse = struct {
    raw: RawResponse,
    error_name: []const u8,
};

pub fn ApiResult(comptime T: type) type {
    return union(enum) {
        ok: Owned(T),
        api_error: RawResponse,
        parse_error: ParseErrorResponse,

        pub fn deinit(self: *@This()) void {
            switch (self.*) {
                .ok => |*value| value.deinit(),
                .api_error => |*value| value.deinit(),
                .parse_error => |*value| value.raw.deinit(),
            }
        }
    };
}
pub const HttpObserver = struct {
    ctx: ?*anyopaque,
    onRequest: ?*const fn (ctx: ?*anyopaque, method: std.http.Method, url: []const u8, headers: []const std.http.Header, body: ?[]const u8) void,
    onResponse: ?*const fn (ctx: ?*anyopaque, method: std.http.Method, url: []const u8, status: std.http.Status, headers: []const std.http.Header, body: []const u8, duration_ns: u64) void,
    onError: ?*const fn (ctx: ?*anyopaque, method: std.http.Method, url: []const u8, err_name: []const u8) void,
};

const max_sse_line_size = 256 * 1024;
const max_sse_event_size = 1024 * 1024;

pub const CancellationToken = struct {
    cancelled: std.atomic.Value(bool),

    pub fn init() CancellationToken {
        return .{ .cancelled = std.atomic.Value(bool).init(false) };
    }

    pub fn cancel(self: *CancellationToken) void {
        self.cancelled.store(true, .seq_cst);
    }

    pub fn isCancelled(self: *CancellationToken) bool {
        return self.cancelled.load(.seq_cst);
    }
};

pub fn checkCancellation(token: ?*CancellationToken) !void {
    if (token) |t| {
        if (t.isCancelled()) return error.Cancelled;
    }
}

/// Wraps an underlying reader and checks an optional cancel predicate before
/// every read of the underlying reader. When the predicate returns true, the
/// read fails with error.ReadFailed; callers translate that into
/// error.Cancelled. A companion watcher thread in the generated client closes
/// the underlying socket so blocked socket reads are interrupted within about 10 ms.
pub const CancelableReader = struct {
    inner: *std.Io.Reader,
    reader: std.Io.Reader,
    should_cancel: ?*const fn () bool,

    pub fn init(inner: *std.Io.Reader, buffer: []u8, should_cancel: ?*const fn () bool) CancelableReader {
        return .{
            .inner = inner,
            .reader = .{
                .buffer = buffer,
                .seek = 0,
                .end = 0,
                .vtable = &vtable,
            },
            .should_cancel = should_cancel,
        };
    }

    const vtable: std.Io.Reader.VTable = .{
        .stream = stream,
        .discard = std.Io.Reader.defaultDiscard,
        .readVec = std.Io.Reader.defaultReadVec,
        .rebase = std.Io.Reader.defaultRebase,
    };

    fn stream(ctx: *std.Io.Reader, w: *std.Io.Writer, limit: std.Io.Limit) std.Io.Reader.StreamError!usize {
        const self: *CancelableReader = @fieldParentPtr("reader", ctx);
        if (self.should_cancel) |pred| {
            if (pred()) return error.ReadFailed;
        }
        return self.inner.stream(w, limit);
    }
};

test "CancelableReader passes through when cancel check is null" {
    var out: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer out.deinit();
    var fixed = std.Io.Reader.fixed("hello");
    var buffer: [1]u8 = undefined;
    var reader = CancelableReader.init(&fixed, &buffer, null);
    _ = try reader.reader.streamRemaining(&out.writer);
    try std.testing.expectEqualStrings("hello", out.written());
}

test "CancelableReader fails with ReadFailed when cancel check returns true" {
    var out: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer out.deinit();
    const always_cancel = struct {
        fn check() bool {
            return true;
        }
    }.check;
    var fixed = std.Io.Reader.fixed("hello");
    var buffer: [1]u8 = undefined;
    var reader = CancelableReader.init(&fixed, &buffer, &always_cancel);
    try std.testing.expectError(error.ReadFailed, reader.reader.streamRemaining(&out.writer));
}

test "CancelableReader passes through when cancel check returns false" {
    var out: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer out.deinit();
    const never_cancel = struct {
        fn check() bool {
            return false;
        }
    }.check;
    var fixed = std.Io.Reader.fixed("hello");
    var buffer: [1]u8 = undefined;
    var reader = CancelableReader.init(&fixed, &buffer, &never_cancel);
    _ = try reader.reader.streamRemaining(&out.writer);
    try std.testing.expectEqualStrings("hello", out.written());
}

const ChunkedReader = struct {
    data: []const u8,
    pos: usize,
    reader: std.Io.Reader,

    fn init(data: []const u8, buffer: []u8) ChunkedReader {
        return .{
            .data = data,
            .pos = 0,
            .reader = .{
                .buffer = buffer,
                .seek = 0,
                .end = 0,
                .vtable = &vtable,
            },
        };
    }

    const vtable: std.Io.Reader.VTable = .{
        .stream = stream,
        .discard = std.Io.Reader.defaultDiscard,
        .readVec = std.Io.Reader.defaultReadVec,
        .rebase = std.Io.Reader.defaultRebase,
    };

    fn stream(ctx: *std.Io.Reader, w: *std.Io.Writer, limit: std.Io.Limit) std.Io.Reader.StreamError!usize {
        const self: *ChunkedReader = @fieldParentPtr("reader", ctx);
        const remaining = self.data.len - self.pos;
        if (remaining == 0) return 0;
        const dest = limit.slice(try w.writableSliceGreedy(1));
        const n = @min(remaining, dest.len);
        @memcpy(dest[0..n], self.data[self.pos .. self.pos + n]);
        self.pos += n;
        w.advance(n);
        return n;
    }
};

test "CancelableReader aborts at the next read when cancel flag is set mid-stream" {
    var out: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer out.deinit();

    const TestContext = struct {
        var cancelled = false;
        fn check() bool {
            return cancelled;
        }
    };

    var chunks_buffer: [1]u8 = undefined;
    var chunks = ChunkedReader.init("hello", &chunks_buffer);
    var wrapper_buffer: [1]u8 = undefined;
    var reader = CancelableReader.init(&chunks.reader, &wrapper_buffer, &TestContext.check);

    _ = try reader.reader.streamExact(&out.writer, 2);
    TestContext.cancelled = true;
    try std.testing.expectError(error.ReadFailed, reader.reader.streamRemaining(&out.writer));
    try std.testing.expectEqualStrings("he", out.written());
}

pub fn parseSseBytes(allocator: std.mem.Allocator, bytes: []const u8, callback: anytype, cancellation_token: ?*CancellationToken) !void {
    var reader: std.Io.Reader = .fixed(bytes);
    try parseSseReader(allocator, &reader, callback, cancellation_token);
}

pub fn parseSseReader(allocator: std.mem.Allocator, reader: *std.Io.Reader, callback: anytype, cancellation_token: ?*CancellationToken) !void {
    var line_buf: std.Io.Writer.Allocating = .init(allocator);
    defer line_buf.deinit();

    var event_data: std.Io.Writer.Allocating = .init(allocator);
    defer event_data.deinit();

    while (true) {
        try checkCancellation(cancellation_token);
        line_buf.clearRetainingCapacity();

        _ = reader.streamDelimiterLimit(&line_buf.writer, '\n', .limited(max_sse_line_size)) catch |err| switch (err) {
            error.StreamTooLong => return error.SseLineTooLong,
            error.ReadFailed => return err,
            error.WriteFailed => return err,
        };

        const ended_with_delimiter = blk: {
            const byte = reader.peekByte() catch |err| switch (err) {
                error.EndOfStream => break :blk false,
                error.ReadFailed => return err,
            };
            if (byte == '\n') {
                _ = try reader.takeByte();
                break :blk true;
            }
            break :blk false;
        };

        if (try processSseLine(&event_data, line_buf.written(), callback)) return;
        if (!ended_with_delimiter) break;
    }

    _ = try dispatchSseEvent(&event_data, callback);
}

fn processSseLine(event_data: *std.Io.Writer.Allocating, raw_line: []const u8, callback: anytype) !bool {
    const line = std.mem.trimEnd(u8, raw_line, "\r");
    if (line.len == 0) return try dispatchSseEvent(event_data, callback);
    if (line[0] == ':') return false;

    const colon = std.mem.indexOfScalar(u8, line, ':') orelse return false;
    const field = line[0..colon];
    if (!std.mem.eql(u8, field, "data")) return false;

    var value = line[colon + 1 ..];
    if (value.len > 0 and value[0] == ' ') value = value[1..];
    const separator_len: usize = if (event_data.written().len == 0) 0 else 1;
    if (event_data.written().len + separator_len + value.len > max_sse_event_size) return error.SseEventTooLong;
    if (separator_len != 0) try event_data.writer.writeByte('\n');
    try event_data.writer.writeAll(value);
    return false;
}

fn dispatchSseEvent(event_data: *std.Io.Writer.Allocating, callback: anytype) !bool {
    const data = event_data.written();
    if (data.len == 0) return false;
    defer event_data.clearRetainingCapacity();

    if (std.mem.eql(u8, data, "[DONE]")) return true;
    try callback.event(data);
    return false;
}

pub fn TypedSseCallback(comptime T: type, comptime Callback: type) type {
    return struct {
        allocator: std.mem.Allocator,
        callback: *Callback,

        pub fn event(self: *@This(), data: []const u8) !void {
            var parsed = try std.json.parseFromSlice(T, self.allocator, data, .{ .ignore_unknown_fields = true });
            defer parsed.deinit();
            try self.callback.event(&parsed.value);
        }
    };
}

pub fn parseSseBytesTyped(comptime T: type, allocator: std.mem.Allocator, bytes: []const u8, callback: anytype, cancellation_token: ?*CancellationToken) !void {
    const Callback = @TypeOf(callback.*);
    var typed_callback: TypedSseCallback(T, Callback) = .{ .allocator = allocator, .callback = callback };
    try parseSseBytes(allocator, bytes, &typed_callback, cancellation_token);
}

pub fn parseSseReaderTyped(comptime T: type, allocator: std.mem.Allocator, reader: *std.Io.Reader, callback: anytype, cancellation_token: ?*CancellationToken) !void {
    const Callback = @TypeOf(callback.*);
    var typed_callback: TypedSseCallback(T, Callback) = .{ .allocator = allocator, .callback = callback };
    try parseSseReader(allocator, reader, &typed_callback, cancellation_token);
}
