// <auto-generated>
//   This code was generated by openapi2zig 0.5.0 (1247924) on 2026-08-31 08:07:43 UTC
//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
//   Checksum: a60ee34c029c2ba
// </auto-generated>

const std = @import("std");
const contracts = @import("contracts.zig");
const runtime = @import("../runtime.zig");
const Owned = runtime.Owned;
const HttpObserver = runtime.HttpObserver;
const RawResponse = runtime.RawResponse;
const ParseErrorResponse = runtime.ParseErrorResponse;
const ApiResult = runtime.ApiResult;
const CancellationToken = runtime.CancellationToken;
const checkCancellation = runtime.checkCancellation;
const CancelableReader = runtime.CancelableReader;
const parseSseReader = runtime.parseSseReader;
const parseSseBytes = runtime.parseSseBytes;
const parseSseBytesTyped = runtime.parseSseBytesTyped;
const parseSseReaderTyped = runtime.parseSseReaderTyped;
const TypedSseCallback = runtime.TypedSseCallback;

pub const Client = struct {
    allocator: std.mem.Allocator,
    io: std.Io,
    http: std.http.Client,
    api_key: []const u8,
    base_url: []const u8 = "",
    organization: ?[]const u8 = null,
    project: ?[]const u8 = null,
    default_headers: []const std.http.Header = &.{},
    http_observer: ?HttpObserver = null,

    /// Optional predicate polled while reading a streaming response body.
    /// When it returns true, a successfully started background watcher interrupts
    /// a blocked SSE socket read within about 10 ms and the stream exits with
    /// error.Cancelled. A CancelableReader also checks the predicate at every read
    /// boundary. If watcher startup fails, cancellation remains read-boundary only.
    /// Point it at an app-level cancel flag; it composes with a CancellationToken.
    /// When null (default), no watcher thread is spawned.
    cancel_check: ?*const fn () bool = null,

    pub fn init(allocator: std.mem.Allocator, io: std.Io, api_key: []const u8) Client {
        return .{
            .allocator = allocator,
            .io = io,
            .http = .{ .allocator = allocator, .io = io },
            .api_key = api_key,
            .http_observer = null,
        };
    }

    pub fn deinit(self: *Client) void {
        self.http.deinit();
    }

    pub fn withBaseUrl(self: *Client, base_url: []const u8) void {
        self.base_url = base_url;
    }
};

fn isQueryChar(c: u8) bool {
    return std.ascii.isAlphanumeric(c) or switch (c) {
        '-', '.', '_', '~' => true,
        else => false,
    };
}

fn writeQueryComponent(writer: *std.Io.Writer, value: []const u8) !void {
    try std.Uri.Component.percentEncode(writer, value, isQueryChar);
}

fn writeQueryValue(writer: *std.Io.Writer, value: anytype) !void {
    const T = @TypeOf(value);
    switch (@typeInfo(T)) {
        .pointer => |ptr| {
            if (ptr.size == .slice and ptr.child == u8) {
                try writeQueryComponent(writer, value);
            } else {
                try std.json.Stringify.value(value, .{}, writer);
            }
        },
        .int, .comptime_int, .float, .comptime_float, .bool => try writer.print("{}", .{value}),
        .@"enum" => try writeQueryComponent(writer, @tagName(value)),
        else => try std.json.Stringify.value(value, .{}, writer),
    }
}

fn appendQueryParam(writer: *std.Io.Writer, first_query: *bool, name: []const u8, value: anytype) !void {
    if (first_query.*) {
        try writer.writeByte('?');
        first_query.* = false;
    } else {
        try writer.writeByte('&');
    }
    try writeQueryComponent(writer, name);
    try writer.writeByte('=');
    try writeQueryValue(writer, value);
}

/// Serializes an `in: header` parameter value to an owned string. Reuses
/// the same primitive-type coverage as query parameters (string, integer,
/// float, boolean, enum). The caller frees the returned slice.
fn formatHeaderValue(allocator: std.mem.Allocator, value: anytype) ![]u8 {
    const T = @TypeOf(value);
    return switch (@typeInfo(T)) {
        .pointer => |ptr| blk: {
            if (ptr.size == .slice and ptr.child == u8) {
                break :blk try allocator.dupe(u8, value);
            }
            @compileError("OpenAPI header values must be strings, numbers, booleans, or enums");
        },
        .@"enum" => try allocator.dupe(u8, @tagName(value)),
        .int, .comptime_int, .float, .comptime_float, .bool => try std.fmt.allocPrint(allocator, "{}", .{value}),
        else => @compileError("OpenAPI header values must be strings, numbers, booleans, or enums"),
    };
}

/// Appends `value` under `name`, replacing (case-insensitively) any
/// existing header of the same name. Used so a declared operation header
/// parameter always wins over an equal-named client default header while
/// emitting exactly one header on the wire.
fn appendOrReplaceHeader(allocator: std.mem.Allocator, headers: *std.ArrayList(std.http.Header), name: []const u8, value: []const u8) !void {
    var i: usize = 0;
    while (i < headers.items.len) {
        if (std.ascii.eqlIgnoreCase(headers.items[i].name, name)) {
            _ = headers.orderedRemove(i);
        } else {
            i += 1;
        }
    }
    try headers.append(allocator, .{ .name = name, .value = value });
}

pub fn requestRaw(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8) !RawResponse {
    return requestRawWithContentType(client, method, url, payload, "application/json");
}

pub fn requestRawWithExtraHeaders(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8, extra_headers: []const std.http.Header) !RawResponse {
    return requestRawWithContentTypeAndExtraHeaders(client, method, url, payload, "application/json", extra_headers);
}

pub fn requestRawWithContentTypeAndExtraHeaders(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8, content_type_value: []const u8, extra_headers: []const std.http.Header) !RawResponse {
    const allocator = client.allocator;
    var headers = std.ArrayList(std.http.Header).empty;
    defer headers.deinit(allocator);
    const content_type: ?[]const u8 = if (payload != null) content_type_value else null;
    try appendClientHeaders(allocator, &headers, client, content_type, "application/json");
    for (extra_headers) |header| try appendOrReplaceHeader(allocator, &headers, header.name, header.value);

    if (client.http_observer) |obs| {
        if (obs.onRequest) |cb| cb(obs.ctx, method, url, headers.items, payload);
    }

    const uri = try std.Uri.parse(url);
    var response_body: std.Io.Writer.Allocating = .init(allocator);
    defer response_body.deinit();

    const start = std.Io.Clock.awake.now(client.io);
    const result = client.http.fetch(.{
        .location = .{ .uri = uri },
        .method = method,
        .extra_headers = headers.items,
        .payload = payload,
        .response_writer = &response_body.writer,
    }) catch |err| {
        if (client.http_observer) |obs| {
            if (obs.onError) |cb| cb(obs.ctx, method, url, @errorName(err));
        }
        return err;
    };
    const elapsed_ns = @as(u64, @intCast(start.untilNow(client.io, .awake).nanoseconds));

    const body = try response_body.toOwnedSlice();

    if (client.http_observer) |obs| {
        if (obs.onResponse) |cb| cb(obs.ctx, method, url, result.status, &.{}, body, elapsed_ns);
    }

    return .{
        .allocator = allocator,
        .status = result.status,
        .body = body,
    };
}

pub fn requestRawWithContentType(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8, content_type_value: []const u8) !RawResponse {
    const allocator = client.allocator;
    var headers = std.ArrayList(std.http.Header).empty;
    defer headers.deinit(allocator);
    const content_type: ?[]const u8 = if (payload != null) content_type_value else null;
    try appendClientHeaders(allocator, &headers, client, content_type, "application/json");

    if (client.http_observer) |obs| {
        if (obs.onRequest) |cb| cb(obs.ctx, method, url, headers.items, payload);
    }

    const uri = try std.Uri.parse(url);
    var response_body: std.Io.Writer.Allocating = .init(allocator);
    defer response_body.deinit();

    const start = std.Io.Clock.awake.now(client.io);
    const result = client.http.fetch(.{
        .location = .{ .uri = uri },
        .method = method,
        .extra_headers = headers.items,
        .payload = payload,
        .response_writer = &response_body.writer,
    }) catch |err| {
        if (client.http_observer) |obs| {
            if (obs.onError) |cb| cb(obs.ctx, method, url, @errorName(err));
        }
        return err;
    };
    const elapsed_ns = @as(u64, @intCast(start.untilNow(client.io, .awake).nanoseconds));

    const body = try response_body.toOwnedSlice();

    if (client.http_observer) |obs| {
        if (obs.onResponse) |cb| cb(obs.ctx, method, url, result.status, &.{}, body, elapsed_ns);
    }

    return .{
        .allocator = allocator,
        .status = result.status,
        .body = body,
    };
}

pub fn getRaw(client: *Client, path: []const u8) !RawResponse {
    const url = try std.fmt.allocPrint(client.allocator, "{s}{s}", .{ client.base_url, path });
    defer client.allocator.free(url);
    return requestRaw(client, .GET, url, null);
}

pub fn postJsonRaw(client: *Client, path: []const u8, payload: anytype) !RawResponse {
    const allocator = client.allocator;
    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(payload, .{ .emit_null_optional_fields = false }, &str.writer);

    const url = try std.fmt.allocPrint(allocator, "{s}{s}", .{ client.base_url, path });
    defer allocator.free(url);
    return requestRaw(client, .POST, url, str.written());
}

pub fn parseRawResponse(comptime T: type, raw: RawResponse) !ApiResult(T) {
    if (raw.status.class() != .success) return .{ .api_error = raw };
    const parsed = std.json.parseFromSlice(T, raw.allocator, raw.body, .{ .ignore_unknown_fields = true }) catch |err| {
        return .{ .parse_error = .{ .raw = raw, .error_name = @errorName(err) } };
    };
    return .{ .ok = .{ .allocator = raw.allocator, .body = raw.body, .parsed = parsed } };
}

pub fn getJsonResult(comptime T: type, client: *Client, path: []const u8) !ApiResult(T) {
    return parseRawResponse(T, try getRaw(client, path));
}

pub fn postJsonResult(comptime T: type, client: *Client, path: []const u8, payload: anytype) !ApiResult(T) {
    return parseRawResponse(T, try postJsonRaw(client, path, payload));
}
fn appendClientHeaders(allocator: std.mem.Allocator, headers: *std.ArrayList(std.http.Header), client: *Client, content_type: ?[]const u8, accept: []const u8) !void {
    if (content_type) |ct| {
        try headers.append(allocator, .{ .name = "Content-Type", .value = ct });
    }
    try headers.append(allocator, .{ .name = "Accept", .value = accept });
    if (client.organization) |organization| {
        try headers.append(allocator, .{ .name = "OpenAI-Organization", .value = organization });
    }
    if (client.project) |project| {
        try headers.append(allocator, .{ .name = "OpenAI-Project", .value = project });
    }
    for (client.default_headers) |header| {
        try headers.append(allocator, header);
    }
}

// Description:
// Generates a response from the model given an input message.
//
pub fn @"generativelanguage.models.generateText"(client: *Client, model: []const u8, requestBody: contracts.GenerateTextRequest) !Owned(contracts.GenerateTextResponse) {
    var result = try @"generativelanguage.models.generateTextResult"(client, model, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.generateTextRaw"(client: *Client, model: []const u8, requestBody: contracts.GenerateTextRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/ss/{s}:generateText", .{ client.base_url, model });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.generateTextResult"(client: *Client, model: []const u8, requestBody: contracts.GenerateTextRequest) !ApiResult(contracts.GenerateTextResponse) {
    return parseRawResponse(contracts.GenerateTextResponse, try @"generativelanguage.models.generateTextRaw"(client, model, requestBody));
}

// Description:
// Generates a [streamed response](https://ai.google.dev/gemini-api/docs/text-generation?lang=python#generate-a-text-stream) from the model given an input `GenerateContentRequest`.
//
pub fn @"generativelanguage.models.streamGenerateContent"(client: *Client, model: []const u8, requestBody: contracts.GenerateContentRequest) !Owned(contracts.GenerateContentResponse) {
    var result = try @"generativelanguage.models.streamGenerateContentResult"(client, model, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.streamGenerateContentRaw"(client: *Client, model: []const u8, requestBody: contracts.GenerateContentRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/ss/{s}:streamGenerateContent", .{ client.base_url, model });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.streamGenerateContentResult"(client: *Client, model: []const u8, requestBody: contracts.GenerateContentRequest) !ApiResult(contracts.GenerateContentResponse) {
    return parseRawResponse(contracts.GenerateContentResponse, try @"generativelanguage.models.streamGenerateContentRaw"(client, model, requestBody));
}

// Description:
// Generates an embedding from the model given an input message.
//
pub fn @"generativelanguage.models.embedText"(client: *Client, model: []const u8, requestBody: contracts.EmbedTextRequest) !Owned(contracts.EmbedTextResponse) {
    var result = try @"generativelanguage.models.embedTextResult"(client, model, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.embedTextRaw"(client: *Client, model: []const u8, requestBody: contracts.EmbedTextRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/ss/{s}:embedText", .{ client.base_url, model });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.embedTextResult"(client: *Client, model: []const u8, requestBody: contracts.EmbedTextRequest) !ApiResult(contracts.EmbedTextResponse) {
    return parseRawResponse(contracts.EmbedTextResponse, try @"generativelanguage.models.embedTextRaw"(client, model, requestBody));
}

// Description:
// Runs a model's tokenizer on a text and returns the token count.
//
pub fn @"generativelanguage.models.countTextTokens"(client: *Client, model: []const u8, requestBody: contracts.CountTextTokensRequest) !Owned(contracts.CountTextTokensResponse) {
    var result = try @"generativelanguage.models.countTextTokensResult"(client, model, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.countTextTokensRaw"(client: *Client, model: []const u8, requestBody: contracts.CountTextTokensRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/ss/{s}:countTextTokens", .{ client.base_url, model });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.countTextTokensResult"(client: *Client, model: []const u8, requestBody: contracts.CountTextTokensRequest) !ApiResult(contracts.CountTextTokensResponse) {
    return parseRawResponse(contracts.CountTextTokensResponse, try @"generativelanguage.models.countTextTokensRaw"(client, model, requestBody));
}

// Description:
// Generates a grounded answer from the model given an input `GenerateAnswerRequest`.
//
pub fn @"generativelanguage.models.generateAnswer"(client: *Client, model: []const u8, requestBody: contracts.GenerateAnswerRequest) !Owned(contracts.GenerateAnswerResponse) {
    var result = try @"generativelanguage.models.generateAnswerResult"(client, model, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.generateAnswerRaw"(client: *Client, model: []const u8, requestBody: contracts.GenerateAnswerRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/ss/{s}:generateAnswer", .{ client.base_url, model });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.generateAnswerResult"(client: *Client, model: []const u8, requestBody: contracts.GenerateAnswerRequest) !ApiResult(contracts.GenerateAnswerResponse) {
    return parseRawResponse(contracts.GenerateAnswerResponse, try @"generativelanguage.models.generateAnswerRaw"(client, model, requestBody));
}

// Description:
// Generates multiple embedding vectors from the input `Content` which consists of a batch of strings represented as `EmbedContentRequest` objects.
//
pub fn @"generativelanguage.models.batchEmbedContents"(client: *Client, model: []const u8, requestBody: contracts.BatchEmbedContentsRequest) !Owned(contracts.BatchEmbedContentsResponse) {
    var result = try @"generativelanguage.models.batchEmbedContentsResult"(client, model, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.batchEmbedContentsRaw"(client: *Client, model: []const u8, requestBody: contracts.BatchEmbedContentsRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/ss/{s}:batchEmbedContents", .{ client.base_url, model });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.batchEmbedContentsResult"(client: *Client, model: []const u8, requestBody: contracts.BatchEmbedContentsRequest) !ApiResult(contracts.BatchEmbedContentsResponse) {
    return parseRawResponse(contracts.BatchEmbedContentsResponse, try @"generativelanguage.models.batchEmbedContentsRaw"(client, model, requestBody));
}

// Description:
// Generates a response from the model given an input `MessagePrompt`.
//
pub fn @"generativelanguage.models.generateMessage"(client: *Client, model: []const u8, requestBody: contracts.GenerateMessageRequest) !Owned(contracts.GenerateMessageResponse) {
    var result = try @"generativelanguage.models.generateMessageResult"(client, model, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.generateMessageRaw"(client: *Client, model: []const u8, requestBody: contracts.GenerateMessageRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/ss/{s}:generateMessage", .{ client.base_url, model });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.generateMessageResult"(client: *Client, model: []const u8, requestBody: contracts.GenerateMessageRequest) !ApiResult(contracts.GenerateMessageResponse) {
    return parseRawResponse(contracts.GenerateMessageResponse, try @"generativelanguage.models.generateMessageRaw"(client, model, requestBody));
}

// Description:
// Generates multiple embeddings from the model given input text in a synchronous call.
//
pub fn @"generativelanguage.models.batchEmbedText"(client: *Client, model: []const u8, requestBody: contracts.BatchEmbedTextRequest) !Owned(contracts.BatchEmbedTextResponse) {
    var result = try @"generativelanguage.models.batchEmbedTextResult"(client, model, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.batchEmbedTextRaw"(client: *Client, model: []const u8, requestBody: contracts.BatchEmbedTextRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/ss/{s}:batchEmbedText", .{ client.base_url, model });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.batchEmbedTextResult"(client: *Client, model: []const u8, requestBody: contracts.BatchEmbedTextRequest) !ApiResult(contracts.BatchEmbedTextResponse) {
    return parseRawResponse(contracts.BatchEmbedTextResponse, try @"generativelanguage.models.batchEmbedTextRaw"(client, model, requestBody));
}

// Description:
// Generates a model response given an input `GenerateContentRequest`. Refer to the [text generation guide](https://ai.google.dev/gemini-api/docs/text-generation) for detailed usage information. Input capabilities differ between models, including tuned models. Refer to the [model guide](https://ai.google.dev/gemini-api/docs/models/gemini) and [tuning guide](https://ai.google.dev/gemini-api/docs/model-tuning) for details.
//
pub fn @"generativelanguage.models.generateContent"(client: *Client, model: []const u8, requestBody: contracts.GenerateContentRequest) !Owned(contracts.GenerateContentResponse) {
    var result = try @"generativelanguage.models.generateContentResult"(client, model, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.generateContentRaw"(client: *Client, model: []const u8, requestBody: contracts.GenerateContentRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/ss/{s}:generateContent", .{ client.base_url, model });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.generateContentResult"(client: *Client, model: []const u8, requestBody: contracts.GenerateContentRequest) !ApiResult(contracts.GenerateContentResponse) {
    return parseRawResponse(contracts.GenerateContentResponse, try @"generativelanguage.models.generateContentRaw"(client, model, requestBody));
}

// Description:
// Lists the [`Model`s](https://ai.google.dev/gemini-api/docs/models/gemini) available through the Gemini API.
//
pub fn @"generativelanguage.models.list"(client: *Client, pageSize: ?i64, pageToken: ?[]const u8) !Owned(contracts.ListModelsResponse) {
    var result = try @"generativelanguage.models.listResult"(client, pageSize, pageToken);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.listRaw"(client: *Client, pageSize: ?i64, pageToken: ?[]const u8) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/models", .{client.base_url});
    var first_query = true;
    if (pageSize) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "pageSize", value);
    }
    if (pageToken) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "pageToken", value);
    }
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.listResult"(client: *Client, pageSize: ?i64, pageToken: ?[]const u8) !ApiResult(contracts.ListModelsResponse) {
    return parseRawResponse(contracts.ListModelsResponse, try @"generativelanguage.models.listRaw"(client, pageSize, pageToken));
}

// Description:
// Runs a model's tokenizer on a string and returns the token count.
//
pub fn @"generativelanguage.models.countMessageTokens"(client: *Client, model: []const u8, requestBody: contracts.CountMessageTokensRequest) !Owned(contracts.CountMessageTokensResponse) {
    var result = try @"generativelanguage.models.countMessageTokensResult"(client, model, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.countMessageTokensRaw"(client: *Client, model: []const u8, requestBody: contracts.CountMessageTokensRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/ss/{s}:countMessageTokens", .{ client.base_url, model });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.countMessageTokensResult"(client: *Client, model: []const u8, requestBody: contracts.CountMessageTokensRequest) !ApiResult(contracts.CountMessageTokensResponse) {
    return parseRawResponse(contracts.CountMessageTokensResponse, try @"generativelanguage.models.countMessageTokensRaw"(client, model, requestBody));
}

// Description:
// Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.
//
pub fn @"generativelanguage.models.operations.list"(client: *Client, name: []const u8, filter: ?[]const u8, pageSize: ?i64, pageToken: ?[]const u8) !Owned(contracts.ListOperationsResponse) {
    var result = try @"generativelanguage.models.operations.listResult"(client, name, filter, pageSize, pageToken);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.operations.listRaw"(client: *Client, name: []const u8, filter: ?[]const u8, pageSize: ?i64, pageToken: ?[]const u8) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/models/{s}/operations", .{ client.base_url, name });
    var first_query = true;
    if (filter) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "filter", value);
    }
    if (pageSize) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "pageSize", value);
    }
    if (pageToken) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "pageToken", value);
    }
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.operations.listResult"(client: *Client, name: []const u8, filter: ?[]const u8, pageSize: ?i64, pageToken: ?[]const u8) !ApiResult(contracts.ListOperationsResponse) {
    return parseRawResponse(contracts.ListOperationsResponse, try @"generativelanguage.models.operations.listRaw"(client, name, filter, pageSize, pageToken));
}

// Description:
// Same as Predict but returns an LRO.
//
pub fn @"generativelanguage.models.predictLongRunning"(client: *Client, model: []const u8, requestBody: contracts.PredictLongRunningRequest) !Owned(contracts.Operation) {
    var result = try @"generativelanguage.models.predictLongRunningResult"(client, model, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.predictLongRunningRaw"(client: *Client, model: []const u8, requestBody: contracts.PredictLongRunningRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/ss/{s}:predictLongRunning", .{ client.base_url, model });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.predictLongRunningResult"(client: *Client, model: []const u8, requestBody: contracts.PredictLongRunningRequest) !ApiResult(contracts.Operation) {
    return parseRawResponse(contracts.Operation, try @"generativelanguage.models.predictLongRunningRaw"(client, model, requestBody));
}

// Description:
// Runs a model's tokenizer on input `Content` and returns the token count. Refer to the [tokens guide](https://ai.google.dev/gemini-api/docs/tokens) to learn more about tokens.
//
pub fn @"generativelanguage.models.countTokens"(client: *Client, model: []const u8, requestBody: contracts.CountTokensRequest) !Owned(contracts.CountTokensResponse) {
    var result = try @"generativelanguage.models.countTokensResult"(client, model, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.countTokensRaw"(client: *Client, model: []const u8, requestBody: contracts.CountTokensRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/ss/{s}:countTokens", .{ client.base_url, model });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.countTokensResult"(client: *Client, model: []const u8, requestBody: contracts.CountTokensRequest) !ApiResult(contracts.CountTokensResponse) {
    return parseRawResponse(contracts.CountTokensResponse, try @"generativelanguage.models.countTokensRaw"(client, model, requestBody));
}

// Description:
// Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.
//
pub fn @"generativelanguage.models.operations.get"(client: *Client, name: []const u8) !Owned(contracts.Operation) {
    var result = try @"generativelanguage.models.operations.getResult"(client, name);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.operations.getRaw"(client: *Client, name: []const u8) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/models/{s}", .{ client.base_url, name });
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.operations.getResult"(client: *Client, name: []const u8) !ApiResult(contracts.Operation) {
    return parseRawResponse(contracts.Operation, try @"generativelanguage.models.operations.getRaw"(client, name));
}

// Description:
// Performs a prediction request.
//
pub fn @"generativelanguage.models.predict"(client: *Client, model: []const u8, requestBody: contracts.PredictRequest) !Owned(contracts.PredictResponse) {
    var result = try @"generativelanguage.models.predictResult"(client, model, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.predictRaw"(client: *Client, model: []const u8, requestBody: contracts.PredictRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/ss/{s}:predict", .{ client.base_url, model });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.predictResult"(client: *Client, model: []const u8, requestBody: contracts.PredictRequest) !ApiResult(contracts.PredictResponse) {
    return parseRawResponse(contracts.PredictResponse, try @"generativelanguage.models.predictRaw"(client, model, requestBody));
}

// Description:
// Generates a text embedding vector from the input `Content` using the specified [Gemini Embedding model](https://ai.google.dev/gemini-api/docs/models/gemini#text-embedding).
//
pub fn @"generativelanguage.models.embedContent"(client: *Client, model: []const u8, requestBody: contracts.EmbedContentRequest) !Owned(contracts.EmbedContentResponse) {
    var result = try @"generativelanguage.models.embedContentResult"(client, model, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn @"generativelanguage.models.embedContentRaw"(client: *Client, model: []const u8, requestBody: contracts.EmbedContentRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/v1beta/ss/{s}:embedContent", .{ client.base_url, model });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn @"generativelanguage.models.embedContentResult"(client: *Client, model: []const u8, requestBody: contracts.EmbedContentRequest) !ApiResult(contracts.EmbedContentResponse) {
    return parseRawResponse(contracts.EmbedContentResponse, try @"generativelanguage.models.embedContentRaw"(client, model, requestBody));
}

pub const resources = struct {
    pub const v1beta = struct {
        pub const models = struct {
            pub fn generativelanguage_models_list(client: *Client, pageSize: ?i64, pageToken: ?[]const u8) !Owned(contracts.ListModelsResponse) {
                return @"generativelanguage.models.list"(client, pageSize, pageToken);
            }
            pub fn generativelanguage_models_listResult(client: *Client, pageSize: ?i64, pageToken: ?[]const u8) !ApiResult(contracts.ListModelsResponse) {
                return @"generativelanguage.models.listResult"(client, pageSize, pageToken);
            }
            pub fn generativelanguage_models_operations_get(client: *Client, name: []const u8) !Owned(contracts.Operation) {
                return @"generativelanguage.models.operations.get"(client, name);
            }
            pub fn generativelanguage_models_operations_getResult(client: *Client, name: []const u8) !ApiResult(contracts.Operation) {
                return @"generativelanguage.models.operations.getResult"(client, name);
            }
            pub const _model__batchembedcontents = struct {
                pub fn generativelanguage_models_batchembedcontents(client: *Client, model: []const u8, requestBody: contracts.BatchEmbedContentsRequest) !Owned(contracts.BatchEmbedContentsResponse) {
                    return @"generativelanguage.models.batchEmbedContents"(client, model, requestBody);
                }
                pub fn generativelanguage_models_batchembedcontentsResult(client: *Client, model: []const u8, requestBody: contracts.BatchEmbedContentsRequest) !ApiResult(contracts.BatchEmbedContentsResponse) {
                    return @"generativelanguage.models.batchEmbedContentsResult"(client, model, requestBody);
                }
            };
            pub const _model__batchembedtext = struct {
                pub fn generativelanguage_models_batchembedtext(client: *Client, model: []const u8, requestBody: contracts.BatchEmbedTextRequest) !Owned(contracts.BatchEmbedTextResponse) {
                    return @"generativelanguage.models.batchEmbedText"(client, model, requestBody);
                }
                pub fn generativelanguage_models_batchembedtextResult(client: *Client, model: []const u8, requestBody: contracts.BatchEmbedTextRequest) !ApiResult(contracts.BatchEmbedTextResponse) {
                    return @"generativelanguage.models.batchEmbedTextResult"(client, model, requestBody);
                }
            };
            pub const _model__countmessagetokens = struct {
                pub fn generativelanguage_models_countmessagetokens(client: *Client, model: []const u8, requestBody: contracts.CountMessageTokensRequest) !Owned(contracts.CountMessageTokensResponse) {
                    return @"generativelanguage.models.countMessageTokens"(client, model, requestBody);
                }
                pub fn generativelanguage_models_countmessagetokensResult(client: *Client, model: []const u8, requestBody: contracts.CountMessageTokensRequest) !ApiResult(contracts.CountMessageTokensResponse) {
                    return @"generativelanguage.models.countMessageTokensResult"(client, model, requestBody);
                }
            };
            pub const _model__counttexttokens = struct {
                pub fn generativelanguage_models_counttexttokens(client: *Client, model: []const u8, requestBody: contracts.CountTextTokensRequest) !Owned(contracts.CountTextTokensResponse) {
                    return @"generativelanguage.models.countTextTokens"(client, model, requestBody);
                }
                pub fn generativelanguage_models_counttexttokensResult(client: *Client, model: []const u8, requestBody: contracts.CountTextTokensRequest) !ApiResult(contracts.CountTextTokensResponse) {
                    return @"generativelanguage.models.countTextTokensResult"(client, model, requestBody);
                }
            };
            pub const _model__counttokens = struct {
                pub fn generativelanguage_models_counttokens(client: *Client, model: []const u8, requestBody: contracts.CountTokensRequest) !Owned(contracts.CountTokensResponse) {
                    return @"generativelanguage.models.countTokens"(client, model, requestBody);
                }
                pub fn generativelanguage_models_counttokensResult(client: *Client, model: []const u8, requestBody: contracts.CountTokensRequest) !ApiResult(contracts.CountTokensResponse) {
                    return @"generativelanguage.models.countTokensResult"(client, model, requestBody);
                }
            };
            pub const _model__embedcontent = struct {
                pub fn generativelanguage_models_embedcontent(client: *Client, model: []const u8, requestBody: contracts.EmbedContentRequest) !Owned(contracts.EmbedContentResponse) {
                    return @"generativelanguage.models.embedContent"(client, model, requestBody);
                }
                pub fn generativelanguage_models_embedcontentResult(client: *Client, model: []const u8, requestBody: contracts.EmbedContentRequest) !ApiResult(contracts.EmbedContentResponse) {
                    return @"generativelanguage.models.embedContentResult"(client, model, requestBody);
                }
            };
            pub const _model__embedtext = struct {
                pub fn generativelanguage_models_embedtext(client: *Client, model: []const u8, requestBody: contracts.EmbedTextRequest) !Owned(contracts.EmbedTextResponse) {
                    return @"generativelanguage.models.embedText"(client, model, requestBody);
                }
                pub fn generativelanguage_models_embedtextResult(client: *Client, model: []const u8, requestBody: contracts.EmbedTextRequest) !ApiResult(contracts.EmbedTextResponse) {
                    return @"generativelanguage.models.embedTextResult"(client, model, requestBody);
                }
            };
            pub const _model__generateanswer = struct {
                pub fn generativelanguage_models_generateanswer(client: *Client, model: []const u8, requestBody: contracts.GenerateAnswerRequest) !Owned(contracts.GenerateAnswerResponse) {
                    return @"generativelanguage.models.generateAnswer"(client, model, requestBody);
                }
                pub fn generativelanguage_models_generateanswerResult(client: *Client, model: []const u8, requestBody: contracts.GenerateAnswerRequest) !ApiResult(contracts.GenerateAnswerResponse) {
                    return @"generativelanguage.models.generateAnswerResult"(client, model, requestBody);
                }
            };
            pub const _model__generatecontent = struct {
                pub fn generativelanguage_models_generatecontent(client: *Client, model: []const u8, requestBody: contracts.GenerateContentRequest) !Owned(contracts.GenerateContentResponse) {
                    return @"generativelanguage.models.generateContent"(client, model, requestBody);
                }
                pub fn generativelanguage_models_generatecontentResult(client: *Client, model: []const u8, requestBody: contracts.GenerateContentRequest) !ApiResult(contracts.GenerateContentResponse) {
                    return @"generativelanguage.models.generateContentResult"(client, model, requestBody);
                }
            };
            pub const _model__generatemessage = struct {
                pub fn generativelanguage_models_generatemessage(client: *Client, model: []const u8, requestBody: contracts.GenerateMessageRequest) !Owned(contracts.GenerateMessageResponse) {
                    return @"generativelanguage.models.generateMessage"(client, model, requestBody);
                }
                pub fn generativelanguage_models_generatemessageResult(client: *Client, model: []const u8, requestBody: contracts.GenerateMessageRequest) !ApiResult(contracts.GenerateMessageResponse) {
                    return @"generativelanguage.models.generateMessageResult"(client, model, requestBody);
                }
            };
            pub const _model__generatetext = struct {
                pub fn generativelanguage_models_generatetext(client: *Client, model: []const u8, requestBody: contracts.GenerateTextRequest) !Owned(contracts.GenerateTextResponse) {
                    return @"generativelanguage.models.generateText"(client, model, requestBody);
                }
                pub fn generativelanguage_models_generatetextResult(client: *Client, model: []const u8, requestBody: contracts.GenerateTextRequest) !ApiResult(contracts.GenerateTextResponse) {
                    return @"generativelanguage.models.generateTextResult"(client, model, requestBody);
                }
            };
            pub const _model__predict = struct {
                pub fn generativelanguage_models_predict(client: *Client, model: []const u8, requestBody: contracts.PredictRequest) !Owned(contracts.PredictResponse) {
                    return @"generativelanguage.models.predict"(client, model, requestBody);
                }
                pub fn generativelanguage_models_predictResult(client: *Client, model: []const u8, requestBody: contracts.PredictRequest) !ApiResult(contracts.PredictResponse) {
                    return @"generativelanguage.models.predictResult"(client, model, requestBody);
                }
            };
            pub const _model__predictlongrunning = struct {
                pub fn generativelanguage_models_predictlongrunning(client: *Client, model: []const u8, requestBody: contracts.PredictLongRunningRequest) !Owned(contracts.Operation) {
                    return @"generativelanguage.models.predictLongRunning"(client, model, requestBody);
                }
                pub fn generativelanguage_models_predictlongrunningResult(client: *Client, model: []const u8, requestBody: contracts.PredictLongRunningRequest) !ApiResult(contracts.Operation) {
                    return @"generativelanguage.models.predictLongRunningResult"(client, model, requestBody);
                }
            };
            pub const _model__streamgeneratecontent = struct {
                pub fn generativelanguage_models_streamgeneratecontent(client: *Client, model: []const u8, requestBody: contracts.GenerateContentRequest) !Owned(contracts.GenerateContentResponse) {
                    return @"generativelanguage.models.streamGenerateContent"(client, model, requestBody);
                }
                pub fn generativelanguage_models_streamgeneratecontentResult(client: *Client, model: []const u8, requestBody: contracts.GenerateContentRequest) !ApiResult(contracts.GenerateContentResponse) {
                    return @"generativelanguage.models.streamGenerateContentResult"(client, model, requestBody);
                }
            };
            pub const operations = struct {
                pub fn generativelanguage_models_operations_list(client: *Client, name: []const u8, filter: ?[]const u8, pageSize: ?i64, pageToken: ?[]const u8) !Owned(contracts.ListOperationsResponse) {
                    return @"generativelanguage.models.operations.list"(client, name, filter, pageSize, pageToken);
                }
                pub fn generativelanguage_models_operations_listResult(client: *Client, name: []const u8, filter: ?[]const u8, pageSize: ?i64, pageToken: ?[]const u8) !ApiResult(contracts.ListOperationsResponse) {
                    return @"generativelanguage.models.operations.listResult"(client, name, filter, pageSize, pageToken);
                }
            };
        };
    };
};

pub const v1beta = resources.v1beta;
