// <auto-generated>
//   This code was generated by openapi2zig 0.5.0 (1247924) on 2026-08-31 08:07:43 UTC
//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
//   Checksum: 64896e27c72945f5
// </auto-generated>

const std = @import("std");

pub const CodeExecutionResult = struct {
    outcome: ?[]const u8 = null,
    output: ?[]const u8 = null,
};

pub const GenerateAnswerRequest = struct {
    answerStyle: ?[]const u8 = null,
    temperature: ?f64 = null,
    semanticRetriever: ?SemanticRetrieverConfig = null,
    safetySettings: ?[]const SafetySetting = null,
    contents: ?[]const Content = null,
    inlinePassages: ?GroundingPassages = null,
};

pub const GenerateTextRequest = struct {
    maxOutputTokens: ?i64 = null,
    prompt: ?TextPrompt = null,
    temperature: ?f64 = null,
    candidateCount: ?i64 = null,
    topK: ?i64 = null,
    topP: ?f64 = null,
    safetySettings: ?[]const SafetySetting = null,
    stopSequences: ?[]const []const u8 = null,
};

pub const LogprobsResult = struct {
    topCandidates: ?[]const TopCandidates = null,
    chosenCandidates: ?[]const LogprobsResultCandidate = null,
};

pub const BatchEmbedTextResponse = struct {
    embeddings: ?[]const Embedding = null,
};

pub const PromptFeedback = struct {
    blockReason: ?[]const u8 = null,
    safetyRatings: ?[]const SafetyRating = null,
};

pub const CitationSource = struct {
    startIndex: ?i64 = null,
    license: ?[]const u8 = null,
    uri: ?[]const u8 = null,
    endIndex: ?i64 = null,
};

pub const CountTokensRequest = struct {
    generateContentRequest: ?GenerateContentRequest = null,
    contents: ?[]const Content = null,
};

pub const GroundingAttribution = struct {
    sourceId: ?AttributionSourceId = null,
    content: ?Content = null,
};

pub const GenerationConfig = struct {
    logprobs: ?i64 = null,
    responseLogprobs: ?bool = null,
    frequencyPenalty: ?f64 = null,
    maxOutputTokens: ?i64 = null,
    presencePenalty: ?f64 = null,
    responseSchema: ?Schema = null,
    temperature: ?f64 = null,
    candidateCount: ?i64 = null,
    responseMimeType: ?[]const u8 = null,
    topK: ?i64 = null,
    topP: ?f64 = null,
    stopSequences: ?[]const []const u8 = null,
};

pub const MetadataFilter = struct {
    conditions: ?[]const Condition = null,
    key: ?[]const u8 = null,
};

pub const PredictResponse = struct {
    predictions: ?[]const std.json.Value = null,
};

pub const Status = struct {
    details: ?[]const std.json.Value = null,
    message: ?[]const u8 = null,
    code: ?i64 = null,
};

pub const GenerateContentResponse = struct {
    modelVersion: ?[]const u8 = null,
    promptFeedback: ?PromptFeedback = null,
    candidates: ?[]const Candidate = null,
    usageMetadata: ?UsageMetadata = null,
};

pub const FunctionCall = struct {
    name: ?[]const u8 = null,
    args: ?std.json.Value = null,
};

pub const GenerateAnswerResponse = struct {
    inputFeedback: ?InputFeedback = null,
    answer: ?Candidate = null,
    answerableProbability: ?f64 = null,
};

pub const FunctionCallingConfig = struct {
    allowedFunctionNames: ?[]const []const u8 = null,
    mode: ?[]const u8 = null,
};

pub const CodeExecution = union(enum) {
    null,
    bool: bool,
    integer: i64,
    float: f64,
    number_string: []const u8,
    string: []const u8,
    array: std.json.Array,
    object: std.json.ObjectMap,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .null => .null,
            .bool => |value| .{ .bool = value },
            .integer => |value| .{ .integer = value },
            .float => |value| .{ .float = value },
            .number_string => |value| .{ .number_string = value },
            .string => |value| .{ .string = value },
            .array => |value| .{ .array = value },
            .object => |value| .{ .object = value },
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .null => try jw.write(null),
            .bool => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .float => |value| try jw.write(value),
            .number_string => |value| try jw.print("{s}", .{value}),
            .string => |value| try jw.write(value),
            .array => |value| try jw.write(value.items),
            .object => |value| {
                try jw.beginObject();
                var iterator = value.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
                try jw.endObject();
            },
        }
    }
};

pub const CitationMetadata = struct {
    citationSources: ?[]const CitationSource = null,
};

pub const Tool = struct {
    googleSearchRetrieval: ?GoogleSearchRetrieval = null,
    codeExecution: ?CodeExecution = null,
    functionDeclarations: ?[]const FunctionDeclaration = null,
};

pub const EmbedTextRequest = struct {
    text: ?[]const u8 = null,
    model: ?[]const u8 = null,
};

pub const CountTokensResponse = struct {
    cachedContentTokenCount: ?i64 = null,
    totalTokens: ?i64 = null,
};

pub const GenerateTextResponse = struct {
    candidates: ?[]const TextCompletion = null,
    filters: ?[]const ContentFilter = null,
    safetyFeedback: ?[]const SafetyFeedback = null,
};

pub const SemanticRetrieverConfig = struct {
    source: ?[]const u8 = null,
    metadataFilters: ?[]const MetadataFilter = null,
    query: ?Content = null,
    minimumRelevanceScore: ?f64 = null,
    maxChunksCount: ?i64 = null,
};

pub const GroundingPassage = struct {
    id: ?[]const u8 = null,
    content: ?Content = null,
};

pub const CountMessageTokensRequest = struct {
    prompt: ?MessagePrompt = null,
};

pub const FileData = struct {
    fileUri: ?[]const u8 = null,
    mimeType: ?[]const u8 = null,
};

pub const Part = struct {
    inlineData: ?Blob = null,
    codeExecutionResult: ?CodeExecutionResult = null,
    executableCode: ?ExecutableCode = null,
    functionResponse: ?FunctionResponse = null,
    text: ?[]const u8 = null,
    fileData: ?FileData = null,
    functionCall: ?FunctionCall = null,
};

pub const ListOperationsResponse = struct {
    nextPageToken: ?[]const u8 = null,
    operations: ?[]const Operation = null,
};

pub const LogprobsResultCandidate = struct {
    logProbability: ?f64 = null,
    token: ?[]const u8 = null,
    tokenId: ?i64 = null,
};

pub const EmbedContentRequest = struct {
    taskType: ?[]const u8 = null,
    model: ?[]const u8 = null,
    outputDimensionality: ?i64 = null,
    title: ?[]const u8 = null,
    content: ?Content = null,
};

pub const Blob = struct {
    data: ?[]const u8 = null,
    mimeType: ?[]const u8 = null,
};

pub const GroundingPassageId = struct {
    passageId: ?[]const u8 = null,
    partIndex: ?i64 = null,
};

pub const FunctionDeclaration = struct {
    description: ?[]const u8 = null,
    name: ?[]const u8 = null,
    parameters: ?Schema = null,
};

pub const GenerateContentRequest = struct {
    safetySettings: ?[]const SafetySetting = null,
    generationConfig: ?GenerationConfig = null,
    tools: ?[]const Tool = null,
    model: ?[]const u8 = null,
    systemInstruction: ?Content = null,
    cachedContent: ?[]const u8 = null,
    toolConfig: ?ToolConfig = null,
    contents: ?[]const Content = null,
};

pub const EmbedContentResponse = struct {
    embedding: ?ContentEmbedding = null,
};

pub const UsageMetadata = struct {
    cachedContentTokenCount: ?i64 = null,
    candidatesTokenCount: ?i64 = null,
    totalTokenCount: ?i64 = null,
    promptTokenCount: ?i64 = null,
};

pub const AttributionSourceId = struct {
    semanticRetrieverChunk: ?SemanticRetrieverChunk = null,
    groundingPassage: ?GroundingPassageId = null,
};

pub const ExecutableCode = struct {
    language: ?[]const u8 = null,
    code: ?[]const u8 = null,
};

pub const SafetySetting = struct {
    threshold: ?[]const u8 = null,
    category: ?[]const u8 = null,
};

pub const InputFeedback = struct {
    blockReason: ?[]const u8 = null,
    safetyRatings: ?[]const SafetyRating = null,
};

pub const FunctionResponse = struct {
    name: ?[]const u8 = null,
    response: ?std.json.Value = null,
};

pub const ContentEmbedding = struct {
    values: ?[]const f64 = null,
};

pub const DynamicRetrievalConfig = struct {
    mode: ?[]const u8 = null,
    dynamicThreshold: ?f64 = null,
};

pub const BatchEmbedTextRequest = struct {
    requests: ?[]const EmbedTextRequest = null,
    texts: ?[]const []const u8 = null,
};

pub const Message = struct {
    author: ?[]const u8 = null,
    citationMetadata: ?CitationMetadata = null,
    content: ?[]const u8 = null,
};

pub const Content = struct {
    parts: ?[]const Part = null,
    role: ?[]const u8 = null,
};

pub const Model = struct {
    displayName: ?[]const u8 = null,
    baseModelId: ?[]const u8 = null,
    maxTemperature: ?f64 = null,
    version: ?[]const u8 = null,
    supportedGenerationMethods: ?[]const []const u8 = null,
    description: ?[]const u8 = null,
    temperature: ?f64 = null,
    inputTokenLimit: ?i64 = null,
    name: ?[]const u8 = null,
    topK: ?i64 = null,
    topP: ?f64 = null,
    outputTokenLimit: ?i64 = null,
};

pub const Candidate = struct {
    content: ?Content = null,
    avgLogprobs: ?f64 = null,
    groundingAttributions: ?[]const GroundingAttribution = null,
    index: ?i64 = null,
    groundingMetadata: ?GroundingMetadata = null,
    logprobsResult: ?LogprobsResult = null,
    finishReason: ?[]const u8 = null,
    safetyRatings: ?[]const SafetyRating = null,
    tokenCount: ?i64 = null,
    citationMetadata: ?CitationMetadata = null,
};

pub const BatchEmbedContentsResponse = struct {
    embeddings: ?[]const ContentEmbedding = null,
};

pub const GroundingSupport = struct {
    groundingChunkIndices: ?[]const i64 = null,
    confidenceScores: ?[]const f64 = null,
    segment: ?Segment = null,
};

pub const Example = struct {
    output: ?Message = null,
    input: ?Message = null,
};

pub const RetrievalMetadata = struct {
    googleSearchDynamicRetrievalScore: ?f64 = null,
};

pub const Segment = struct {
    text: ?[]const u8 = null,
    startIndex: ?i64 = null,
    partIndex: ?i64 = null,
    endIndex: ?i64 = null,
};

pub const Operation = struct {
    @"error": ?Status = null,
    done: ?bool = null,
    metadata: ?std.json.Value = null,
    name: ?[]const u8 = null,
    response: ?std.json.Value = null,
};

pub const ContentFilter = struct {
    reason: ?[]const u8 = null,
    message: ?[]const u8 = null,
};

pub const Web = struct {
    uri: ?[]const u8 = null,
    title: ?[]const u8 = null,
};

pub const GoogleSearchRetrieval = struct {
    dynamicRetrievalConfig: ?DynamicRetrievalConfig = null,
};

pub const TopCandidates = struct {
    candidates: ?[]const LogprobsResultCandidate = null,
};

pub const SemanticRetrieverChunk = struct {
    source: ?[]const u8 = null,
    chunk: ?[]const u8 = null,
};

pub const GroundingChunk = struct {
    web: ?Web = null,
};

pub const EmbedTextResponse = struct {
    embedding: ?Embedding = null,
};

pub const GroundingMetadata = struct {
    retrievalMetadata: ?RetrievalMetadata = null,
    groundingChunks: ?[]const GroundingChunk = null,
    webSearchQueries: ?[]const []const u8 = null,
    groundingSupports: ?[]const GroundingSupport = null,
    searchEntryPoint: ?SearchEntryPoint = null,
};

pub const GenerateMessageResponse = struct {
    candidates: ?[]const Message = null,
    filters: ?[]const ContentFilter = null,
    messages: ?[]const Message = null,
};

pub const ListModelsResponse = struct {
    models: ?[]const Model = null,
    nextPageToken: ?[]const u8 = null,
};

pub const CountTextTokensRequest = struct {
    prompt: ?TextPrompt = null,
};

pub const GroundingPassages = struct {
    passages: ?[]const GroundingPassage = null,
};

pub const ToolConfig = struct {
    functionCallingConfig: ?FunctionCallingConfig = null,
};

pub const Embedding = struct {
    value: ?[]const f64 = null,
};

pub const SafetyRating = struct {
    blocked: ?bool = null,
    category: ?[]const u8 = null,
    probability: ?[]const u8 = null,
};

pub const CountTextTokensResponse = struct {
    tokenCount: ?i64 = null,
};

pub const PredictRequest = struct {
    parameters: ?std.json.Value = null,
    instances: ?[]const std.json.Value = null,
};

pub const SafetyFeedback = struct {
    rating: ?SafetyRating = null,
    setting: ?SafetySetting = null,
};

pub const Schema = struct {
    nullable: ?bool = null,
    format: ?[]const u8 = null,
    required: ?[]const []const u8 = null,
    minItems: ?[]const u8 = null,
    description: ?[]const u8 = null,
    items: ?*Schema = null,
    maxItems: ?[]const u8 = null,
    properties: ?std.json.Value = null,
    type: ?[]const u8 = null,
    @"enum": ?[]const []const u8 = null,
};

pub const TextCompletion = struct {
    safetyRatings: ?[]const SafetyRating = null,
    output: ?[]const u8 = null,
    citationMetadata: ?CitationMetadata = null,
};

pub const BatchEmbedContentsRequest = struct {
    requests: ?[]const EmbedContentRequest = null,
};

pub const PredictLongRunningRequest = struct {
    parameters: ?std.json.Value = null,
    instances: ?[]const std.json.Value = null,
};

pub const CountMessageTokensResponse = struct {
    tokenCount: ?i64 = null,
};

pub const TextPrompt = struct {
    text: ?[]const u8 = null,
};

pub const MessagePrompt = struct {
    context: ?[]const u8 = null,
    examples: ?[]const Example = null,
    messages: ?[]const Message = null,
};

pub const SearchEntryPoint = struct {
    renderedContent: ?[]const u8 = null,
    sdkBlob: ?[]const u8 = null,
};

pub const GenerateMessageRequest = struct {
    temperature: ?f64 = null,
    candidateCount: ?i64 = null,
    topK: ?i64 = null,
    topP: ?f64 = null,
    prompt: ?MessagePrompt = null,
};

pub const Condition = struct {
    stringValue: ?[]const u8 = null,
    operation: ?[]const u8 = null,
    numericValue: ?f64 = null,
};
