// <auto-generated>
//   This code was generated by openapi2zig 0.5.0 (f4781fa) on 2026-08-30 13:31:47 UTC
//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
//   Checksum: 18340239b09d2a6b
// </auto-generated>

const std = @import("std");
const contracts = @import("contracts.zig");
const runtime = @import("../runtime.zig");
const Owned = runtime.Owned;
const HttpObserver = runtime.HttpObserver;
const RawResponse = runtime.RawResponse;
const ParseErrorResponse = runtime.ParseErrorResponse;
const ApiResult = runtime.ApiResult;
const CancellationToken = runtime.CancellationToken;
const checkCancellation = runtime.checkCancellation;
const CancelableReader = runtime.CancelableReader;
const parseSseReader = runtime.parseSseReader;
const parseSseBytes = runtime.parseSseBytes;
const parseSseBytesTyped = runtime.parseSseBytesTyped;
const parseSseReaderTyped = runtime.parseSseReaderTyped;
const TypedSseCallback = runtime.TypedSseCallback;

pub const Client = struct {
    allocator: std.mem.Allocator,
    io: std.Io,
    http: std.http.Client,
    api_key: []const u8,
    base_url: []const u8 = "",
    organization: ?[]const u8 = null,
    project: ?[]const u8 = null,
    default_headers: []const std.http.Header = &.{},
    http_observer: ?HttpObserver = null,

    /// Optional predicate polled while reading a streaming response body.
    /// When it returns true, a successfully started background watcher interrupts
    /// a blocked SSE socket read within about 10 ms and the stream exits with
    /// error.Cancelled. A CancelableReader also checks the predicate at every read
    /// boundary. If watcher startup fails, cancellation remains read-boundary only.
    /// Point it at an app-level cancel flag; it composes with a CancellationToken.
    /// When null (default), no watcher thread is spawned.
    cancel_check: ?*const fn () bool = null,

    pub fn init(allocator: std.mem.Allocator, io: std.Io, api_key: []const u8) Client {
        return .{
            .allocator = allocator,
            .io = io,
            .http = .{ .allocator = allocator, .io = io },
            .api_key = api_key,
            .http_observer = null,
        };
    }

    pub fn deinit(self: *Client) void {
        self.http.deinit();
    }

    pub fn withBaseUrl(self: *Client, base_url: []const u8) void {
        self.base_url = base_url;
    }
    const CancelWatcher = struct {
        connection: ?*std.http.Client.Connection,
        io: std.Io,
        pred: *const fn () bool,
        done: *std.atomic.Value(bool),
        replacement_handle: ?std.Io.net.Socket.Handle = null,
        interrupted: bool = false,

        const Windows = if (@import("builtin").os.tag == .windows) struct {
            extern "kernel32" fn CreateEventW(event_attributes: ?*anyopaque, manual_reset: std.os.windows.BOOL, initial_state: std.os.windows.BOOL, name: ?[*:0]const u16) callconv(.winapi) ?std.os.windows.HANDLE;
        } else struct {};

        fn run(self: *CancelWatcher) void {
            while (!self.done.load(.acquire)) {
                if (self.pred()) {
                    if (self.connection) |conn| {
                        if (comptime @import("builtin").os.tag == .windows) {
                            if (Windows.CreateEventW(null, .FALSE, .FALSE, null)) |replacement| {
                                // Connection.destroy unconditionally closes the stream handle. Preserve
                                // a separately owned valid handle for it before closing the socket.
                                self.replacement_handle = replacement;
                                self.interrupted = true;
                                conn.stream_reader.stream.close(self.io);
                            } else {
                                self.interrupted = true;
                                conn.stream_reader.stream.shutdown(self.io, .both) catch {};
                            }
                        } else {
                            self.interrupted = true;
                            conn.stream_reader.stream.shutdown(self.io, .both) catch {};
                        }
                    }
                    return;
                }
                self.io.sleep(.{ .nanoseconds = 10 * std.time.ns_per_ms }, .awake) catch return;
            }
        }
    };
};

fn isQueryChar(c: u8) bool {
    return std.ascii.isAlphanumeric(c) or switch (c) {
        '-', '.', '_', '~' => true,
        else => false,
    };
}

fn writeQueryComponent(writer: *std.Io.Writer, value: []const u8) !void {
    try std.Uri.Component.percentEncode(writer, value, isQueryChar);
}

fn writeQueryValue(writer: *std.Io.Writer, value: anytype) !void {
    const T = @TypeOf(value);
    switch (@typeInfo(T)) {
        .pointer => |ptr| {
            if (ptr.size == .slice and ptr.child == u8) {
                try writeQueryComponent(writer, value);
            } else {
                try std.json.Stringify.value(value, .{}, writer);
            }
        },
        .int, .comptime_int, .float, .comptime_float, .bool => try writer.print("{}", .{value}),
        .@"enum" => try writeQueryComponent(writer, @tagName(value)),
        else => try std.json.Stringify.value(value, .{}, writer),
    }
}

fn appendQueryParam(writer: *std.Io.Writer, first_query: *bool, name: []const u8, value: anytype) !void {
    if (first_query.*) {
        try writer.writeByte('?');
        first_query.* = false;
    } else {
        try writer.writeByte('&');
    }
    try writeQueryComponent(writer, name);
    try writer.writeByte('=');
    try writeQueryValue(writer, value);
}

/// Serializes an `in: header` parameter value to an owned string. Reuses
/// the same primitive-type coverage as query parameters (string, integer,
/// float, boolean, enum). The caller frees the returned slice.
fn formatHeaderValue(allocator: std.mem.Allocator, value: anytype) ![]u8 {
    const T = @TypeOf(value);
    return switch (@typeInfo(T)) {
        .pointer => |ptr| blk: {
            if (ptr.size == .slice and ptr.child == u8) {
                break :blk try allocator.dupe(u8, value);
            }
            @compileError("OpenAPI header values must be strings, numbers, booleans, or enums");
        },
        .@"enum" => try allocator.dupe(u8, @tagName(value)),
        .int, .comptime_int, .float, .comptime_float, .bool => try std.fmt.allocPrint(allocator, "{}", .{value}),
        else => @compileError("OpenAPI header values must be strings, numbers, booleans, or enums"),
    };
}

/// Appends `value` under `name`, replacing (case-insensitively) any
/// existing header of the same name. Used so a declared operation header
/// parameter always wins over an equal-named client default header while
/// emitting exactly one header on the wire.
fn appendOrReplaceHeader(allocator: std.mem.Allocator, headers: *std.ArrayList(std.http.Header), name: []const u8, value: []const u8) !void {
    var i: usize = 0;
    while (i < headers.items.len) {
        if (std.ascii.eqlIgnoreCase(headers.items[i].name, name)) {
            _ = headers.orderedRemove(i);
        } else {
            i += 1;
        }
    }
    try headers.append(allocator, .{ .name = name, .value = value });
}

pub fn requestRaw(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8) !RawResponse {
    return requestRawWithContentType(client, method, url, payload, "application/json");
}

pub fn requestRawWithExtraHeaders(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8, extra_headers: []const std.http.Header) !RawResponse {
    return requestRawWithContentTypeAndExtraHeaders(client, method, url, payload, "application/json", extra_headers);
}

pub fn requestRawWithContentTypeAndExtraHeaders(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8, content_type_value: []const u8, extra_headers: []const std.http.Header) !RawResponse {
    const allocator = client.allocator;
    var headers = std.ArrayList(std.http.Header).empty;
    defer headers.deinit(allocator);
    const content_type: ?[]const u8 = if (payload != null) content_type_value else null;
    try appendClientHeaders(allocator, &headers, client, content_type, "application/json");
    for (extra_headers) |header| try appendOrReplaceHeader(allocator, &headers, header.name, header.value);

    if (client.http_observer) |obs| {
        if (obs.onRequest) |cb| cb(obs.ctx, method, url, headers.items, payload);
    }

    const uri = try std.Uri.parse(url);
    var response_body: std.Io.Writer.Allocating = .init(allocator);
    defer response_body.deinit();

    const start = std.Io.Clock.awake.now(client.io);
    const result = client.http.fetch(.{
        .location = .{ .uri = uri },
        .method = method,
        .extra_headers = headers.items,
        .payload = payload,
        .response_writer = &response_body.writer,
    }) catch |err| {
        if (client.http_observer) |obs| {
            if (obs.onError) |cb| cb(obs.ctx, method, url, @errorName(err));
        }
        return err;
    };
    const elapsed_ns = @as(u64, @intCast(start.untilNow(client.io, .awake).nanoseconds));

    const body = try response_body.toOwnedSlice();

    if (client.http_observer) |obs| {
        if (obs.onResponse) |cb| cb(obs.ctx, method, url, result.status, &.{}, body, elapsed_ns);
    }

    return .{
        .allocator = allocator,
        .status = result.status,
        .body = body,
    };
}

pub fn requestRawWithContentType(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8, content_type_value: []const u8) !RawResponse {
    const allocator = client.allocator;
    var headers = std.ArrayList(std.http.Header).empty;
    defer headers.deinit(allocator);
    const content_type: ?[]const u8 = if (payload != null) content_type_value else null;
    try appendClientHeaders(allocator, &headers, client, content_type, "application/json");

    if (client.http_observer) |obs| {
        if (obs.onRequest) |cb| cb(obs.ctx, method, url, headers.items, payload);
    }

    const uri = try std.Uri.parse(url);
    var response_body: std.Io.Writer.Allocating = .init(allocator);
    defer response_body.deinit();

    const start = std.Io.Clock.awake.now(client.io);
    const result = client.http.fetch(.{
        .location = .{ .uri = uri },
        .method = method,
        .extra_headers = headers.items,
        .payload = payload,
        .response_writer = &response_body.writer,
    }) catch |err| {
        if (client.http_observer) |obs| {
            if (obs.onError) |cb| cb(obs.ctx, method, url, @errorName(err));
        }
        return err;
    };
    const elapsed_ns = @as(u64, @intCast(start.untilNow(client.io, .awake).nanoseconds));

    const body = try response_body.toOwnedSlice();

    if (client.http_observer) |obs| {
        if (obs.onResponse) |cb| cb(obs.ctx, method, url, result.status, &.{}, body, elapsed_ns);
    }

    return .{
        .allocator = allocator,
        .status = result.status,
        .body = body,
    };
}

pub fn getRaw(client: *Client, path: []const u8) !RawResponse {
    const url = try std.fmt.allocPrint(client.allocator, "{s}{s}", .{ client.base_url, path });
    defer client.allocator.free(url);
    return requestRaw(client, .GET, url, null);
}

pub fn postJsonRaw(client: *Client, path: []const u8, payload: anytype) !RawResponse {
    const allocator = client.allocator;
    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(payload, .{ .emit_null_optional_fields = false }, &str.writer);

    const url = try std.fmt.allocPrint(allocator, "{s}{s}", .{ client.base_url, path });
    defer allocator.free(url);
    return requestRaw(client, .POST, url, str.written());
}

pub fn parseRawResponse(comptime T: type, raw: RawResponse) !ApiResult(T) {
    if (raw.status.class() != .success) return .{ .api_error = raw };
    const parsed = std.json.parseFromSlice(T, raw.allocator, raw.body, .{ .ignore_unknown_fields = true }) catch |err| {
        return .{ .parse_error = .{ .raw = raw, .error_name = @errorName(err) } };
    };
    return .{ .ok = .{ .allocator = raw.allocator, .body = raw.body, .parsed = parsed } };
}

pub fn getJsonResult(comptime T: type, client: *Client, path: []const u8) !ApiResult(T) {
    return parseRawResponse(T, try getRaw(client, path));
}

pub fn postJsonResult(comptime T: type, client: *Client, path: []const u8, payload: anytype) !ApiResult(T) {
    return parseRawResponse(T, try postJsonRaw(client, path, payload));
}
fn stringifyStreamRequest(allocator: std.mem.Allocator, requestBody: anytype) ![]u8 {
    var buf: std.Io.Writer.Allocating = .init(allocator);
    defer buf.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &buf.writer);

    var parsed = try std.json.parseFromSlice(std.json.Value, allocator, buf.written(), .{ .ignore_unknown_fields = true });
    defer parsed.deinit();

    if (parsed.value == .object) {
        try parsed.value.object.put(parsed.arena.allocator(), "stream", .{ .bool = true });
    }

    var out: std.Io.Writer.Allocating = .init(allocator);
    errdefer out.deinit();
    try std.json.Stringify.value(parsed.value, .{ .emit_null_optional_fields = false }, &out.writer);
    return try out.toOwnedSlice();
}

fn streamJsonTyped(comptime T: type, client: *Client, path: []const u8, requestBody: anytype, callback: anytype, cancellation_token: ?*CancellationToken) !void {
    return streamJsonTypedWithExtraHeaders(T, client, path, requestBody, callback, cancellation_token, &.{});
}

fn streamJsonTypedWithExtraHeaders(comptime T: type, client: *Client, path: []const u8, requestBody: anytype, callback: anytype, cancellation_token: ?*CancellationToken, extra_headers: []const std.http.Header) !void {
    const Callback = @TypeOf(callback.*);
    var typed_callback: TypedSseCallback(T, Callback) = .{ .allocator = client.allocator, .callback = callback };
    try streamJsonWithExtraHeaders(client, path, requestBody, &typed_callback, cancellation_token, extra_headers);
}

fn streamJson(client: *Client, path: []const u8, requestBody: anytype, callback: anytype, cancellation_token: ?*CancellationToken) !void {
    return streamJsonWithExtraHeaders(client, path, requestBody, callback, cancellation_token, &.{});
}

fn streamJsonWithExtraHeaders(client: *Client, path: []const u8, requestBody: anytype, callback: anytype, cancellation_token: ?*CancellationToken, extra_headers: []const std.http.Header) !void {
    const allocator = client.allocator;
    const payload = try stringifyStreamRequest(allocator, requestBody);
    defer allocator.free(payload);

    var headers = std.ArrayList(std.http.Header).empty;
    defer headers.deinit(allocator);
    try appendClientHeaders(allocator, &headers, client, "application/json", "text/event-stream");
    for (extra_headers) |header| try appendOrReplaceHeader(allocator, &headers, header.name, header.value);

    const url = try std.fmt.allocPrint(allocator, "{s}{s}", .{ client.base_url, path });
    defer allocator.free(url);

    if (client.http_observer) |obs| {
        if (obs.onRequest) |cb| cb(obs.ctx, .POST, url, headers.items, payload);
    }

    const uri = try std.Uri.parse(url);
    try checkCancellation(cancellation_token);

    const start = std.Io.Clock.awake.now(client.io);
    var req = client.http.request(.POST, uri, .{
        .redirect_behavior = .unhandled,
        .headers = .{ .accept_encoding = .{ .override = "identity" } },
        .extra_headers = headers.items,
    }) catch |err| {
        if (client.http_observer) |obs| {
            if (obs.onError) |cb| cb(obs.ctx, .POST, url, @errorName(err));
        }
        return err;
    };
    defer req.deinit();

    req.transfer_encoding = .{ .content_length = payload.len };
    var request_body = try req.sendBodyUnflushed(&.{});
    try request_body.writer.writeAll(payload);
    try request_body.end();
    try req.connection.?.flush();
    try checkCancellation(cancellation_token);

    var response = req.receiveHead(&.{}) catch |err| {
        if (client.http_observer) |obs| {
            if (obs.onError) |cb| cb(obs.ctx, .POST, url, @errorName(err));
        }
        return err;
    };
    const elapsed_ns = @as(u64, @intCast(start.untilNow(client.io, .awake).nanoseconds));
    if (response.head.status.class() != .success) {
        if (client.http_observer) |obs| {
            if (obs.onResponse) |cb| cb(obs.ctx, .POST, url, response.head.status, &.{}, "", elapsed_ns);
        }
        return error.ResponseError;
    }

    if (client.http_observer) |obs| {
        if (obs.onResponse) |cb| cb(obs.ctx, .POST, url, response.head.status, &.{}, "", elapsed_ns);
    }

    var transfer_buffer: [8 * 1024]u8 = undefined;
    const response_reader = response.reader(&transfer_buffer);
    if (client.cancel_check) |pred| {
        var done = std.atomic.Value(bool).init(false);
        var watcher_ctx = Client.CancelWatcher{ .connection = req.connection, .io = client.io, .pred = pred, .done = &done };
        const watcher_thread: ?std.Thread = std.Thread.spawn(.{}, Client.CancelWatcher.run, .{&watcher_ctx}) catch null;
        defer if (watcher_thread) |thread| {
            done.store(true, .release);
            thread.join();
            if (watcher_ctx.interrupted) {
                const conn = watcher_ctx.connection.?;
                if (comptime @import("builtin").os.tag == .windows) {
                    if (watcher_ctx.replacement_handle) |handle| {
                        conn.stream_reader.stream.socket.handle = handle;
                        conn.stream_writer.stream.socket.handle = handle;
                    }
                }
                conn.closing = true;
            }
        };
        var cancelable_buffer: [1]u8 = undefined;
        var cancelable_reader = CancelableReader.init(response_reader, &cancelable_buffer, pred);
        parseSseReader(allocator, &cancelable_reader.reader, callback, cancellation_token) catch |err| switch (err) {
            error.ReadFailed => {
                if (pred()) return error.Cancelled;
                return response.bodyErr() orelse err;
            },
            else => return err,
        };
    } else {
        parseSseReader(allocator, response_reader, callback, cancellation_token) catch |err| switch (err) {
            error.ReadFailed => return response.bodyErr() orelse err,
            else => return err,
        };
    }
}
fn appendClientHeaders(allocator: std.mem.Allocator, headers: *std.ArrayList(std.http.Header), client: *Client, content_type: ?[]const u8, accept: []const u8) !void {
    if (content_type) |ct| {
        try headers.append(allocator, .{ .name = "Content-Type", .value = ct });
    }
    try headers.append(allocator, .{ .name = "Accept", .value = accept });
    if (client.organization) |organization| {
        try headers.append(allocator, .{ .name = "OpenAI-Organization", .value = organization });
    }
    if (client.project) |project| {
        try headers.append(allocator, .{ .name = "OpenAI-Project", .value = project });
    }
    for (client.default_headers) |header| {
        try headers.append(allocator, header);
    }
}

/////////////////
// Summary:
// List stored Chat Completions. Only Chat Completions that have been stored
// with the `store` parameter set to `true` will be returned.
//
//
pub fn listChatCompletions(client: *Client, model: ?[]const u8, metadata: ?[]const u8, after: ?[]const u8, limit: ?i64, order: ?[]const u8) !Owned(contracts.ChatCompletionList) {
    var result = try listChatCompletionsResult(client, model, metadata, after, limit, order);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn listChatCompletionsRaw(client: *Client, model: ?[]const u8, metadata: ?[]const u8, after: ?[]const u8, limit: ?i64, order: ?[]const u8) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/chat/completions", .{client.base_url});
    var first_query = true;
    if (model) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "model", value);
    }
    if (metadata) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "metadata", value);
    }
    if (after) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "after", value);
    }
    if (limit) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "limit", value);
    }
    if (order) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "order", value);
    }
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn listChatCompletionsResult(client: *Client, model: ?[]const u8, metadata: ?[]const u8, after: ?[]const u8, limit: ?i64, order: ?[]const u8) !ApiResult(contracts.ChatCompletionList) {
    return parseRawResponse(contracts.ChatCompletionList, try listChatCompletionsRaw(client, model, metadata, after, limit, order));
}

/////////////////
// Summary:
// **Starting a new project?** We recommend trying [Responses](/docs/api-reference/responses)
// to take advantage of the latest OpenAI platform features. Compare
// [Chat Completions with Responses](/docs/guides/responses-vs-chat-completions?api-mode=responses).
//
// ---
//
// Creates a model response for the given chat conversation. Learn more in the
// [text generation](/docs/guides/text-generation), [vision](/docs/guides/vision),
// and [audio](/docs/guides/audio) guides.
//
// Parameter support can differ depending on the model used to generate the
// response, particularly for newer reasoning models. Parameters that are only
// supported for reasoning models are noted below. For the current state of
// unsupported parameters in reasoning models,
// [refer to the reasoning guide](/docs/guides/reasoning).
//
// Returns a chat completion object, or a streamed sequence of chat completion
// chunk objects if the request is streamed.
//
//
pub fn createChatCompletion(client: *Client, requestBody: contracts.CreateChatCompletionRequest) !Owned(contracts.CreateChatCompletionResponse) {
    var result = try createChatCompletionResult(client, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn createChatCompletionRaw(client: *Client, requestBody: contracts.CreateChatCompletionRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/chat/completions", .{client.base_url});

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn createChatCompletionResult(client: *Client, requestBody: contracts.CreateChatCompletionRequest) !ApiResult(contracts.CreateChatCompletionResponse) {
    return parseRawResponse(contracts.CreateChatCompletionResponse, try createChatCompletionRaw(client, requestBody));
}

pub fn createChatCompletionStreaming(client: *Client, requestBody: anytype, callback: anytype, cancellation_token: ?*CancellationToken) !void {
    var stream_headers = std.ArrayList(std.http.Header).empty;
    defer stream_headers.deinit(client.allocator);
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| client.allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(client.allocator, "Bearer {s}", .{client.api_key});
        try stream_headers.append(client.allocator, .{ .name = "Authorization", .value = auth_header.? });
    }
    return streamJsonWithExtraHeaders(client, "/chat/completions", requestBody, callback, cancellation_token, stream_headers.items);
}

pub fn createChatCompletionStreamingEvents(comptime Event: type, client: *Client, requestBody: anytype, callback: anytype, cancellation_token: ?*CancellationToken) !void {
    var stream_headers = std.ArrayList(std.http.Header).empty;
    defer stream_headers.deinit(client.allocator);
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| client.allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(client.allocator, "Bearer {s}", .{client.api_key});
        try stream_headers.append(client.allocator, .{ .name = "Authorization", .value = auth_header.? });
    }
    return streamJsonTypedWithExtraHeaders(Event, client, "/chat/completions", requestBody, callback, cancellation_token, stream_headers.items);
}

/////////////////
// Summary:
// Get a stored chat completion. Only Chat Completions that have been created
// with the `store` parameter set to `true` will be returned.
//
//
pub fn getChatCompletion(client: *Client, completion_id: []const u8) !Owned(contracts.CreateChatCompletionResponse) {
    var result = try getChatCompletionResult(client, completion_id);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn getChatCompletionRaw(client: *Client, completion_id: []const u8) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/chat/completions/{s}", .{ client.base_url, completion_id });
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn getChatCompletionResult(client: *Client, completion_id: []const u8) !ApiResult(contracts.CreateChatCompletionResponse) {
    return parseRawResponse(contracts.CreateChatCompletionResponse, try getChatCompletionRaw(client, completion_id));
}

/////////////////
// Summary:
// Modify a stored chat completion. Only Chat Completions that have been
// created with the `store` parameter set to `true` can be modified. Currently,
// the only supported modification is to update the `metadata` field.
//
//
pub fn updateChatCompletion(client: *Client, completion_id: []const u8, requestBody: std.json.Value) !Owned(contracts.CreateChatCompletionResponse) {
    var result = try updateChatCompletionResult(client, completion_id, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn updateChatCompletionRaw(client: *Client, completion_id: []const u8, requestBody: std.json.Value) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/chat/completions/{s}", .{ client.base_url, completion_id });

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn updateChatCompletionResult(client: *Client, completion_id: []const u8, requestBody: std.json.Value) !ApiResult(contracts.CreateChatCompletionResponse) {
    return parseRawResponse(contracts.CreateChatCompletionResponse, try updateChatCompletionRaw(client, completion_id, requestBody));
}

/////////////////
// Summary:
// Delete a stored chat completion. Only Chat Completions that have been
// created with the `store` parameter set to `true` can be deleted.
//
//
pub fn deleteChatCompletion(client: *Client, completion_id: []const u8) !Owned(contracts.ChatCompletionDeleted) {
    var result = try deleteChatCompletionResult(client, completion_id);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn deleteChatCompletionRaw(client: *Client, completion_id: []const u8) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/chat/completions/{s}", .{ client.base_url, completion_id });
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.DELETE, uri_buf.written(), payload, operation_headers.items);
}

pub fn deleteChatCompletionResult(client: *Client, completion_id: []const u8) !ApiResult(contracts.ChatCompletionDeleted) {
    return parseRawResponse(contracts.ChatCompletionDeleted, try deleteChatCompletionRaw(client, completion_id));
}

/////////////////
// Summary:
// Get the messages in a stored chat completion. Only Chat Completions that
// have been created with the `store` parameter set to `true` will be
// returned.
//
//
pub fn getChatCompletionMessages(client: *Client, completion_id: []const u8, after: ?[]const u8, limit: ?i64, order: ?[]const u8) !Owned(contracts.ChatCompletionMessageList) {
    var result = try getChatCompletionMessagesResult(client, completion_id, after, limit, order);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn getChatCompletionMessagesRaw(client: *Client, completion_id: []const u8, after: ?[]const u8, limit: ?i64, order: ?[]const u8) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/chat/completions/{s}/messages", .{ client.base_url, completion_id });
    var first_query = true;
    if (after) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "after", value);
    }
    if (limit) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "limit", value);
    }
    if (order) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "order", value);
    }
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn getChatCompletionMessagesResult(client: *Client, completion_id: []const u8, after: ?[]const u8, limit: ?i64, order: ?[]const u8) !ApiResult(contracts.ChatCompletionMessageList) {
    return parseRawResponse(contracts.ChatCompletionMessageList, try getChatCompletionMessagesRaw(client, completion_id, after, limit, order));
}

/////////////////
// Summary:
// Lists the currently available models, and provides basic information about each one such as the owner and availability.
//
pub fn listModels(client: *Client) !Owned(contracts.ListModelsResponse) {
    var result = try listModelsResult(client);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn listModelsRaw(client: *Client) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/models", .{client.base_url});
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn listModelsResult(client: *Client) !ApiResult(contracts.ListModelsResponse) {
    return parseRawResponse(contracts.ListModelsResponse, try listModelsRaw(client));
}

/////////////////
// Summary:
// Retrieves a model instance, providing basic information about the model such as the owner and permissioning.
//
pub fn retrieveModel(client: *Client, model: []const u8) !Owned(contracts.Model) {
    var result = try retrieveModelResult(client, model);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn retrieveModelRaw(client: *Client, model: []const u8) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/ss/{s}", .{ client.base_url, model });
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn retrieveModelResult(client: *Client, model: []const u8) !ApiResult(contracts.Model) {
    return parseRawResponse(contracts.Model, try retrieveModelRaw(client, model));
}

/////////////////
// Summary:
// Delete a fine-tuned model. You must have the Owner role in your organization to delete a model.
//
pub fn deleteModel(client: *Client, model: []const u8) !Owned(contracts.DeleteModelResponse) {
    var result = try deleteModelResult(client, model);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn deleteModelRaw(client: *Client, model: []const u8) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/ss/{s}", .{ client.base_url, model });
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.DELETE, uri_buf.written(), payload, operation_headers.items);
}

pub fn deleteModelResult(client: *Client, model: []const u8) !ApiResult(contracts.DeleteModelResponse) {
    return parseRawResponse(contracts.DeleteModelResponse, try deleteModelRaw(client, model));
}

pub const resources = struct {
    pub const chat = struct {
        pub const completions = struct {
            pub fn create(client: *Client, requestBody: contracts.CreateChatCompletionRequest) !Owned(contracts.CreateChatCompletionResponse) {
                return createChatCompletion(client, requestBody);
            }
            pub fn createResult(client: *Client, requestBody: contracts.CreateChatCompletionRequest) !ApiResult(contracts.CreateChatCompletionResponse) {
                return createChatCompletionResult(client, requestBody);
            }
            pub fn createChatCompletionStream(client: *Client, requestBody: anytype, callback: anytype, cancellation_token: ?*CancellationToken) !void {
                return createChatCompletionStreaming(client, requestBody, callback, cancellation_token);
            }
            pub fn createChatCompletionStreamEvents(comptime Event: type, client: *Client, requestBody: anytype, callback: anytype, cancellation_token: ?*CancellationToken) !void {
                return createChatCompletionStreamingEvents(Event, client, requestBody, callback, cancellation_token);
            }
            pub fn delete(client: *Client, completion_id: []const u8) !Owned(contracts.ChatCompletionDeleted) {
                return deleteChatCompletion(client, completion_id);
            }
            pub fn deleteResult(client: *Client, completion_id: []const u8) !ApiResult(contracts.ChatCompletionDeleted) {
                return deleteChatCompletionResult(client, completion_id);
            }
            pub fn get(client: *Client, completion_id: []const u8) !Owned(contracts.CreateChatCompletionResponse) {
                return getChatCompletion(client, completion_id);
            }
            pub fn getResult(client: *Client, completion_id: []const u8) !ApiResult(contracts.CreateChatCompletionResponse) {
                return getChatCompletionResult(client, completion_id);
            }
            pub fn list(client: *Client, model: ?[]const u8, metadata: ?[]const u8, after: ?[]const u8, limit: ?i64, order: ?[]const u8) !Owned(contracts.ChatCompletionList) {
                return listChatCompletions(client, model, metadata, after, limit, order);
            }
            pub fn listResult(client: *Client, model: ?[]const u8, metadata: ?[]const u8, after: ?[]const u8, limit: ?i64, order: ?[]const u8) !ApiResult(contracts.ChatCompletionList) {
                return listChatCompletionsResult(client, model, metadata, after, limit, order);
            }
            pub fn update(client: *Client, completion_id: []const u8, requestBody: std.json.Value) !Owned(contracts.CreateChatCompletionResponse) {
                return updateChatCompletion(client, completion_id, requestBody);
            }
            pub fn updateResult(client: *Client, completion_id: []const u8, requestBody: std.json.Value) !ApiResult(contracts.CreateChatCompletionResponse) {
                return updateChatCompletionResult(client, completion_id, requestBody);
            }
            pub const messages = struct {
                pub fn getchatcompletionmessages_(client: *Client, completion_id: []const u8, after: ?[]const u8, limit: ?i64, order: ?[]const u8) !Owned(contracts.ChatCompletionMessageList) {
                    return getChatCompletionMessages(client, completion_id, after, limit, order);
                }
                pub fn getchatcompletionmessages_Result(client: *Client, completion_id: []const u8, after: ?[]const u8, limit: ?i64, order: ?[]const u8) !ApiResult(contracts.ChatCompletionMessageList) {
                    return getChatCompletionMessagesResult(client, completion_id, after, limit, order);
                }
            };
        };
    };
    pub const models = struct {
        pub fn delete(client: *Client, model: []const u8) !Owned(contracts.DeleteModelResponse) {
            return deleteModel(client, model);
        }
        pub fn deleteResult(client: *Client, model: []const u8) !ApiResult(contracts.DeleteModelResponse) {
            return deleteModelResult(client, model);
        }
        pub fn list(client: *Client) !Owned(contracts.ListModelsResponse) {
            return listModels(client);
        }
        pub fn listResult(client: *Client) !ApiResult(contracts.ListModelsResponse) {
            return listModelsResult(client);
        }
        pub fn retrieve(client: *Client, model: []const u8) !Owned(contracts.Model) {
            return retrieveModel(client, model);
        }
        pub fn retrieveResult(client: *Client, model: []const u8) !ApiResult(contracts.Model) {
            return retrieveModelResult(client, model);
        }
    };
};

pub const chat = resources.chat;
pub const models = resources.models;
