// <auto-generated>
//   This code was generated by openapi2zig 0.5.0 (240c22f) on 2026-08-29 22:18:33 UTC
//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
//   Checksum: dfcdee62ca495682
// </auto-generated>

const std = @import("std");

pub const ChatCompletionAllowedToolsChoice = struct {
    allowed_tools: ChatCompletionAllowedTools,
    type: []const u8,
};

pub const CreateChatCompletionResponseChoicesItemLogprobs = ?std.json.Value;

pub const CreateChatCompletionResponseChoicesItem = struct {
    logprobs: ?CreateChatCompletionResponseChoicesItemLogprobs,
    finish_reason: []const u8,
    index: i64,
    message: ChatCompletionResponseMessage,
};

pub const CreateChatCompletionResponse = struct {
    choices: []const CreateChatCompletionResponseChoicesItem,
    system_fingerprint: ?[]const u8 = null,
    object: []const u8,
    model: []const u8,
    id: []const u8,
    service_tier: ?[]const u8 = null,
    created: i64,
    usage: ?CompletionUsage = null,
};

pub const ChatCompletionRequestSystemMessageContentPart = union(enum) {
    chat_completion_request_message_content_part_text: ChatCompletionRequestMessageContentPartText,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(ChatCompletionRequestMessageContentPartText, allocator, source, options)) |value| {
            return .{ .chat_completion_request_message_content_part_text = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .chat_completion_request_message_content_part_text => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const Verbosity = ?[]const u8;

pub const ChatCompletionMessageCustomToolCallCustom = struct {
    name: []const u8,
    input: []const u8,
};

pub const ChatCompletionMessageCustomToolCall = struct {
    custom: ChatCompletionMessageCustomToolCallCustom,
    id: []const u8,
    type: []const u8,
};

pub const ResponseFormatText = struct {
    type: []const u8,
};

pub const StopConfigurationVariant0 = ?[]const u8;

pub const StopConfigurationVariant1 = []const []const u8;

pub const StopConfiguration = union(enum) {
    string: ?[]const u8,
    strings: []const []const u8,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(?[]const u8, allocator, source, options)) |value| {
            return .{ .string = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky([]const []const u8, allocator, source, options)) |value| {
            return .{ .strings = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .string => |value| try jw.write(value),
            .strings => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ChatCompletionRequestToolMessageContentPart = union(enum) {
    chat_completion_request_message_content_part_text: ChatCompletionRequestMessageContentPartText,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(ChatCompletionRequestMessageContentPartText, allocator, source, options)) |value| {
            return .{ .chat_completion_request_message_content_part_text = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .chat_completion_request_message_content_part_text => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ChatCompletionMessageToolCallFunction = struct {
    arguments: []const u8,
    name: []const u8,
};

pub const ChatCompletionMessageToolCall = struct {
    id: []const u8,
    type: []const u8,
    function: ChatCompletionMessageToolCallFunction,
};

pub const ChatCompletionRequestFunctionMessage = struct {
    role: []const u8,
    name: []const u8,
    content: ?[]const u8,
};

pub const ChatCompletionFunctions = struct {
    description: ?[]const u8 = null,
    name: []const u8,
    parameters: ?FunctionParameters = null,
};

pub const ChatCompletionRequestMessageContentPartFileFile = struct {
    file_id: ?[]const u8 = null,
    filename: ?[]const u8 = null,
    file_data: ?[]const u8 = null,
};

pub const ChatCompletionRequestMessageContentPartFile = struct {
    file: ChatCompletionRequestMessageContentPartFileFile,
    type: []const u8,
};

pub const Metadata = ?std.json.Value;

pub const ReasoningEffort = ?[]const u8;

pub const ChatCompletionToolChoiceOptionVariant0 = []const u8;

pub const ChatCompletionToolChoiceOption = union(enum) {
    none,
    auto,
    required,
    chat_completion_allowed_tools_choice: ChatCompletionAllowedToolsChoice,
    chat_completion_named_tool_choice: ChatCompletionNamedToolChoice,
    chat_completion_named_tool_choice_custom: ChatCompletionNamedToolChoiceCustom,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (source == .string and std.mem.eql(u8, source.string, "none")) return .none;
        if (source == .string and std.mem.eql(u8, source.string, "auto")) return .auto;
        if (source == .string and std.mem.eql(u8, source.string, "required")) return .required;
        if (std.json.parseFromValueLeaky(ChatCompletionAllowedToolsChoice, allocator, source, options)) |value| {
            return .{ .chat_completion_allowed_tools_choice = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ChatCompletionNamedToolChoice, allocator, source, options)) |value| {
            return .{ .chat_completion_named_tool_choice = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ChatCompletionNamedToolChoiceCustom, allocator, source, options)) |value| {
            return .{ .chat_completion_named_tool_choice_custom = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .none => try jw.write("none"),
            .auto => try jw.write("auto"),
            .required => try jw.write("required"),
            .chat_completion_allowed_tools_choice => |value| try jw.write(value),
            .chat_completion_named_tool_choice => |value| try jw.write(value),
            .chat_completion_named_tool_choice_custom => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ParallelToolCalls = bool;

pub const ChatCompletionRequestMessage = union(enum) {
    developer: ChatCompletionRequestDeveloperMessage,
    system: ChatCompletionRequestSystemMessage,
    user: ChatCompletionRequestUserMessage,
    assistant: ChatCompletionRequestAssistantMessage,
    tool: ChatCompletionRequestToolMessage,
    function: ChatCompletionRequestFunctionMessage,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (source != .object) return error.UnexpectedToken;
        const discriminator = source.object.get("role") orelse return .{ .raw = source };
        if (discriminator != .string) return .{ .raw = source };
        if (std.mem.eql(u8, discriminator.string, "developer")) {
            return .{ .developer = try std.json.parseFromValueLeaky(ChatCompletionRequestDeveloperMessage, allocator, source, options) };
        }
        if (std.mem.eql(u8, discriminator.string, "system")) {
            return .{ .system = try std.json.parseFromValueLeaky(ChatCompletionRequestSystemMessage, allocator, source, options) };
        }
        if (std.mem.eql(u8, discriminator.string, "user")) {
            return .{ .user = try std.json.parseFromValueLeaky(ChatCompletionRequestUserMessage, allocator, source, options) };
        }
        if (std.mem.eql(u8, discriminator.string, "assistant")) {
            return .{ .assistant = try std.json.parseFromValueLeaky(ChatCompletionRequestAssistantMessage, allocator, source, options) };
        }
        if (std.mem.eql(u8, discriminator.string, "tool")) {
            return .{ .tool = try std.json.parseFromValueLeaky(ChatCompletionRequestToolMessage, allocator, source, options) };
        }
        if (std.mem.eql(u8, discriminator.string, "function")) {
            return .{ .function = try std.json.parseFromValueLeaky(ChatCompletionRequestFunctionMessage, allocator, source, options) };
        }

        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .developer => |value| try jw.write(value),
            .system => |value| try jw.write(value),
            .user => |value| try jw.write(value),
            .assistant => |value| try jw.write(value),
            .tool => |value| try jw.write(value),
            .function => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ChatCompletionMessageListDataItemFunctionCall = struct {
    arguments: []const u8,
    name: []const u8,
};

pub const ChatCompletionMessageListDataItemAudio = ?std.json.Value;

pub const ChatCompletionMessageListDataItemAnnotationsItemUrlCitation = struct {
    end_index: i64,
    start_index: i64,
    url: []const u8,
    title: []const u8,
};

pub const ChatCompletionMessageListDataItemAnnotationsItem = struct {
    url_citation: ChatCompletionMessageListDataItemAnnotationsItemUrlCitation,
    type: []const u8,
};

pub const ChatCompletionMessageListDataItemContentPartsItem = union(enum) {
    chat_completion_request_message_content_part_text: ChatCompletionRequestMessageContentPartText,
    chat_completion_request_message_content_part_image: ChatCompletionRequestMessageContentPartImage,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(ChatCompletionRequestMessageContentPartText, allocator, source, options)) |value| {
            return .{ .chat_completion_request_message_content_part_text = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ChatCompletionRequestMessageContentPartImage, allocator, source, options)) |value| {
            return .{ .chat_completion_request_message_content_part_image = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .chat_completion_request_message_content_part_text => |value| try jw.write(value),
            .chat_completion_request_message_content_part_image => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ChatCompletionMessageListDataItem = struct {
    function_call: ?ChatCompletionMessageListDataItemFunctionCall = null,
    audio: ?ChatCompletionMessageListDataItemAudio = null,
    annotations: ?[]const ChatCompletionMessageListDataItemAnnotationsItem = null,
    tool_calls: ?ChatCompletionMessageToolCalls = null,
    content_parts: ?[]const ChatCompletionMessageListDataItemContentPartsItem = null,
    role: []const u8,
    id: []const u8,
    refusal: ?[]const u8,
    content: ?[]const u8,
};

pub const ChatCompletionMessageList = struct {
    object: []const u8,
    data: []const ChatCompletionMessageListDataItem,
    last_id: []const u8,
    has_more: bool,
    first_id: []const u8,
};

pub const ChatCompletionRequestMessageContentPartAudioInputAudio = struct {
    data: []const u8,
    format: []const u8,
};

pub const ChatCompletionRequestMessageContentPartAudio = struct {
    input_audio: ChatCompletionRequestMessageContentPartAudioInputAudio,
    type: []const u8,
};

pub const ChatCompletionRequestMessageContentPartText = struct {
    text: []const u8,
    type: []const u8,
};

pub const ChatCompletionRequestUserMessageContentPart = union(enum) {
    chat_completion_request_message_content_part_text: ChatCompletionRequestMessageContentPartText,
    chat_completion_request_message_content_part_image: ChatCompletionRequestMessageContentPartImage,
    chat_completion_request_message_content_part_audio: ChatCompletionRequestMessageContentPartAudio,
    chat_completion_request_message_content_part_file: ChatCompletionRequestMessageContentPartFile,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(ChatCompletionRequestMessageContentPartText, allocator, source, options)) |value| {
            return .{ .chat_completion_request_message_content_part_text = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ChatCompletionRequestMessageContentPartImage, allocator, source, options)) |value| {
            return .{ .chat_completion_request_message_content_part_image = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ChatCompletionRequestMessageContentPartAudio, allocator, source, options)) |value| {
            return .{ .chat_completion_request_message_content_part_audio = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ChatCompletionRequestMessageContentPartFile, allocator, source, options)) |value| {
            return .{ .chat_completion_request_message_content_part_file = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .chat_completion_request_message_content_part_text => |value| try jw.write(value),
            .chat_completion_request_message_content_part_image => |value| try jw.write(value),
            .chat_completion_request_message_content_part_audio => |value| try jw.write(value),
            .chat_completion_request_message_content_part_file => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ResponseFormatJsonObject = struct {
    type: []const u8,
};

pub const ChatCompletionRequestToolMessageContentVariant0 = []const u8;

pub const ChatCompletionRequestToolMessageContentVariant1 = []const ChatCompletionRequestToolMessageContentPart;

pub const ChatCompletionRequestToolMessageContent = union(enum) {
    text: []const u8,
    array_of_content_parts: []const ChatCompletionRequestToolMessageContentPart,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky([]const u8, allocator, source, options)) |value| {
            return .{ .text = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky([]const ChatCompletionRequestToolMessageContentPart, allocator, source, options)) |value| {
            return .{ .array_of_content_parts = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .text => |value| try jw.write(value),
            .array_of_content_parts => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ChatCompletionRequestToolMessage = struct {
    tool_call_id: []const u8,
    role: []const u8,
    content: ChatCompletionRequestToolMessageContent,
};

pub const VoiceIdsOrCustomVoiceVariant1 = struct {
    id: []const u8,
};

pub const VoiceIdsOrCustomVoice = union(enum) {
    voice_ids_shared: VoiceIdsShared,
    object: VoiceIdsOrCustomVoiceVariant1,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(VoiceIdsShared, allocator, source, options)) |value| {
            return .{ .voice_ids_shared = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(VoiceIdsOrCustomVoiceVariant1, allocator, source, options)) |value| {
            return .{ .object = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .voice_ids_shared => |value| try jw.write(value),
            .object => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ListModelsResponse = struct {
    object: []const u8,
    data: []const Model,
};

pub const CreateChatCompletionRequestToolsItem = union(enum) {
    chat_completion_tool: ChatCompletionTool,
    custom_tool_chat_completions: CustomToolChatCompletions,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(ChatCompletionTool, allocator, source, options)) |value| {
            return .{ .chat_completion_tool = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(CustomToolChatCompletions, allocator, source, options)) |value| {
            return .{ .custom_tool_chat_completions = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .chat_completion_tool => |value| try jw.write(value),
            .custom_tool_chat_completions => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const CreateChatCompletionRequestAudio = struct {
    format: []const u8,
    voice: VoiceIdsOrCustomVoice,
};

pub const CreateChatCompletionRequestResponseFormat = union(enum) {
    text: ResponseFormatText,
    json_schema: ResponseFormatJsonSchema,
    json_object: ResponseFormatJsonObject,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (source != .object) return error.UnexpectedToken;
        const discriminator = source.object.get("type") orelse return .{ .raw = source };
        if (discriminator != .string) return .{ .raw = source };
        if (std.mem.eql(u8, discriminator.string, "text")) {
            return .{ .text = try std.json.parseFromValueLeaky(ResponseFormatText, allocator, source, options) };
        }
        if (std.mem.eql(u8, discriminator.string, "json_schema")) {
            return .{ .json_schema = try std.json.parseFromValueLeaky(ResponseFormatJsonSchema, allocator, source, options) };
        }
        if (std.mem.eql(u8, discriminator.string, "json_object")) {
            return .{ .json_object = try std.json.parseFromValueLeaky(ResponseFormatJsonObject, allocator, source, options) };
        }

        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .text => |value| try jw.write(value),
            .json_schema => |value| try jw.write(value),
            .json_object => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const CreateChatCompletionRequestWebSearchOptionsUserLocation = struct {
    approximate: WebSearchLocation,
    type: []const u8,
};

pub const CreateChatCompletionRequestWebSearchOptions = struct {
    search_context_size: ?[]const u8 = null,
    user_location: ?CreateChatCompletionRequestWebSearchOptionsUserLocation = null,
};

pub const CreateChatCompletionRequestFunctionCallVariant0 = []const u8;

pub const CreateChatCompletionRequestFunctionCall = union(enum) {
    none,
    auto,
    chat_completion_function_call_option: ChatCompletionFunctionCallOption,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (source == .string and std.mem.eql(u8, source.string, "none")) return .none;
        if (source == .string and std.mem.eql(u8, source.string, "auto")) return .auto;
        if (std.json.parseFromValueLeaky(ChatCompletionFunctionCallOption, allocator, source, options)) |value| {
            return .{ .chat_completion_function_call_option = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .none => try jw.write("none"),
            .auto => try jw.write("auto"),
            .chat_completion_function_call_option => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const CreateChatCompletionRequest = struct {
    logprobs: ?bool = null,
    tools: ?[]const CreateChatCompletionRequestToolsItem = null,
    reasoning_effort: ?[]const u8 = null,
    store: ?bool = null,
    model: []const u8,
    stream: ?bool = null,
    stream_options: ?ChatCompletionStreamOptions = null,
    parallel_tool_calls: ?ParallelToolCalls = null,
    modalities: ?ResponseModalities = null,
    prediction: ?std.json.Value = null,
    audio: ?CreateChatCompletionRequestAudio = null,
    safety_identifier: ?[]const u8 = null,
    verbosity: ?[]const u8 = null,
    n: ?i64 = null,
    max_completion_tokens: ?i64 = null,
    metadata: ?Metadata = null,
    top_logprobs: ?i64 = null,
    stop: ?StopConfiguration = null,
    logit_bias: ?std.json.Value = null,
    response_format: ?CreateChatCompletionRequestResponseFormat = null,
    max_tokens: ?i64 = null,
    messages: []const ChatCompletionRequestMessage,
    seed: ?i64 = null,
    temperature: ?f64 = null,
    web_search_options: ?CreateChatCompletionRequestWebSearchOptions = null,
    function_call: ?CreateChatCompletionRequestFunctionCall = null,
    user: ?[]const u8 = null,
    functions: ?[]const ChatCompletionFunctions = null,
    prompt_cache_retention: ?[]const u8 = null,
    frequency_penalty: ?f64 = null,
    presence_penalty: ?f64 = null,
    tool_choice: ?ChatCompletionToolChoiceOption = null,
    top_p: ?f64 = null,
    service_tier: ?[]const u8 = null,
    prompt_cache_key: ?[]const u8 = null,
    extra_body: ?std.json.Value = null,

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        try jw.beginObject();
        if (self.logprobs) |value| {
            try jw.objectField("logprobs");
            try jw.write(value);
        }
        if (self.tools) |value| {
            try jw.objectField("tools");
            try jw.write(value);
        }
        if (self.reasoning_effort) |value| {
            try jw.objectField("reasoning_effort");
            try jw.write(value);
        }
        if (self.store) |value| {
            try jw.objectField("store");
            try jw.write(value);
        }
        try jw.objectField("model");
        try jw.write(self.model);
        if (self.stream) |value| {
            try jw.objectField("stream");
            try jw.write(value);
        }
        if (self.stream_options) |value| {
            try jw.objectField("stream_options");
            try jw.write(value);
        }
        if (self.parallel_tool_calls) |value| {
            try jw.objectField("parallel_tool_calls");
            try jw.write(value);
        }
        if (self.modalities) |value| {
            try jw.objectField("modalities");
            try jw.write(value);
        }
        if (self.prediction) |value| {
            try jw.objectField("prediction");
            try jw.write(value);
        }
        if (self.audio) |value| {
            try jw.objectField("audio");
            try jw.write(value);
        }
        if (self.safety_identifier) |value| {
            try jw.objectField("safety_identifier");
            try jw.write(value);
        }
        if (self.verbosity) |value| {
            try jw.objectField("verbosity");
            try jw.write(value);
        }
        if (self.n) |value| {
            try jw.objectField("n");
            try jw.write(value);
        }
        if (self.max_completion_tokens) |value| {
            try jw.objectField("max_completion_tokens");
            try jw.write(value);
        }
        if (self.metadata) |value| {
            try jw.objectField("metadata");
            try jw.write(value);
        }
        if (self.top_logprobs) |value| {
            try jw.objectField("top_logprobs");
            try jw.write(value);
        }
        if (self.stop) |value| {
            try jw.objectField("stop");
            try jw.write(value);
        }
        if (self.logit_bias) |value| {
            try jw.objectField("logit_bias");
            try jw.write(value);
        }
        if (self.response_format) |value| {
            try jw.objectField("response_format");
            try jw.write(value);
        }
        if (self.max_tokens) |value| {
            try jw.objectField("max_tokens");
            try jw.write(value);
        }
        try jw.objectField("messages");
        try jw.write(self.messages);
        if (self.seed) |value| {
            try jw.objectField("seed");
            try jw.write(value);
        }
        if (self.temperature) |value| {
            try jw.objectField("temperature");
            try jw.write(value);
        }
        if (self.web_search_options) |value| {
            try jw.objectField("web_search_options");
            try jw.write(value);
        }
        if (self.function_call) |value| {
            try jw.objectField("function_call");
            try jw.write(value);
        }
        if (self.user) |value| {
            try jw.objectField("user");
            try jw.write(value);
        }
        if (self.functions) |value| {
            try jw.objectField("functions");
            try jw.write(value);
        }
        if (self.prompt_cache_retention) |value| {
            try jw.objectField("prompt_cache_retention");
            try jw.write(value);
        }
        if (self.frequency_penalty) |value| {
            try jw.objectField("frequency_penalty");
            try jw.write(value);
        }
        if (self.presence_penalty) |value| {
            try jw.objectField("presence_penalty");
            try jw.write(value);
        }
        if (self.tool_choice) |value| {
            try jw.objectField("tool_choice");
            try jw.write(value);
        }
        if (self.top_p) |value| {
            try jw.objectField("top_p");
            try jw.write(value);
        }
        if (self.service_tier) |value| {
            try jw.objectField("service_tier");
            try jw.write(value);
        }
        if (self.prompt_cache_key) |value| {
            try jw.objectField("prompt_cache_key");
            try jw.write(value);
        }

        if (self.extra_body) |extra| {
            if (extra == .object) {
                var iterator = extra.object.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
            }
        }

        try jw.endObject();
    }
};

pub const ChatCompletionRequestAssistantMessageAudio = ?std.json.Value;

pub const ChatCompletionRequestAssistantMessageFunctionCall = ?std.json.Value;

pub const ChatCompletionRequestAssistantMessageContent = ?std.json.Value;

pub const ChatCompletionRequestAssistantMessage = struct {
    audio: ?ChatCompletionRequestAssistantMessageAudio = null,
    function_call: ?ChatCompletionRequestAssistantMessageFunctionCall = null,
    tool_calls: ?ChatCompletionMessageToolCalls = null,
    role: []const u8,
    name: ?[]const u8 = null,
    refusal: ?[]const u8 = null,
    content: ?ChatCompletionRequestAssistantMessageContent = null,
    reasoning_details: ?std.json.Value = null,
};

pub const ResponseFormatJsonSchemaJsonSchema = struct {
    description: ?[]const u8 = null,
    schema: ?ResponseFormatJsonSchemaSchema = null,
    name: []const u8,
    strict: ?bool = null,
};

pub const ResponseFormatJsonSchema = struct {
    json_schema: ResponseFormatJsonSchemaJsonSchema,
    type: []const u8,
};

pub const ChatCompletionRequestDeveloperMessageContentVariant0 = []const u8;

pub const ChatCompletionRequestDeveloperMessageContentVariant1 = []const ChatCompletionRequestMessageContentPartText;

pub const ChatCompletionRequestDeveloperMessageContent = union(enum) {
    text: []const u8,
    array_of_content_parts: []const ChatCompletionRequestMessageContentPartText,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky([]const u8, allocator, source, options)) |value| {
            return .{ .text = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky([]const ChatCompletionRequestMessageContentPartText, allocator, source, options)) |value| {
            return .{ .array_of_content_parts = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .text => |value| try jw.write(value),
            .array_of_content_parts => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ChatCompletionRequestDeveloperMessage = struct {
    role: []const u8,
    name: ?[]const u8 = null,
    content: ChatCompletionRequestDeveloperMessageContent,
};

pub const ModelIdsShared = []const u8;

pub const PredictionContentContentVariant0 = []const u8;

pub const PredictionContentContentVariant1 = []const ChatCompletionRequestMessageContentPartText;

pub const PredictionContentContent = union(enum) {
    text: []const u8,
    array_of_content_parts: []const ChatCompletionRequestMessageContentPartText,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky([]const u8, allocator, source, options)) |value| {
            return .{ .text = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky([]const ChatCompletionRequestMessageContentPartText, allocator, source, options)) |value| {
            return .{ .array_of_content_parts = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .text => |value| try jw.write(value),
            .array_of_content_parts => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const PredictionContent = struct {
    type: []const u8,
    content: PredictionContentContent,
};

pub const ChatCompletionResponseMessageFunctionCall = struct {
    arguments: []const u8,
    name: []const u8,
};

pub const ChatCompletionResponseMessageAudio = ?std.json.Value;

pub const ChatCompletionResponseMessageAnnotationsItemUrlCitation = struct {
    end_index: i64,
    start_index: i64,
    url: []const u8,
    title: []const u8,
};

pub const ChatCompletionResponseMessageAnnotationsItem = struct {
    url_citation: ChatCompletionResponseMessageAnnotationsItemUrlCitation,
    type: []const u8,
};

pub const ChatCompletionResponseMessage = struct {
    function_call: ?ChatCompletionResponseMessageFunctionCall = null,
    audio: ?ChatCompletionResponseMessageAudio = null,
    annotations: ?[]const ChatCompletionResponseMessageAnnotationsItem = null,
    tool_calls: ?ChatCompletionMessageToolCalls = null,
    role: []const u8,
    refusal: ?[]const u8,
    content: ?[]const u8,
};

pub const ChatCompletionTool = struct {
    type: []const u8,
    function: FunctionObject,
};

pub const ServiceTier = ?[]const u8;

pub const ChatCompletionRequestAssistantMessageContentPart = union(enum) {
    text: ChatCompletionRequestMessageContentPartText,
    refusal: ChatCompletionRequestMessageContentPartRefusal,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (source != .object) return error.UnexpectedToken;
        const discriminator = source.object.get("type") orelse return .{ .raw = source };
        if (discriminator != .string) return .{ .raw = source };
        if (std.mem.eql(u8, discriminator.string, "text")) {
            return .{ .text = try std.json.parseFromValueLeaky(ChatCompletionRequestMessageContentPartText, allocator, source, options) };
        }
        if (std.mem.eql(u8, discriminator.string, "refusal")) {
            return .{ .refusal = try std.json.parseFromValueLeaky(ChatCompletionRequestMessageContentPartRefusal, allocator, source, options) };
        }

        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .text => |value| try jw.write(value),
            .refusal => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const Model = struct {
    object: []const u8,
    owned_by: []const u8,
    id: []const u8,
    created: i64,
};

pub const ChatCompletionMessageToolCallsItem = union(enum) {
    function: ChatCompletionMessageToolCall,
    custom: ChatCompletionMessageCustomToolCall,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (source != .object) return error.UnexpectedToken;
        const discriminator = source.object.get("type") orelse return .{ .raw = source };
        if (discriminator != .string) return .{ .raw = source };
        if (std.mem.eql(u8, discriminator.string, "function")) {
            return .{ .function = try std.json.parseFromValueLeaky(ChatCompletionMessageToolCall, allocator, source, options) };
        }
        if (std.mem.eql(u8, discriminator.string, "custom")) {
            return .{ .custom = try std.json.parseFromValueLeaky(ChatCompletionMessageCustomToolCall, allocator, source, options) };
        }

        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .function => |value| try jw.write(value),
            .custom => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ChatCompletionMessageToolCalls = []const ChatCompletionMessageToolCallsItem;

pub const ChatCompletionRequestUserMessageContentVariant0 = []const u8;

pub const ChatCompletionRequestUserMessageContentVariant1 = []const ChatCompletionRequestUserMessageContentPart;

pub const ChatCompletionRequestUserMessageContent = union(enum) {
    text: []const u8,
    array_of_content_parts: []const ChatCompletionRequestUserMessageContentPart,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky([]const u8, allocator, source, options)) |value| {
            return .{ .text = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky([]const ChatCompletionRequestUserMessageContentPart, allocator, source, options)) |value| {
            return .{ .array_of_content_parts = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .text => |value| try jw.write(value),
            .array_of_content_parts => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ChatCompletionRequestUserMessage = struct {
    role: []const u8,
    name: ?[]const u8 = null,
    content: ChatCompletionRequestUserMessageContent,
};

pub const DeleteModelResponse = struct {
    object: []const u8,
    id: []const u8,
    deleted: bool,
};

pub const ChatCompletionStreamOptions = ?std.json.Value;

pub const ChatCompletionRequestMessageContentPartRefusal = struct {
    type: []const u8,
    refusal: []const u8,
};

pub const ChatCompletionTokenLogprobTopLogprobsItem = struct {
    logprob: f64,
    token: []const u8,
    bytes: ?[]const i64,
};

pub const ChatCompletionTokenLogprob = struct {
    logprob: f64,
    token: []const u8,
    bytes: ?[]const i64,
    top_logprobs: []const ChatCompletionTokenLogprobTopLogprobsItem,
};

pub const ChatCompletionNamedToolChoiceCustomCustom = struct {
    name: []const u8,
};

pub const ChatCompletionNamedToolChoiceCustom = struct {
    custom: ChatCompletionNamedToolChoiceCustomCustom,
    type: []const u8,
};

pub const CompletionUsageCompletionTokensDetails = struct {
    accepted_prediction_tokens: ?i64 = null,
    audio_tokens: ?i64 = null,
    reasoning_tokens: ?i64 = null,
    rejected_prediction_tokens: ?i64 = null,
};

pub const CompletionUsagePromptTokensDetails = struct {
    cached_tokens: ?i64 = null,
    audio_tokens: ?i64 = null,
};

pub const CompletionUsage = struct {
    prompt_tokens: i64,
    total_tokens: i64,
    completion_tokens: i64,
    completion_tokens_details: ?CompletionUsageCompletionTokensDetails = null,
    prompt_tokens_details: ?CompletionUsagePromptTokensDetails = null,
};

pub const ChatCompletionRequestSystemMessageContentVariant0 = []const u8;

pub const ChatCompletionRequestSystemMessageContentVariant1 = []const ChatCompletionRequestSystemMessageContentPart;

pub const ChatCompletionRequestSystemMessageContent = union(enum) {
    text: []const u8,
    array_of_content_parts: []const ChatCompletionRequestSystemMessageContentPart,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky([]const u8, allocator, source, options)) |value| {
            return .{ .text = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky([]const ChatCompletionRequestSystemMessageContentPart, allocator, source, options)) |value| {
            return .{ .array_of_content_parts = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .text => |value| try jw.write(value),
            .array_of_content_parts => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ChatCompletionRequestSystemMessage = struct {
    role: []const u8,
    name: ?[]const u8 = null,
    content: ChatCompletionRequestSystemMessageContent,
};

pub const CustomToolChatCompletionsCustomFormatVariant0 = struct {
    type: []const u8,
};

pub const CustomToolChatCompletionsCustomFormatVariant1Grammar = struct {
    syntax: []const u8,
    definition: []const u8,
};

pub const CustomToolChatCompletionsCustomFormatVariant1 = struct {
    type: []const u8,
    grammar: CustomToolChatCompletionsCustomFormatVariant1Grammar,
};

pub const CustomToolChatCompletionsCustomFormat = union(enum) {
    text: CustomToolChatCompletionsCustomFormatVariant0,
    grammar: CustomToolChatCompletionsCustomFormatVariant1,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(CustomToolChatCompletionsCustomFormatVariant0, allocator, source, options)) |value| {
            return .{ .text = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(CustomToolChatCompletionsCustomFormatVariant1, allocator, source, options)) |value| {
            return .{ .grammar = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .text => |value| try jw.write(value),
            .grammar => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const CustomToolChatCompletionsCustom = struct {
    description: ?[]const u8 = null,
    name: []const u8,
    format: ?CustomToolChatCompletionsCustomFormat = null,
};

pub const CustomToolChatCompletions = struct {
    custom: CustomToolChatCompletionsCustom,
    type: []const u8,
};

pub const ResponseModalities = ?[]const []const u8;

pub const FunctionParameters = union(enum) {
    null,
    bool: bool,
    integer: i64,
    float: f64,
    number_string: []const u8,
    string: []const u8,
    array: std.json.Array,
    object: std.json.ObjectMap,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .null => .null,
            .bool => |value| .{ .bool = value },
            .integer => |value| .{ .integer = value },
            .float => |value| .{ .float = value },
            .number_string => |value| .{ .number_string = value },
            .string => |value| .{ .string = value },
            .array => |value| .{ .array = value },
            .object => |value| .{ .object = value },
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .null => try jw.write(null),
            .bool => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .float => |value| try jw.write(value),
            .number_string => |value| try jw.print("{s}", .{value}),
            .string => |value| try jw.write(value),
            .array => |value| try jw.write(value.items),
            .object => |value| {
                try jw.beginObject();
                var iterator = value.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
                try jw.endObject();
            },
        }
    }
};

pub const ChatCompletionAllowedTools = struct {
    tools: []const std.json.Value,
    mode: []const u8,
};

pub const ChatCompletionFunctionCallOption = struct {
    name: []const u8,
};

pub const FunctionObject = struct {
    description: ?[]const u8 = null,
    strict: ?bool = null,
    name: []const u8,
    parameters: ?FunctionParameters = null,
};

pub const WebSearchLocation = struct {
    city: ?[]const u8 = null,
    country: ?[]const u8 = null,
    region: ?[]const u8 = null,
    timezone: ?[]const u8 = null,
};

pub const ResponseFormatJsonSchemaSchema = union(enum) {
    null,
    bool: bool,
    integer: i64,
    float: f64,
    number_string: []const u8,
    string: []const u8,
    array: std.json.Array,
    object: std.json.ObjectMap,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .null => .null,
            .bool => |value| .{ .bool = value },
            .integer => |value| .{ .integer = value },
            .float => |value| .{ .float = value },
            .number_string => |value| .{ .number_string = value },
            .string => |value| .{ .string = value },
            .array => |value| .{ .array = value },
            .object => |value| .{ .object = value },
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .null => try jw.write(null),
            .bool => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .float => |value| try jw.write(value),
            .number_string => |value| try jw.print("{s}", .{value}),
            .string => |value| try jw.write(value),
            .array => |value| try jw.write(value.items),
            .object => |value| {
                try jw.beginObject();
                var iterator = value.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
                try jw.endObject();
            },
        }
    }
};

pub const ChatCompletionRequestMessageContentPartImageImageUrl = struct {
    url: []const u8,
    detail: ?[]const u8 = null,
};

pub const ChatCompletionRequestMessageContentPartImage = struct {
    image_url: ChatCompletionRequestMessageContentPartImageImageUrl,
    type: []const u8,
};

pub const ChatCompletionDeleted = struct {
    object: []const u8,
    id: []const u8,
    deleted: bool,
};

pub const VoiceIdsShared = []const u8;

pub const ChatCompletionList = struct {
    object: []const u8,
    data: []const CreateChatCompletionResponse,
    last_id: []const u8,
    has_more: bool,
    first_id: []const u8,
};

pub const WebSearchContextSize = []const u8;

pub const ChatCompletionNamedToolChoiceFunction = struct {
    name: []const u8,
};

pub const ChatCompletionNamedToolChoice = struct {
    type: []const u8,
    function: ChatCompletionNamedToolChoiceFunction,
};

pub const OpenApi2ZigDynamicObject = std.json.ArrayHashMap(std.json.Value);

pub const EvalResponsesSourceMetadata = OpenApi2ZigDynamicObject;
pub const EvalRunOutputItemResultSample = OpenApi2ZigDynamicObject;
pub const AssignedRoleDetailsCreatedByUserObj = OpenApi2ZigDynamicObject;
pub const AssignedRoleDetailsMetadata = OpenApi2ZigDynamicObject;
pub const MCPListToolsToolAnnotations = OpenApi2ZigDynamicObject;

pub const MCPToolHeaders = std.json.ArrayHashMap([]const u8);

pub const ChatkitWorkflowStateVariable = union(enum) {
    string: []const u8,
    integer: i64,
    boolean: bool,
    number: f64,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .string => |value| .{ .string = value },
            .integer => |value| .{ .integer = value },
            .bool => |value| .{ .boolean = value },
            .float => |value| .{ .number = value },
            else => error.UnexpectedToken,
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .string => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .boolean => |value| try jw.write(value),
            .number => |value| try jw.write(value),
        }
    }
};

pub const ChatkitWorkflowStateVariables = std.json.ArrayHashMap(ChatkitWorkflowStateVariable);
