// <auto-generated>
//   This code was generated by openapi2zig 0.5.0 (240c22f) on 2026-08-29 22:18:33 UTC
//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
//   Checksum: 82f9fe6a43861b0d
// </auto-generated>

const std = @import("std");
const contracts = @import("contracts.zig");
const runtime = @import("../runtime.zig");
const Owned = runtime.Owned;
const HttpObserver = runtime.HttpObserver;
const RawResponse = runtime.RawResponse;
const ParseErrorResponse = runtime.ParseErrorResponse;
const ApiResult = runtime.ApiResult;
const CancellationToken = runtime.CancellationToken;
const checkCancellation = runtime.checkCancellation;
const CancelableReader = runtime.CancelableReader;
const parseSseReader = runtime.parseSseReader;
const parseSseBytes = runtime.parseSseBytes;
const parseSseBytesTyped = runtime.parseSseBytesTyped;
const parseSseReaderTyped = runtime.parseSseReaderTyped;
const TypedSseCallback = runtime.TypedSseCallback;

pub const Client = struct {
    allocator: std.mem.Allocator,
    io: std.Io,
    http: std.http.Client,
    api_key: []const u8,
    base_url: []const u8 = "",
    organization: ?[]const u8 = null,
    project: ?[]const u8 = null,
    default_headers: []const std.http.Header = &.{},
    http_observer: ?HttpObserver = null,

    /// Optional predicate polled while reading a streaming response body.
    /// When it returns true, a successfully started background watcher interrupts
    /// a blocked SSE socket read within about 10 ms and the stream exits with
    /// error.Cancelled. A CancelableReader also checks the predicate at every read
    /// boundary. If watcher startup fails, cancellation remains read-boundary only.
    /// Point it at an app-level cancel flag; it composes with a CancellationToken.
    /// When null (default), no watcher thread is spawned.
    cancel_check: ?*const fn () bool = null,

    pub fn init(allocator: std.mem.Allocator, io: std.Io, api_key: []const u8) Client {
        return .{
            .allocator = allocator,
            .io = io,
            .http = .{ .allocator = allocator, .io = io },
            .api_key = api_key,
            .http_observer = null,
        };
    }

    pub fn deinit(self: *Client) void {
        self.http.deinit();
    }

    pub fn withBaseUrl(self: *Client, base_url: []const u8) void {
        self.base_url = base_url;
    }
};

fn isQueryChar(c: u8) bool {
    return std.ascii.isAlphanumeric(c) or switch (c) {
        '-', '.', '_', '~' => true,
        else => false,
    };
}

fn writeQueryComponent(writer: *std.Io.Writer, value: []const u8) !void {
    try std.Uri.Component.percentEncode(writer, value, isQueryChar);
}

fn writeQueryValue(writer: *std.Io.Writer, value: anytype) !void {
    const T = @TypeOf(value);
    switch (@typeInfo(T)) {
        .pointer => |ptr| {
            if (ptr.size == .slice and ptr.child == u8) {
                try writeQueryComponent(writer, value);
            } else {
                try std.json.Stringify.value(value, .{}, writer);
            }
        },
        .int, .comptime_int, .float, .comptime_float, .bool => try writer.print("{}", .{value}),
        .@"enum" => try writeQueryComponent(writer, @tagName(value)),
        else => try std.json.Stringify.value(value, .{}, writer),
    }
}

fn appendQueryParam(writer: *std.Io.Writer, first_query: *bool, name: []const u8, value: anytype) !void {
    if (first_query.*) {
        try writer.writeByte('?');
        first_query.* = false;
    } else {
        try writer.writeByte('&');
    }
    try writeQueryComponent(writer, name);
    try writer.writeByte('=');
    try writeQueryValue(writer, value);
}

/// Serializes an `in: header` parameter value to an owned string. Reuses
/// the same primitive-type coverage as query parameters (string, integer,
/// float, boolean, enum). The caller frees the returned slice.
fn formatHeaderValue(allocator: std.mem.Allocator, value: anytype) ![]u8 {
    const T = @TypeOf(value);
    return switch (@typeInfo(T)) {
        .pointer => |ptr| blk: {
            if (ptr.size == .slice and ptr.child == u8) {
                break :blk try allocator.dupe(u8, value);
            }
            @compileError("OpenAPI header values must be strings, numbers, booleans, or enums");
        },
        .@"enum" => try allocator.dupe(u8, @tagName(value)),
        .int, .comptime_int, .float, .comptime_float, .bool => try std.fmt.allocPrint(allocator, "{}", .{value}),
        else => @compileError("OpenAPI header values must be strings, numbers, booleans, or enums"),
    };
}

/// Appends `value` under `name`, replacing (case-insensitively) any
/// existing header of the same name. Used so a declared operation header
/// parameter always wins over an equal-named client default header while
/// emitting exactly one header on the wire.
fn appendOrReplaceHeader(allocator: std.mem.Allocator, headers: *std.ArrayList(std.http.Header), name: []const u8, value: []const u8) !void {
    var i: usize = 0;
    while (i < headers.items.len) {
        if (std.ascii.eqlIgnoreCase(headers.items[i].name, name)) {
            _ = headers.orderedRemove(i);
        } else {
            i += 1;
        }
    }
    try headers.append(allocator, .{ .name = name, .value = value });
}

pub fn requestRaw(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8) !RawResponse {
    return requestRawWithContentType(client, method, url, payload, "application/json");
}

pub fn requestRawWithExtraHeaders(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8, extra_headers: []const std.http.Header) !RawResponse {
    return requestRawWithContentTypeAndExtraHeaders(client, method, url, payload, "application/json", extra_headers);
}

pub fn requestRawWithContentTypeAndExtraHeaders(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8, content_type_value: []const u8, extra_headers: []const std.http.Header) !RawResponse {
    const allocator = client.allocator;
    var headers = std.ArrayList(std.http.Header).empty;
    defer headers.deinit(allocator);
    const content_type: ?[]const u8 = if (payload != null) content_type_value else null;
    try appendClientHeaders(allocator, &headers, client, content_type, "application/json");
    for (extra_headers) |header| try appendOrReplaceHeader(allocator, &headers, header.name, header.value);

    if (client.http_observer) |obs| {
        if (obs.onRequest) |cb| cb(obs.ctx, method, url, headers.items, payload);
    }

    const uri = try std.Uri.parse(url);
    var response_body: std.Io.Writer.Allocating = .init(allocator);
    defer response_body.deinit();

    const start = std.Io.Clock.awake.now(client.io);
    const result = client.http.fetch(.{
        .location = .{ .uri = uri },
        .method = method,
        .extra_headers = headers.items,
        .payload = payload,
        .response_writer = &response_body.writer,
    }) catch |err| {
        if (client.http_observer) |obs| {
            if (obs.onError) |cb| cb(obs.ctx, method, url, @errorName(err));
        }
        return err;
    };
    const elapsed_ns = @as(u64, @intCast(start.untilNow(client.io, .awake).nanoseconds));

    const body = try response_body.toOwnedSlice();

    if (client.http_observer) |obs| {
        if (obs.onResponse) |cb| cb(obs.ctx, method, url, result.status, &.{}, body, elapsed_ns);
    }

    return .{
        .allocator = allocator,
        .status = result.status,
        .body = body,
    };
}

pub fn requestRawWithContentType(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8, content_type_value: []const u8) !RawResponse {
    const allocator = client.allocator;
    var headers = std.ArrayList(std.http.Header).empty;
    defer headers.deinit(allocator);
    const content_type: ?[]const u8 = if (payload != null) content_type_value else null;
    try appendClientHeaders(allocator, &headers, client, content_type, "application/json");

    if (client.http_observer) |obs| {
        if (obs.onRequest) |cb| cb(obs.ctx, method, url, headers.items, payload);
    }

    const uri = try std.Uri.parse(url);
    var response_body: std.Io.Writer.Allocating = .init(allocator);
    defer response_body.deinit();

    const start = std.Io.Clock.awake.now(client.io);
    const result = client.http.fetch(.{
        .location = .{ .uri = uri },
        .method = method,
        .extra_headers = headers.items,
        .payload = payload,
        .response_writer = &response_body.writer,
    }) catch |err| {
        if (client.http_observer) |obs| {
            if (obs.onError) |cb| cb(obs.ctx, method, url, @errorName(err));
        }
        return err;
    };
    const elapsed_ns = @as(u64, @intCast(start.untilNow(client.io, .awake).nanoseconds));

    const body = try response_body.toOwnedSlice();

    if (client.http_observer) |obs| {
        if (obs.onResponse) |cb| cb(obs.ctx, method, url, result.status, &.{}, body, elapsed_ns);
    }

    return .{
        .allocator = allocator,
        .status = result.status,
        .body = body,
    };
}

pub fn getRaw(client: *Client, path: []const u8) !RawResponse {
    const url = try std.fmt.allocPrint(client.allocator, "{s}{s}", .{ client.base_url, path });
    defer client.allocator.free(url);
    return requestRaw(client, .GET, url, null);
}

pub fn postJsonRaw(client: *Client, path: []const u8, payload: anytype) !RawResponse {
    const allocator = client.allocator;
    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(payload, .{ .emit_null_optional_fields = false }, &str.writer);

    const url = try std.fmt.allocPrint(allocator, "{s}{s}", .{ client.base_url, path });
    defer allocator.free(url);
    return requestRaw(client, .POST, url, str.written());
}

pub fn parseRawResponse(comptime T: type, raw: RawResponse) !ApiResult(T) {
    if (raw.status.class() != .success) return .{ .api_error = raw };
    const parsed = std.json.parseFromSlice(T, raw.allocator, raw.body, .{ .ignore_unknown_fields = true }) catch |err| {
        return .{ .parse_error = .{ .raw = raw, .error_name = @errorName(err) } };
    };
    return .{ .ok = .{ .allocator = raw.allocator, .body = raw.body, .parsed = parsed } };
}

pub fn getJsonResult(comptime T: type, client: *Client, path: []const u8) !ApiResult(T) {
    return parseRawResponse(T, try getRaw(client, path));
}

pub fn postJsonResult(comptime T: type, client: *Client, path: []const u8, payload: anytype) !ApiResult(T) {
    return parseRawResponse(T, try postJsonRaw(client, path, payload));
}
fn appendClientHeaders(allocator: std.mem.Allocator, headers: *std.ArrayList(std.http.Header), client: *Client, content_type: ?[]const u8, accept: []const u8) !void {
    if (content_type) |ct| {
        try headers.append(allocator, .{ .name = "Content-Type", .value = ct });
    }
    try headers.append(allocator, .{ .name = "Accept", .value = accept });
    if (client.organization) |organization| {
        try headers.append(allocator, .{ .name = "OpenAI-Organization", .value = organization });
    }
    if (client.project) |project| {
        try headers.append(allocator, .{ .name = "OpenAI-Project", .value = project });
    }
    for (client.default_headers) |header| {
        try headers.append(allocator, header);
    }
}

/////////////////
// Summary:
// List your models
//
// Description:
// Get a list of available models on your system, including both LLMs and embedding models.
//
pub fn listModels(client: *Client) !Owned(contracts.ListModelsResponse) {
    var result = try listModelsResult(client);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn listModelsRaw(client: *Client) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/api/v1/models", .{client.base_url});
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn listModelsResult(client: *Client) !ApiResult(contracts.ListModelsResponse) {
    return parseRawResponse(contracts.ListModelsResponse, try listModelsRaw(client));
}

/////////////////
// Summary:
// Download a model
//
// Description:
// Download LLMs and embedding models.
//
pub fn downloadModel(client: *Client, requestBody: contracts.DownloadModelRequest) !Owned(contracts.DownloadModelResponse) {
    var result = try downloadModelResult(client, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn downloadModelRaw(client: *Client, requestBody: contracts.DownloadModelRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/api/v1/models/download", .{client.base_url});

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn downloadModelResult(client: *Client, requestBody: contracts.DownloadModelRequest) !ApiResult(contracts.DownloadModelResponse) {
    return parseRawResponse(contracts.DownloadModelResponse, try downloadModelRaw(client, requestBody));
}

/////////////////
// Summary:
// Get download status
//
// Description:
// Get the status of model downloads.
//
pub fn getDownloadStatus(client: *Client, job_id: []const u8) !Owned(contracts.DownloadStatusResponse) {
    var result = try getDownloadStatusResult(client, job_id);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn getDownloadStatusRaw(client: *Client, job_id: []const u8) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/api/v1/models/download/status/{s}", .{ client.base_url, job_id });
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn getDownloadStatusResult(client: *Client, job_id: []const u8) !ApiResult(contracts.DownloadStatusResponse) {
    return parseRawResponse(contracts.DownloadStatusResponse, try getDownloadStatusRaw(client, job_id));
}

/////////////////
// Summary:
// Unload a model
//
// Description:
// Unload a loaded model from memory.
//
pub fn unloadModel(client: *Client, requestBody: contracts.UnloadModelRequest) !Owned(contracts.UnloadModelResponse) {
    var result = try unloadModelResult(client, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn unloadModelRaw(client: *Client, requestBody: contracts.UnloadModelRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/api/v1/models/unload", .{client.base_url});

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn unloadModelResult(client: *Client, requestBody: contracts.UnloadModelRequest) !ApiResult(contracts.UnloadModelResponse) {
    return parseRawResponse(contracts.UnloadModelResponse, try unloadModelRaw(client, requestBody));
}

/////////////////
// Summary:
// Load a model
//
// Description:
// Load an LLM or Embedding model into memory with custom configuration for inference.
//
pub fn loadModel(client: *Client, requestBody: contracts.LoadModelRequest) !Owned(contracts.LoadModelResponse) {
    var result = try loadModelResult(client, requestBody);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn loadModelRaw(client: *Client, requestBody: contracts.LoadModelRequest) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/api/v1/models/load", .{client.base_url});

    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(requestBody, .{ .emit_null_optional_fields = false }, &str.writer);
    const payload: ?[]const u8 = str.written();

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.POST, uri_buf.written(), payload, operation_headers.items);
}

pub fn loadModelResult(client: *Client, requestBody: contracts.LoadModelRequest) !ApiResult(contracts.LoadModelResponse) {
    return parseRawResponse(contracts.LoadModelResponse, try loadModelRaw(client, requestBody));
}

pub const resources = struct {
    pub const api = struct {
        pub const models = struct {
            pub fn list(client: *Client) !Owned(contracts.ListModelsResponse) {
                return listModels(client);
            }
            pub fn listResult(client: *Client) !ApiResult(contracts.ListModelsResponse) {
                return listModelsResult(client);
            }
            pub const download = struct {
                pub fn downloadmodel(client: *Client, requestBody: contracts.DownloadModelRequest) !Owned(contracts.DownloadModelResponse) {
                    return downloadModel(client, requestBody);
                }
                pub fn downloadmodelResult(client: *Client, requestBody: contracts.DownloadModelRequest) !ApiResult(contracts.DownloadModelResponse) {
                    return downloadModelResult(client, requestBody);
                }
                pub const status = struct {
                    pub fn get(client: *Client, job_id: []const u8) !Owned(contracts.DownloadStatusResponse) {
                        return getDownloadStatus(client, job_id);
                    }
                    pub fn getResult(client: *Client, job_id: []const u8) !ApiResult(contracts.DownloadStatusResponse) {
                        return getDownloadStatusResult(client, job_id);
                    }
                };
            };
            pub const load = struct {
                pub fn loadmodel(client: *Client, requestBody: contracts.LoadModelRequest) !Owned(contracts.LoadModelResponse) {
                    return loadModel(client, requestBody);
                }
                pub fn loadmodelResult(client: *Client, requestBody: contracts.LoadModelRequest) !ApiResult(contracts.LoadModelResponse) {
                    return loadModelResult(client, requestBody);
                }
            };
            pub const unload = struct {
                pub fn unloadmodel(client: *Client, requestBody: contracts.UnloadModelRequest) !Owned(contracts.UnloadModelResponse) {
                    return unloadModel(client, requestBody);
                }
                pub fn unloadmodelResult(client: *Client, requestBody: contracts.UnloadModelRequest) !ApiResult(contracts.UnloadModelResponse) {
                    return unloadModelResult(client, requestBody);
                }
            };
        };
    };
};

pub const api = resources.api;
