// <auto-generated>
//   This code was generated by openapi2zig 0.5.0 (240c22f) on 2026-08-29 22:57:19 UTC
//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
//   Checksum: b2963e0ed396a274
// </auto-generated>

const std = @import("std");

pub const LlmLoadConfig = struct {
    context_length: i64,
    flash_attention: ?bool = null,
    eval_batch_size: ?i64 = null,
    num_experts: ?i64 = null,
    offload_kv_cache_to_gpu: ?bool = null,
};

pub const UnloadModelRequest = struct {
    instance_id: []const u8,
};

pub const ListModelsResponse = struct {
    models: []const ModelInfo,
};

pub const DownloadModelResponse = struct {
    status: []const u8,
    job_id: ?[]const u8 = null,
    completed_at: ?[]const u8 = null,
    total_size_bytes: ?i64 = null,
    started_at: ?[]const u8 = null,
};

pub const LoadedInstance = struct {
    id: []const u8,
    config: LoadedInstanceConfig,
};

pub const LoadModelRequest = struct {
    context_length: ?i64 = null,
    flash_attention: ?bool = null,
    eval_batch_size: ?i64 = null,
    num_experts: ?i64 = null,
    offload_kv_cache_to_gpu: ?bool = null,
    model: []const u8,
    echo_load_config: ?bool = null,
};

pub const ModelInfoCapabilitiesReasoning = struct {
    allowed_options: []const []const u8,
    default: []const u8,
};

pub const ModelInfoCapabilities = struct {
    trained_for_tool_use: ?bool = null,
    reasoning: ?ModelInfoCapabilitiesReasoning = null,
    vision: ?bool = null,
};

pub const ModelInfoQuantization = struct {
    name: ?[]const u8 = null,
    bits_per_weight: ?f64 = null,
};

pub const ModelInfo = struct {
    params_string: ?[]const u8 = null,
    publisher: []const u8,
    key: []const u8,
    format: ?[]const u8 = null,
    variants: ?[]const []const u8 = null,
    selected_variant: ?[]const u8 = null,
    display_name: []const u8,
    size_bytes: i64,
    architecture: ?[]const u8 = null,
    max_context_length: i64,
    capabilities: ?ModelInfoCapabilities = null,
    loaded_instances: []const LoadedInstance,
    quantization: ?ModelInfoQuantization = null,
    description: ?[]const u8 = null,
    type: []const u8,
};

pub const EmbeddingLoadConfig = struct {
    context_length: i64,
};

pub const DownloadStatusResponse = struct {
    completed_at: ?[]const u8 = null,
    bytes_per_second: ?i64 = null,
    estimated_completion: ?[]const u8 = null,
    total_size_bytes: ?i64 = null,
    started_at: ?[]const u8 = null,
    status: []const u8,
    job_id: []const u8,
    downloaded_bytes: ?i64 = null,
};

pub const DownloadModelRequest = struct {
    quantization: ?[]const u8 = null,
    model: []const u8,
};

pub const LoadedInstanceConfig = struct {
    context_length: i64,
    num_experts: ?i64 = null,
    flash_attention: ?bool = null,
    eval_batch_size: ?i64 = null,
    parallel: ?i64 = null,
    offload_kv_cache_to_gpu: ?bool = null,
};

pub const UnloadModelResponse = struct {
    instance_id: []const u8,
};

pub const LoadModelResponseLoadConfig = union(enum) {
    llm_load_config: LlmLoadConfig,
    embedding_load_config: EmbeddingLoadConfig,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(LlmLoadConfig, allocator, source, options)) |value| {
            return .{ .llm_load_config = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(EmbeddingLoadConfig, allocator, source, options)) |value| {
            return .{ .embedding_load_config = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .llm_load_config => |value| try jw.write(value),
            .embedding_load_config => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const LoadModelResponse = struct {
    load_time_seconds: f64,
    status: []const u8,
    instance_id: []const u8,
    load_config: ?LoadModelResponseLoadConfig = null,
    type: []const u8,
};
