// <auto-generated>
//   This code was generated by openapi2zig 0.5.0 (b7e76d4) on 2026-08-20 21:26:58 UTC
//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
//   Checksum: 1f0cea2f8ca1edb9
// </auto-generated>

const std = @import("std");

pub const LlmLoadConfig = struct {
    context_length: i64,
    flash_attention: ?bool = null,
    eval_batch_size: ?i64 = null,
    num_experts: ?i64 = null,
    offload_kv_cache_to_gpu: ?bool = null,
};

pub const UnloadModelRequest = struct {
    instance_id: []const u8,
};

pub const ReasoningOutput = struct {
    type: []const u8,
    content: []const u8,
};

pub const ListModelsResponse = struct {
    models: []const ModelInfo,
};

pub const DownloadModelResponse = struct {
    status: []const u8,
    job_id: ?[]const u8 = null,
    completed_at: ?[]const u8 = null,
    total_size_bytes: ?i64 = null,
    started_at: ?[]const u8 = null,
};

pub const ChatOutputItem = union(enum) {
    message: MessageOutput,
    tool_call: ToolCallOutput,
    reasoning: ReasoningOutput,
    invalid_tool_call: InvalidToolCallOutput,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (source != .object) return error.UnexpectedToken;
        const discriminator = source.object.get("type") orelse return .{ .raw = source };
        if (discriminator != .string) return .{ .raw = source };
        if (std.mem.eql(u8, discriminator.string, "message")) {
            return .{ .message = try std.json.parseFromValueLeaky(MessageOutput, allocator, source, options) };
        }
        if (std.mem.eql(u8, discriminator.string, "tool_call")) {
            return .{ .tool_call = try std.json.parseFromValueLeaky(ToolCallOutput, allocator, source, options) };
        }
        if (std.mem.eql(u8, discriminator.string, "reasoning")) {
            return .{ .reasoning = try std.json.parseFromValueLeaky(ReasoningOutput, allocator, source, options) };
        }
        if (std.mem.eql(u8, discriminator.string, "invalid_tool_call")) {
            return .{ .invalid_tool_call = try std.json.parseFromValueLeaky(InvalidToolCallOutput, allocator, source, options) };
        }

        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .message => |value| try jw.write(value),
            .tool_call => |value| try jw.write(value),
            .reasoning => |value| try jw.write(value),
            .invalid_tool_call => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const LoadedInstance = struct {
    id: []const u8,
    config: LoadedInstanceConfig,
};

pub const TextInput = struct {
    type: []const u8,
    content: []const u8,
};

pub const LoadModelRequest = struct {
    context_length: ?i64 = null,
    flash_attention: ?bool = null,
    eval_batch_size: ?i64 = null,
    num_experts: ?i64 = null,
    offload_kv_cache_to_gpu: ?bool = null,
    model: []const u8,
    echo_load_config: ?bool = null,
};

pub const ModelInfoCapabilitiesReasoning = struct {
    allowed_options: []const []const u8,
    default: []const u8,
};

pub const ModelInfoCapabilities = struct {
    trained_for_tool_use: ?bool = null,
    reasoning: ?ModelInfoCapabilitiesReasoning = null,
    vision: ?bool = null,
};

pub const ModelInfoQuantization = struct {
    name: []const u8,
    bits_per_weight: f64,
};

pub const ModelInfo = struct {
    params_string: ?[]const u8 = null,
    publisher: []const u8,
    key: []const u8,
    format: []const u8,
    variants: ?[]const []const u8 = null,
    selected_variant: ?[]const u8 = null,
    display_name: []const u8,
    size_bytes: i64,
    architecture: ?[]const u8 = null,
    max_context_length: i64,
    capabilities: ?ModelInfoCapabilities = null,
    loaded_instances: []const LoadedInstance,
    quantization: ?ModelInfoQuantization = null,
    description: ?[]const u8 = null,
    type: []const u8,
};

pub const EmbeddingLoadConfig = struct {
    context_length: i64,
};

pub const DownloadStatusResponse = struct {
    completed_at: ?[]const u8 = null,
    bytes_per_second: ?i64 = null,
    estimated_completion: ?[]const u8 = null,
    total_size_bytes: ?i64 = null,
    started_at: ?[]const u8 = null,
    status: []const u8,
    job_id: []const u8,
    downloaded_bytes: ?i64 = null,
};

pub const PluginIntegration = struct {
    allowed_tools: ?[]const []const u8 = null,
    id: []const u8,
    type: []const u8,
};

pub const ChatStats = struct {
    input_tokens: i64,
    reasoning_output_tokens: i64,
    tokens_per_second: f64,
    time_to_first_token_seconds: f64,
    total_output_tokens: i64,
    model_load_time_seconds: ?f64 = null,
};

pub const ChatResponse = struct {
    stats: ChatStats,
    response_id: ?[]const u8 = null,
    model_instance_id: []const u8,
    output: []const ChatOutputItem,
};

pub const DownloadModelRequest = struct {
    quantization: ?[]const u8 = null,
    model: []const u8,
};

pub const ChatRequestIntegrationsItemVariant0 = []const u8;

pub const ChatRequestIntegrationsItem = union(enum) {
    string: []const u8,
    plugin_integration: PluginIntegration,
    ephemeral_mcp_integration: EphemeralMcpIntegration,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky([]const u8, allocator, source, options)) |value| {
            return .{ .string = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(PluginIntegration, allocator, source, options)) |value| {
            return .{ .plugin_integration = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(EphemeralMcpIntegration, allocator, source, options)) |value| {
            return .{ .ephemeral_mcp_integration = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .string => |value| try jw.write(value),
            .plugin_integration => |value| try jw.write(value),
            .ephemeral_mcp_integration => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ChatRequestInputVariant0 = []const u8;

pub const ChatRequestInputVariant1 = []const ChatInputItem;

pub const ChatRequestInput = union(enum) {
    string: []const u8,
    chat_input_item_items: []const ChatInputItem,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky([]const u8, allocator, source, options)) |value| {
            return .{ .string = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky([]const ChatInputItem, allocator, source, options)) |value| {
            return .{ .chat_input_item_items = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .string => |value| try jw.write(value),
            .chat_input_item_items => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ChatRequest = struct {
    integrations: ?[]const ChatRequestIntegrationsItem = null,
    reasoning: ?[]const u8 = null,
    temperature: ?f64 = null,
    max_output_tokens: ?i64 = null,
    store: ?bool = null,
    model: []const u8,
    stream: ?bool = null,
    context_length: ?i64 = null,
    repeat_penalty: ?f64 = null,
    top_p: ?f64 = null,
    top_k: ?i64 = null,
    min_p: ?f64 = null,
    previous_response_id: ?[]const u8 = null,
    input: ChatRequestInput,
    system_prompt: ?[]const u8 = null,
};

pub const MessageOutput = struct {
    type: []const u8,
    content: []const u8,
};

pub const LoadedInstanceConfig = struct {
    context_length: i64,
    num_experts: ?i64 = null,
    flash_attention: ?bool = null,
    eval_batch_size: ?i64 = null,
    parallel: ?i64 = null,
    offload_kv_cache_to_gpu: ?bool = null,
};

pub const ImageInput = struct {
    data_url: []const u8,
    type: []const u8,
};

pub const UnloadModelResponse = struct {
    instance_id: []const u8,
};

pub const InvalidToolCallOutputMetadata = struct {
    arguments: ?std.json.Value = null,
    tool_name: []const u8,
    type: []const u8,
    provider_info: ?ProviderInfo = null,
};

pub const InvalidToolCallOutput = struct {
    metadata: InvalidToolCallOutputMetadata,
    reason: []const u8,
    type: []const u8,
};

pub const LoadModelResponseLoadConfig = union(enum) {
    llm_load_config: LlmLoadConfig,
    embedding_load_config: EmbeddingLoadConfig,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(LlmLoadConfig, allocator, source, options)) |value| {
            return .{ .llm_load_config = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(EmbeddingLoadConfig, allocator, source, options)) |value| {
            return .{ .embedding_load_config = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .llm_load_config => |value| try jw.write(value),
            .embedding_load_config => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const LoadModelResponse = struct {
    load_time_seconds: f64,
    status: []const u8,
    instance_id: []const u8,
    load_config: ?LoadModelResponseLoadConfig = null,
    type: []const u8,
};

pub const ProviderInfo = struct {
    type: []const u8,
    plugin_id: ?[]const u8 = null,
    server_label: ?[]const u8 = null,
};

pub const ChatInputItem = union(enum) {
    message: TextInput,
    image: ImageInput,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (source != .object) return error.UnexpectedToken;
        const discriminator = source.object.get("type") orelse return .{ .raw = source };
        if (discriminator != .string) return .{ .raw = source };
        if (std.mem.eql(u8, discriminator.string, "message")) {
            return .{ .message = try std.json.parseFromValueLeaky(TextInput, allocator, source, options) };
        }
        if (std.mem.eql(u8, discriminator.string, "image")) {
            return .{ .image = try std.json.parseFromValueLeaky(ImageInput, allocator, source, options) };
        }

        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .message => |value| try jw.write(value),
            .image => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const EphemeralMcpIntegration = struct {
    server_url: []const u8,
    allowed_tools: ?[]const []const u8 = null,
    type: []const u8,
    headers: ?std.json.Value = null,
    server_label: []const u8,
};

pub const ToolCallOutput = struct {
    arguments: std.json.Value,
    tool: []const u8,
    output: []const u8,
    type: []const u8,
    provider_info: ProviderInfo,
};
