// <auto-generated>
//   This code was generated by openapi2zig 0.5.0 (240c22f) on 2026-08-29 22:57:19 UTC
//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
//   Checksum: c9bbc5b1bdb59883
// </auto-generated>

const std = @import("std");

pub const ResponsePageLocationCitation = struct {
    end_page_number: i64,
    file_id: ?[]const u8,
    start_page_number: i64,
    document_index: i64,
    cited_text: []const u8,
    type: []const u8,
    document_title: ?[]const u8,
};

pub const ResponseBashCodeExecutionResultBlock = struct {
    content: []const ResponseBashCodeExecutionOutputBlock,
    return_code: i64,
    type: []const u8,
    stderr: []const u8,
    stdout: []const u8,
};

pub const URLPDFSource = struct {
    url: []const u8,
    type: []const u8,
};

pub const RequestToolReferenceBlock = struct {
    tool_name: []const u8,
    type: []const u8,
    cache_control: ?std.json.Value = null,
};

pub const InputContentBlock = union(enum) {
    request_text_block: RequestTextBlock,
    request_image_block: RequestImageBlock,
    request_document_block: RequestDocumentBlock,
    request_search_result_block: RequestSearchResultBlock,
    request_thinking_block: RequestThinkingBlock,
    request_redacted_thinking_block: RequestRedactedThinkingBlock,
    request_tool_use_block: RequestToolUseBlock,
    request_tool_result_block: RequestToolResultBlock,
    request_server_tool_use_block: RequestServerToolUseBlock,
    request_web_search_tool_result_block: RequestWebSearchToolResultBlock,
    request_web_fetch_tool_result_block: RequestWebFetchToolResultBlock,
    request_code_execution_tool_result_block: RequestCodeExecutionToolResultBlock,
    request_bash_code_execution_tool_result_block: RequestBashCodeExecutionToolResultBlock,
    request_text_editor_code_execution_tool_result_block: RequestTextEditorCodeExecutionToolResultBlock,
    request_tool_search_tool_result_block: RequestToolSearchToolResultBlock,
    request_container_upload_block: RequestContainerUploadBlock,
    request_mid_conv_system_block: RequestMidConvSystemBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(RequestTextBlock, allocator, source, options)) |value| {
            return .{ .request_text_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestImageBlock, allocator, source, options)) |value| {
            return .{ .request_image_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestDocumentBlock, allocator, source, options)) |value| {
            return .{ .request_document_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestSearchResultBlock, allocator, source, options)) |value| {
            return .{ .request_search_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestThinkingBlock, allocator, source, options)) |value| {
            return .{ .request_thinking_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestRedactedThinkingBlock, allocator, source, options)) |value| {
            return .{ .request_redacted_thinking_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestToolUseBlock, allocator, source, options)) |value| {
            return .{ .request_tool_use_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestToolResultBlock, allocator, source, options)) |value| {
            return .{ .request_tool_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestServerToolUseBlock, allocator, source, options)) |value| {
            return .{ .request_server_tool_use_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestWebSearchToolResultBlock, allocator, source, options)) |value| {
            return .{ .request_web_search_tool_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestWebFetchToolResultBlock, allocator, source, options)) |value| {
            return .{ .request_web_fetch_tool_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestCodeExecutionToolResultBlock, allocator, source, options)) |value| {
            return .{ .request_code_execution_tool_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestBashCodeExecutionToolResultBlock, allocator, source, options)) |value| {
            return .{ .request_bash_code_execution_tool_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestTextEditorCodeExecutionToolResultBlock, allocator, source, options)) |value| {
            return .{ .request_text_editor_code_execution_tool_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestToolSearchToolResultBlock, allocator, source, options)) |value| {
            return .{ .request_tool_search_tool_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestContainerUploadBlock, allocator, source, options)) |value| {
            return .{ .request_container_upload_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestMidConvSystemBlock, allocator, source, options)) |value| {
            return .{ .request_mid_conv_system_block = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .request_text_block => |value| try jw.write(value),
            .request_image_block => |value| try jw.write(value),
            .request_document_block => |value| try jw.write(value),
            .request_search_result_block => |value| try jw.write(value),
            .request_thinking_block => |value| try jw.write(value),
            .request_redacted_thinking_block => |value| try jw.write(value),
            .request_tool_use_block => |value| try jw.write(value),
            .request_tool_result_block => |value| try jw.write(value),
            .request_server_tool_use_block => |value| try jw.write(value),
            .request_web_search_tool_result_block => |value| try jw.write(value),
            .request_web_fetch_tool_result_block => |value| try jw.write(value),
            .request_code_execution_tool_result_block => |value| try jw.write(value),
            .request_bash_code_execution_tool_result_block => |value| try jw.write(value),
            .request_text_editor_code_execution_tool_result_block => |value| try jw.write(value),
            .request_tool_search_tool_result_block => |value| try jw.write(value),
            .request_container_upload_block => |value| try jw.write(value),
            .request_mid_conv_system_block => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ResponseToolUseBlock = struct {
    caller: std.json.Value,
    id: []const u8,
    input: std.json.Value,
    name: []const u8,
    type: []const u8,
};

pub const MemoryTool_20250818 = struct {
    input_examples: ?[]const std.json.Value = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    allowed_callers: ?[]const AllowedCaller = null,
    cache_control: ?std.json.Value = null,
    name: []const u8,
    type: []const u8,
};

pub const RequestCodeExecutionResultBlock = struct {
    content: []const RequestCodeExecutionOutputBlock,
    return_code: i64,
    type: []const u8,
    stderr: []const u8,
    stdout: []const u8,
};

pub const InputMessageContentVariant0 = []const u8;

pub const InputMessageContentVariant1 = []const InputContentBlock;

pub const InputMessageContent = union(enum) {
    string: []const u8,
    input_content_block_items: []const InputContentBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky([]const u8, allocator, source, options)) |value| {
            return .{ .string = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky([]const InputContentBlock, allocator, source, options)) |value| {
            return .{ .input_content_block_items = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .string => |value| try jw.write(value),
            .input_content_block_items => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const InputMessage = struct {
    role: []const u8,
    content: InputMessageContent,
};

pub const ResponseCodeExecutionToolResultBlockContent = union(enum) {
    response_code_execution_tool_result_error: ResponseCodeExecutionToolResultError,
    response_code_execution_result_block: ResponseCodeExecutionResultBlock,
    response_encrypted_code_execution_result_block: ResponseEncryptedCodeExecutionResultBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(ResponseCodeExecutionToolResultError, allocator, source, options)) |value| {
            return .{ .response_code_execution_tool_result_error = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseCodeExecutionResultBlock, allocator, source, options)) |value| {
            return .{ .response_code_execution_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseEncryptedCodeExecutionResultBlock, allocator, source, options)) |value| {
            return .{ .response_encrypted_code_execution_result_block = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .response_code_execution_tool_result_error => |value| try jw.write(value),
            .response_code_execution_result_block => |value| try jw.write(value),
            .response_encrypted_code_execution_result_block => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ResponseCodeExecutionToolResultBlock = struct {
    tool_use_id: []const u8,
    type: []const u8,
    content: ResponseCodeExecutionToolResultBlockContent,
};

pub const WebFetchTool_20260318 = struct {
    response_inclusion: ?[]const u8 = null,
    allowed_callers: ?[]const AllowedCaller = null,
    cache_control: ?std.json.Value = null,
    max_content_tokens: ?i64 = null,
    allowed_domains: ?[]const []const u8 = null,
    use_cache: ?bool = null,
    max_uses: ?i64 = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    blocked_domains: ?[]const []const u8 = null,
    citations: ?RequestCitationsConfig = null,
    name: []const u8,
    type: []const u8,
};

pub const ToolChoiceNone = struct {
    type: []const u8,
};

pub const ToolSearchToolResultErrorCode = []const u8;

pub const RequestToolSearchToolResultError = struct {
    error_code: []const u8,
    error_message: ?[]const u8 = null,
    type: []const u8,
};

pub const Base64ImageSource = struct {
    data: []const u8,
    media_type: []const u8,
    type: []const u8,
};

pub const RequestWebSearchToolResultBlockContentVariant0 = []const RequestWebSearchResultBlock;

pub const RequestWebSearchToolResultBlockContent = union(enum) {
    web_search_tool_result_block_item: []const RequestWebSearchResultBlock,
    request_web_search_tool_result_error: RequestWebSearchToolResultError,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky([]const RequestWebSearchResultBlock, allocator, source, options)) |value| {
            return .{ .web_search_tool_result_block_item = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestWebSearchToolResultError, allocator, source, options)) |value| {
            return .{ .request_web_search_tool_result_error = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .web_search_tool_result_block_item => |value| try jw.write(value),
            .request_web_search_tool_result_error => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const RequestWebSearchToolResultBlock = struct {
    cache_control: ?std.json.Value = null,
    tool_use_id: []const u8,
    caller: ?std.json.Value = null,
    type: []const u8,
    content: RequestWebSearchToolResultBlockContent,
};

pub const CacheCreation = struct {
    ephemeral_1h_input_tokens: i64,
    ephemeral_5m_input_tokens: i64,
};

pub const JsonOutputFormat = struct {
    schema: std.json.Value,
    type: []const u8,
};

pub const RequestPageLocationCitation = struct {
    end_page_number: i64,
    document_index: i64,
    start_page_number: i64,
    cited_text: []const u8,
    type: []const u8,
    document_title: ?[]const u8,
};

pub const ThinkingConfigAdaptive = struct {
    display: ?[]const u8 = null,
    type: []const u8,
};

pub const AllowedCaller = []const u8;

pub const WebFetchTool_20260209 = struct {
    max_uses: ?i64 = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    allowed_callers: ?[]const AllowedCaller = null,
    cache_control: ?std.json.Value = null,
    max_content_tokens: ?i64 = null,
    blocked_domains: ?[]const []const u8 = null,
    citations: ?RequestCitationsConfig = null,
    allowed_domains: ?[]const []const u8 = null,
    name: []const u8,
    type: []const u8,
};

pub const ToolChoiceTool = struct {
    disable_parallel_tool_use: ?bool = null,
    name: []const u8,
    type: []const u8,
};

pub const ResponseSearchResultLocationCitation = struct {
    end_block_index: i64,
    search_result_index: i64,
    source: []const u8,
    start_block_index: i64,
    cited_text: []const u8,
    title: ?[]const u8,
    type: []const u8,
};

pub const ContentBlock = union(enum) {
    response_text_block: ResponseTextBlock,
    response_thinking_block: ResponseThinkingBlock,
    response_redacted_thinking_block: ResponseRedactedThinkingBlock,
    response_tool_use_block: ResponseToolUseBlock,
    response_server_tool_use_block: ResponseServerToolUseBlock,
    response_web_search_tool_result_block: ResponseWebSearchToolResultBlock,
    response_web_fetch_tool_result_block: ResponseWebFetchToolResultBlock,
    response_code_execution_tool_result_block: ResponseCodeExecutionToolResultBlock,
    response_bash_code_execution_tool_result_block: ResponseBashCodeExecutionToolResultBlock,
    response_text_editor_code_execution_tool_result_block: ResponseTextEditorCodeExecutionToolResultBlock,
    response_tool_search_tool_result_block: ResponseToolSearchToolResultBlock,
    response_container_upload_block: ResponseContainerUploadBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(ResponseTextBlock, allocator, source, options)) |value| {
            return .{ .response_text_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseThinkingBlock, allocator, source, options)) |value| {
            return .{ .response_thinking_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseRedactedThinkingBlock, allocator, source, options)) |value| {
            return .{ .response_redacted_thinking_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseToolUseBlock, allocator, source, options)) |value| {
            return .{ .response_tool_use_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseServerToolUseBlock, allocator, source, options)) |value| {
            return .{ .response_server_tool_use_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseWebSearchToolResultBlock, allocator, source, options)) |value| {
            return .{ .response_web_search_tool_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseWebFetchToolResultBlock, allocator, source, options)) |value| {
            return .{ .response_web_fetch_tool_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseCodeExecutionToolResultBlock, allocator, source, options)) |value| {
            return .{ .response_code_execution_tool_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseBashCodeExecutionToolResultBlock, allocator, source, options)) |value| {
            return .{ .response_bash_code_execution_tool_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseTextEditorCodeExecutionToolResultBlock, allocator, source, options)) |value| {
            return .{ .response_text_editor_code_execution_tool_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseToolSearchToolResultBlock, allocator, source, options)) |value| {
            return .{ .response_tool_search_tool_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseContainerUploadBlock, allocator, source, options)) |value| {
            return .{ .response_container_upload_block = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .response_text_block => |value| try jw.write(value),
            .response_thinking_block => |value| try jw.write(value),
            .response_redacted_thinking_block => |value| try jw.write(value),
            .response_tool_use_block => |value| try jw.write(value),
            .response_server_tool_use_block => |value| try jw.write(value),
            .response_web_search_tool_result_block => |value| try jw.write(value),
            .response_web_fetch_tool_result_block => |value| try jw.write(value),
            .response_code_execution_tool_result_block => |value| try jw.write(value),
            .response_bash_code_execution_tool_result_block => |value| try jw.write(value),
            .response_text_editor_code_execution_tool_result_block => |value| try jw.write(value),
            .response_tool_search_tool_result_block => |value| try jw.write(value),
            .response_container_upload_block => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const RequestTextBlock = struct {
    text: []const u8,
    citations: ?[]const std.json.Value = null,
    type: []const u8,
    cache_control: ?std.json.Value = null,
};

pub const RequestTextEditorCodeExecutionToolResultBlockContent = union(enum) {
    request_text_editor_code_execution_tool_result_error: RequestTextEditorCodeExecutionToolResultError,
    request_text_editor_code_execution_view_result_block: RequestTextEditorCodeExecutionViewResultBlock,
    request_text_editor_code_execution_create_result_block: RequestTextEditorCodeExecutionCreateResultBlock,
    request_text_editor_code_execution_str_replace_result_block: RequestTextEditorCodeExecutionStrReplaceResultBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(RequestTextEditorCodeExecutionToolResultError, allocator, source, options)) |value| {
            return .{ .request_text_editor_code_execution_tool_result_error = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestTextEditorCodeExecutionViewResultBlock, allocator, source, options)) |value| {
            return .{ .request_text_editor_code_execution_view_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestTextEditorCodeExecutionCreateResultBlock, allocator, source, options)) |value| {
            return .{ .request_text_editor_code_execution_create_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestTextEditorCodeExecutionStrReplaceResultBlock, allocator, source, options)) |value| {
            return .{ .request_text_editor_code_execution_str_replace_result_block = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .request_text_editor_code_execution_tool_result_error => |value| try jw.write(value),
            .request_text_editor_code_execution_view_result_block => |value| try jw.write(value),
            .request_text_editor_code_execution_create_result_block => |value| try jw.write(value),
            .request_text_editor_code_execution_str_replace_result_block => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const RequestTextEditorCodeExecutionToolResultBlock = struct {
    cache_control: ?std.json.Value = null,
    tool_use_id: []const u8,
    type: []const u8,
    content: RequestTextEditorCodeExecutionToolResultBlockContent,
};

pub const RequestImageBlock = struct {
    source: std.json.Value,
    type: []const u8,
    cache_control: ?std.json.Value = null,
};

pub const WebFetchTool_20260309 = struct {
    max_uses: ?i64 = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    allowed_callers: ?[]const AllowedCaller = null,
    cache_control: ?std.json.Value = null,
    max_content_tokens: ?i64 = null,
    blocked_domains: ?[]const []const u8 = null,
    citations: ?RequestCitationsConfig = null,
    allowed_domains: ?[]const []const u8 = null,
    name: []const u8,
    type: []const u8,
    use_cache: ?bool = null,
};

pub const CacheControlEphemeral = struct {
    ttl: ?[]const u8 = null,
    type: []const u8,
};

pub const BillingError = struct {
    message: []const u8,
    type: []const u8,
};

pub const ResponseWebFetchResultBlock = struct {
    retrieved_at: ?[]const u8,
    url: []const u8,
    type: []const u8,
    content: ResponseDocumentBlock,
};

pub const EffortLevel = []const u8;

pub const CodeExecutionTool_20250522 = struct {
    cache_control: ?std.json.Value = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    type: []const u8,
    allowed_callers: ?[]const AllowedCaller = null,
    name: []const u8,
};

pub const RequestSearchResultLocationCitation = struct {
    end_block_index: i64,
    search_result_index: i64,
    source: []const u8,
    start_block_index: i64,
    cited_text: []const u8,
    title: ?[]const u8,
    type: []const u8,
};

pub const ServerToolCaller = struct {
    type: []const u8,
    tool_id: []const u8,
};

pub const RequestThinkingBlock = struct {
    thinking: []const u8,
    signature: []const u8,
    type: []const u8,
};

pub const ResponseToolReferenceBlock = struct {
    tool_name: []const u8,
    type: []const u8,
};

pub const InputSchema = struct {
    properties: ?std.json.Value = null,
    required: ?[]const []const u8 = null,
    type: []const u8,
};

pub const ResponseToolSearchToolResultBlockContent = union(enum) {
    response_tool_search_tool_result_error: ResponseToolSearchToolResultError,
    response_tool_search_tool_search_result_block: ResponseToolSearchToolSearchResultBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(ResponseToolSearchToolResultError, allocator, source, options)) |value| {
            return .{ .response_tool_search_tool_result_error = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseToolSearchToolSearchResultBlock, allocator, source, options)) |value| {
            return .{ .response_tool_search_tool_search_result_block = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .response_tool_search_tool_result_error => |value| try jw.write(value),
            .response_tool_search_tool_search_result_block => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ResponseToolSearchToolResultBlock = struct {
    tool_use_id: []const u8,
    type: []const u8,
    content: ResponseToolSearchToolResultBlockContent,
};

pub const ServerToolUsage = struct {
    web_search_requests: i64,
    web_fetch_requests: i64,
};

pub const RequestBashCodeExecutionResultBlock = struct {
    content: []const RequestBashCodeExecutionOutputBlock,
    return_code: i64,
    type: []const u8,
    stderr: []const u8,
    stdout: []const u8,
};

pub const BashCodeExecutionToolResultErrorCode = []const u8;

pub const InvalidRequestError = struct {
    message: []const u8,
    type: []const u8,
};

pub const ResponseCodeExecutionToolResultError = struct {
    error_code: []const u8,
    type: []const u8,
};

pub const OutputConfig = struct {
    effort: ?[]const u8 = null,
    format: ?JsonOutputFormat = null,
};

pub const ResponseTextBlock = struct {
    text: []const u8,
    citations: ?[]const std.json.Value,
    type: []const u8,
};

pub const RequestCitationsConfig = struct {
    enabled: ?bool = null,
};

pub const CreateMessageParamsToolsItem = union(enum) {
    tool: Tool,
    bash_tool_20250124: BashTool_20250124,
    code_execution_tool_20250522: CodeExecutionTool_20250522,
    code_execution_tool_20250825: CodeExecutionTool_20250825,
    code_execution_tool_20260120: CodeExecutionTool_20260120,
    code_execution_tool_20260521: CodeExecutionTool_20260521,
    memory_tool_20250818: MemoryTool_20250818,
    text_editor_20250124: TextEditor_20250124,
    text_editor_20250429: TextEditor_20250429,
    text_editor_20250728: TextEditor_20250728,
    web_search_tool_20250305: WebSearchTool_20250305,
    web_fetch_tool_20250910: WebFetchTool_20250910,
    web_search_tool_20260209: WebSearchTool_20260209,
    web_fetch_tool_20260209: WebFetchTool_20260209,
    web_fetch_tool_20260309: WebFetchTool_20260309,
    web_search_tool_20260318: WebSearchTool_20260318,
    web_fetch_tool_20260318: WebFetchTool_20260318,
    tool_search_tool_bm25_20251119: ToolSearchToolBM25_20251119,
    tool_search_tool_regex_20251119: ToolSearchToolRegex_20251119,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(Tool, allocator, source, options)) |value| {
            return .{ .tool = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(BashTool_20250124, allocator, source, options)) |value| {
            return .{ .bash_tool_20250124 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(CodeExecutionTool_20250522, allocator, source, options)) |value| {
            return .{ .code_execution_tool_20250522 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(CodeExecutionTool_20250825, allocator, source, options)) |value| {
            return .{ .code_execution_tool_20250825 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(CodeExecutionTool_20260120, allocator, source, options)) |value| {
            return .{ .code_execution_tool_20260120 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(CodeExecutionTool_20260521, allocator, source, options)) |value| {
            return .{ .code_execution_tool_20260521 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(MemoryTool_20250818, allocator, source, options)) |value| {
            return .{ .memory_tool_20250818 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(TextEditor_20250124, allocator, source, options)) |value| {
            return .{ .text_editor_20250124 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(TextEditor_20250429, allocator, source, options)) |value| {
            return .{ .text_editor_20250429 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(TextEditor_20250728, allocator, source, options)) |value| {
            return .{ .text_editor_20250728 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(WebSearchTool_20250305, allocator, source, options)) |value| {
            return .{ .web_search_tool_20250305 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(WebFetchTool_20250910, allocator, source, options)) |value| {
            return .{ .web_fetch_tool_20250910 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(WebSearchTool_20260209, allocator, source, options)) |value| {
            return .{ .web_search_tool_20260209 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(WebFetchTool_20260209, allocator, source, options)) |value| {
            return .{ .web_fetch_tool_20260209 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(WebFetchTool_20260309, allocator, source, options)) |value| {
            return .{ .web_fetch_tool_20260309 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(WebSearchTool_20260318, allocator, source, options)) |value| {
            return .{ .web_search_tool_20260318 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(WebFetchTool_20260318, allocator, source, options)) |value| {
            return .{ .web_fetch_tool_20260318 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ToolSearchToolBM25_20251119, allocator, source, options)) |value| {
            return .{ .tool_search_tool_bm25_20251119 = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ToolSearchToolRegex_20251119, allocator, source, options)) |value| {
            return .{ .tool_search_tool_regex_20251119 = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .tool => |value| try jw.write(value),
            .bash_tool_20250124 => |value| try jw.write(value),
            .code_execution_tool_20250522 => |value| try jw.write(value),
            .code_execution_tool_20250825 => |value| try jw.write(value),
            .code_execution_tool_20260120 => |value| try jw.write(value),
            .code_execution_tool_20260521 => |value| try jw.write(value),
            .memory_tool_20250818 => |value| try jw.write(value),
            .text_editor_20250124 => |value| try jw.write(value),
            .text_editor_20250429 => |value| try jw.write(value),
            .text_editor_20250728 => |value| try jw.write(value),
            .web_search_tool_20250305 => |value| try jw.write(value),
            .web_fetch_tool_20250910 => |value| try jw.write(value),
            .web_search_tool_20260209 => |value| try jw.write(value),
            .web_fetch_tool_20260209 => |value| try jw.write(value),
            .web_fetch_tool_20260309 => |value| try jw.write(value),
            .web_search_tool_20260318 => |value| try jw.write(value),
            .web_fetch_tool_20260318 => |value| try jw.write(value),
            .tool_search_tool_bm25_20251119 => |value| try jw.write(value),
            .tool_search_tool_regex_20251119 => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const CreateMessageParamsSystemVariant0 = []const u8;

pub const CreateMessageParamsSystemVariant1 = []const RequestTextBlock;

pub const CreateMessageParamsSystem = union(enum) {
    string: []const u8,
    request_text_block_items: []const RequestTextBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky([]const u8, allocator, source, options)) |value| {
            return .{ .string = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky([]const RequestTextBlock, allocator, source, options)) |value| {
            return .{ .request_text_block_items = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .string => |value| try jw.write(value),
            .request_text_block_items => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const CreateMessageParams = struct {
    thinking: ?ThinkingConfigParam = null,
    max_tokens: i64,
    tools: ?[]const CreateMessageParamsToolsItem = null,
    messages: []const InputMessage,
    cache_control: ?std.json.Value = null,
    temperature: ?f64 = null,
    system: ?CreateMessageParamsSystem = null,
    stream: ?bool = null,
    model: []const u8,
    output_config: ?OutputConfig = null,
    container: ?[]const u8 = null,
    tool_choice: ?ToolChoice = null,
    top_p: ?f64 = null,
    top_k: ?i64 = null,
    inference_geo: ?[]const u8 = null,
    metadata: ?Metadata = null,
    service_tier: ?[]const u8 = null,
    stop_sequences: ?[]const []const u8 = null,
};

pub const Tool = struct {
    input_examples: ?[]const std.json.Value = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    allowed_callers: ?[]const AllowedCaller = null,
    cache_control: ?std.json.Value = null,
    description: ?[]const u8 = null,
    input_schema: InputSchema,
    name: []const u8,
    type: ?[]const u8 = null,
    eager_input_streaming: ?bool = null,
};

pub const BashTool_20250124 = struct {
    input_examples: ?[]const std.json.Value = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    allowed_callers: ?[]const AllowedCaller = null,
    cache_control: ?std.json.Value = null,
    name: []const u8,
    type: []const u8,
};

pub const ThinkingDisplayMode = []const u8;

pub const WebFetchTool_20250910 = struct {
    max_uses: ?i64 = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    allowed_callers: ?[]const AllowedCaller = null,
    cache_control: ?std.json.Value = null,
    max_content_tokens: ?i64 = null,
    blocked_domains: ?[]const []const u8 = null,
    citations: ?RequestCitationsConfig = null,
    allowed_domains: ?[]const []const u8 = null,
    name: []const u8,
    type: []const u8,
};

pub const ResponseBashCodeExecutionToolResultError = struct {
    error_code: []const u8,
    type: []const u8,
};

pub const Metadata = struct {
    user_id: ?[]const u8 = null,
};

pub const ResponseTextEditorCodeExecutionToolResultError = struct {
    error_code: []const u8,
    error_message: ?[]const u8,
    type: []const u8,
};

pub const ThinkingConfigEnabled = struct {
    display: ?[]const u8 = null,
    budget_tokens: i64,
    type: []const u8,
};

pub const ResponseCharLocationCitation = struct {
    document_title: ?[]const u8,
    file_id: ?[]const u8,
    document_index: i64,
    end_char_index: i64,
    cited_text: []const u8,
    type: []const u8,
    start_char_index: i64,
};

pub const ResponseWebSearchResultBlock = struct {
    page_age: ?[]const u8,
    encrypted_content: []const u8,
    url: []const u8,
    type: []const u8,
    title: []const u8,
};

pub const WebSearchTool_20250305 = struct {
    max_uses: ?i64 = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    allowed_callers: ?[]const AllowedCaller = null,
    cache_control: ?std.json.Value = null,
    blocked_domains: ?[]const []const u8 = null,
    user_location: ?UserLocation = null,
    allowed_domains: ?[]const []const u8 = null,
    name: []const u8,
    type: []const u8,
};

pub const RequestMidConvSystemBlock = struct {
    cache_control: ?std.json.Value = null,
    type: []const u8,
    content: []const std.json.Value,
};

pub const WebSearchTool_20260209 = struct {
    max_uses: ?i64 = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    allowed_callers: ?[]const AllowedCaller = null,
    cache_control: ?std.json.Value = null,
    blocked_domains: ?[]const []const u8 = null,
    user_location: ?UserLocation = null,
    allowed_domains: ?[]const []const u8 = null,
    name: []const u8,
    type: []const u8,
};

pub const Base64PDFSource = struct {
    data: []const u8,
    media_type: []const u8,
    type: []const u8,
};

pub const TextEditor_20250124 = struct {
    input_examples: ?[]const std.json.Value = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    allowed_callers: ?[]const AllowedCaller = null,
    cache_control: ?std.json.Value = null,
    name: []const u8,
    type: []const u8,
};

pub const ResponseServerToolUseBlock = struct {
    caller: std.json.Value,
    id: []const u8,
    input: std.json.Value,
    name: []const u8,
    type: []const u8,
};

pub const StopReason = []const u8;

pub const ResponseTextEditorCodeExecutionToolResultBlockContent = union(enum) {
    response_text_editor_code_execution_tool_result_error: ResponseTextEditorCodeExecutionToolResultError,
    response_text_editor_code_execution_view_result_block: ResponseTextEditorCodeExecutionViewResultBlock,
    response_text_editor_code_execution_create_result_block: ResponseTextEditorCodeExecutionCreateResultBlock,
    response_text_editor_code_execution_str_replace_result_block: ResponseTextEditorCodeExecutionStrReplaceResultBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(ResponseTextEditorCodeExecutionToolResultError, allocator, source, options)) |value| {
            return .{ .response_text_editor_code_execution_tool_result_error = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseTextEditorCodeExecutionViewResultBlock, allocator, source, options)) |value| {
            return .{ .response_text_editor_code_execution_view_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseTextEditorCodeExecutionCreateResultBlock, allocator, source, options)) |value| {
            return .{ .response_text_editor_code_execution_create_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseTextEditorCodeExecutionStrReplaceResultBlock, allocator, source, options)) |value| {
            return .{ .response_text_editor_code_execution_str_replace_result_block = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .response_text_editor_code_execution_tool_result_error => |value| try jw.write(value),
            .response_text_editor_code_execution_view_result_block => |value| try jw.write(value),
            .response_text_editor_code_execution_create_result_block => |value| try jw.write(value),
            .response_text_editor_code_execution_str_replace_result_block => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ResponseTextEditorCodeExecutionToolResultBlock = struct {
    tool_use_id: []const u8,
    type: []const u8,
    content: ResponseTextEditorCodeExecutionToolResultBlockContent,
};

pub const RequestBashCodeExecutionOutputBlock = struct {
    file_id: []const u8,
    type: []const u8,
};

pub const WebSearchTool_20260318 = struct {
    max_uses: ?i64 = null,
    response_inclusion: ?[]const u8 = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    allowed_callers: ?[]const AllowedCaller = null,
    cache_control: ?std.json.Value = null,
    blocked_domains: ?[]const []const u8 = null,
    user_location: ?UserLocation = null,
    allowed_domains: ?[]const []const u8 = null,
    name: []const u8,
    type: []const u8,
};

pub const PlainTextSource = struct {
    data: []const u8,
    media_type: []const u8,
    type: []const u8,
};

pub const RequestCodeExecutionOutputBlock = struct {
    file_id: []const u8,
    type: []const u8,
};

pub const NotFoundError = struct {
    message: []const u8,
    type: []const u8,
};

pub const RefusalStopDetails = struct {
    category: ?[]const u8,
    explanation: ?[]const u8,
    type: []const u8,
};

pub const TextEditor_20250728 = struct {
    input_examples: ?[]const std.json.Value = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    allowed_callers: ?[]const AllowedCaller = null,
    cache_control: ?std.json.Value = null,
    max_characters: ?i64 = null,
    name: []const u8,
    type: []const u8,
};

pub const ResponseTextEditorCodeExecutionCreateResultBlock = struct {
    is_file_update: bool,
    type: []const u8,
};

pub const WebFetchToolResultErrorCode = []const u8;

pub const OverloadedError = struct {
    message: []const u8,
    type: []const u8,
};

pub const ServerToolCaller_20260120 = struct {
    type: []const u8,
    tool_id: []const u8,
};

pub const RequestToolSearchToolSearchResultBlock = struct {
    tool_references: []const RequestToolReferenceBlock,
    type: []const u8,
};

pub const ResponseCitationsConfig = struct {
    enabled: bool,
};

pub const ResponseThinkingBlock = struct {
    thinking: []const u8,
    signature: []const u8,
    type: []const u8,
};

pub const ToolChoiceAny = struct {
    disable_parallel_tool_use: ?bool = null,
    type: []const u8,
};

pub const APIError = struct {
    message: []const u8,
    type: []const u8,
};

pub const ResponseWebFetchToolResultBlockContent = union(enum) {
    response_web_fetch_tool_result_error: ResponseWebFetchToolResultError,
    response_web_fetch_result_block: ResponseWebFetchResultBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(ResponseWebFetchToolResultError, allocator, source, options)) |value| {
            return .{ .response_web_fetch_tool_result_error = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseWebFetchResultBlock, allocator, source, options)) |value| {
            return .{ .response_web_fetch_result_block = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .response_web_fetch_tool_result_error => |value| try jw.write(value),
            .response_web_fetch_result_block => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ResponseWebFetchToolResultBlock = struct {
    tool_use_id: []const u8,
    caller: std.json.Value,
    type: []const u8,
    content: ResponseWebFetchToolResultBlockContent,
};

pub const RequestCharLocationCitation = struct {
    end_char_index: i64,
    start_char_index: i64,
    document_index: i64,
    cited_text: []const u8,
    type: []const u8,
    document_title: ?[]const u8,
};

pub const RequestWebSearchResultLocationCitation = struct {
    url: []const u8,
    encrypted_index: []const u8,
    cited_text: []const u8,
    title: ?[]const u8,
    type: []const u8,
};

pub const ResponseContainerUploadBlock = struct {
    file_id: []const u8,
    type: []const u8,
};

pub const RateLimitError = struct {
    message: []const u8,
    type: []const u8,
};

pub const DirectCaller = struct {
    type: []const u8,
};

pub const RequestWebFetchToolResultError = struct {
    error_code: []const u8,
    type: []const u8,
};

pub const ThinkingConfigDisabled = struct {
    type: []const u8,
};

pub const Model = union(enum) {
    null,
    bool: bool,
    integer: i64,
    float: f64,
    number_string: []const u8,
    string: []const u8,
    array: std.json.Array,
    object: std.json.ObjectMap,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .null => .null,
            .bool => |value| .{ .bool = value },
            .integer => |value| .{ .integer = value },
            .float => |value| .{ .float = value },
            .number_string => |value| .{ .number_string = value },
            .string => |value| .{ .string = value },
            .array => |value| .{ .array = value },
            .object => |value| .{ .object = value },
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .null => try jw.write(null),
            .bool => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .float => |value| try jw.write(value),
            .number_string => |value| try jw.print("{s}", .{value}),
            .string => |value| try jw.write(value),
            .array => |value| try jw.write(value.items),
            .object => |value| {
                try jw.beginObject();
                var iterator = value.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
                try jw.endObject();
            },
        }
    }
};

pub const ContentBlockSourceContentVariant0 = []const u8;

pub const ContentBlockSourceContentVariant1 = []const std.json.Value;

pub const ContentBlockSourceContent = union(enum) {
    string: []const u8,
    content_block_source_content: []const std.json.Value,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky([]const u8, allocator, source, options)) |value| {
            return .{ .string = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky([]const std.json.Value, allocator, source, options)) |value| {
            return .{ .content_block_source_content = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .string => |value| try jw.write(value),
            .content_block_source_content => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ContentBlockSource = struct {
    type: []const u8,
    content: ContentBlockSourceContent,
};

pub const ToolSearchToolRegex_20251119 = struct {
    cache_control: ?std.json.Value = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    type: []const u8,
    allowed_callers: ?[]const AllowedCaller = null,
    name: []const u8,
};

pub const ErrorResponse = struct {
    @"error": std.json.Value,
    request_id: ?[]const u8,
    type: []const u8,
};

pub const RequestToolUseBlock = struct {
    cache_control: ?std.json.Value = null,
    caller: ?std.json.Value = null,
    id: []const u8,
    type: []const u8,
    input: std.json.Value,
    name: []const u8,
};

pub const RequestWebSearchResultBlock = struct {
    page_age: ?[]const u8 = null,
    encrypted_content: []const u8,
    url: []const u8,
    type: []const u8,
    title: []const u8,
};

pub const TextEditor_20250429 = struct {
    input_examples: ?[]const std.json.Value = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    allowed_callers: ?[]const AllowedCaller = null,
    cache_control: ?std.json.Value = null,
    name: []const u8,
    type: []const u8,
};

pub const ToolSearchToolBM25_20251119 = struct {
    cache_control: ?std.json.Value = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    type: []const u8,
    allowed_callers: ?[]const AllowedCaller = null,
    name: []const u8,
};

pub const ToolChoice = union(enum) {
    tool_choice_auto: ToolChoiceAuto,
    tool_choice_any: ToolChoiceAny,
    tool_choice_tool: ToolChoiceTool,
    tool_choice_none: ToolChoiceNone,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(ToolChoiceAuto, allocator, source, options)) |value| {
            return .{ .tool_choice_auto = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ToolChoiceAny, allocator, source, options)) |value| {
            return .{ .tool_choice_any = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ToolChoiceTool, allocator, source, options)) |value| {
            return .{ .tool_choice_tool = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ToolChoiceNone, allocator, source, options)) |value| {
            return .{ .tool_choice_none = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .tool_choice_auto => |value| try jw.write(value),
            .tool_choice_any => |value| try jw.write(value),
            .tool_choice_tool => |value| try jw.write(value),
            .tool_choice_none => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ResponseWebSearchToolResultError = struct {
    error_code: []const u8,
    type: []const u8,
};

pub const Usage = struct {
    cache_read_input_tokens: ?i64,
    input_tokens: i64,
    output_tokens_details: ?OutputTokensDetails,
    server_tool_use: ?ServerToolUsage,
    inference_geo: ?[]const u8,
    output_tokens: i64,
    service_tier: ?[]const u8,
    cache_creation_input_tokens: ?i64,
    cache_creation: ?CacheCreation,
};

pub const ResponseWebFetchToolResultError = struct {
    error_code: []const u8,
    type: []const u8,
};

pub const RequestTextEditorCodeExecutionViewResultBlock = struct {
    total_lines: ?i64 = null,
    file_type: []const u8,
    num_lines: ?i64 = null,
    start_line: ?i64 = null,
    type: []const u8,
    content: []const u8,
};

pub const ToolChoiceAuto = struct {
    disable_parallel_tool_use: ?bool = null,
    type: []const u8,
};

pub const RequestTextEditorCodeExecutionToolResultError = struct {
    error_code: []const u8,
    error_message: ?[]const u8 = null,
    type: []const u8,
};

pub const RequestToolSearchToolResultBlockContent = union(enum) {
    request_tool_search_tool_result_error: RequestToolSearchToolResultError,
    request_tool_search_tool_search_result_block: RequestToolSearchToolSearchResultBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(RequestToolSearchToolResultError, allocator, source, options)) |value| {
            return .{ .request_tool_search_tool_result_error = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestToolSearchToolSearchResultBlock, allocator, source, options)) |value| {
            return .{ .request_tool_search_tool_search_result_block = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .request_tool_search_tool_result_error => |value| try jw.write(value),
            .request_tool_search_tool_search_result_block => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const RequestToolSearchToolResultBlock = struct {
    cache_control: ?std.json.Value = null,
    tool_use_id: []const u8,
    type: []const u8,
    content: RequestToolSearchToolResultBlockContent,
};

pub const RequestDocumentBlock = struct {
    source: std.json.Value,
    context: ?[]const u8 = null,
    citations: ?RequestCitationsConfig = null,
    type: []const u8,
    title: ?[]const u8 = null,
    cache_control: ?std.json.Value = null,
};

pub const Container = struct {
    expires_at: []const u8,
    id: []const u8,
};

pub const RequestWebFetchResultBlock = struct {
    retrieved_at: ?[]const u8 = null,
    url: []const u8,
    type: []const u8,
    content: RequestDocumentBlock,
};

pub const ResponseRedactedThinkingBlock = struct {
    data: []const u8,
    type: []const u8,
};

pub const RequestContainerUploadBlock = struct {
    file_id: []const u8,
    type: []const u8,
    cache_control: ?std.json.Value = null,
};

pub const ResponseCodeExecutionResultBlock = struct {
    content: []const ResponseCodeExecutionOutputBlock,
    return_code: i64,
    type: []const u8,
    stderr: []const u8,
    stdout: []const u8,
};

pub const ResponseEncryptedCodeExecutionResultBlock = struct {
    encrypted_stdout: []const u8,
    return_code: i64,
    stderr: []const u8,
    type: []const u8,
    content: []const ResponseCodeExecutionOutputBlock,
};

pub const ResponseBashCodeExecutionToolResultBlockContent = union(enum) {
    response_bash_code_execution_tool_result_error: ResponseBashCodeExecutionToolResultError,
    response_bash_code_execution_result_block: ResponseBashCodeExecutionResultBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(ResponseBashCodeExecutionToolResultError, allocator, source, options)) |value| {
            return .{ .response_bash_code_execution_tool_result_error = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ResponseBashCodeExecutionResultBlock, allocator, source, options)) |value| {
            return .{ .response_bash_code_execution_result_block = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .response_bash_code_execution_tool_result_error => |value| try jw.write(value),
            .response_bash_code_execution_result_block => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ResponseBashCodeExecutionToolResultBlock = struct {
    tool_use_id: []const u8,
    type: []const u8,
    content: ResponseBashCodeExecutionToolResultBlockContent,
};

pub const RequestServerToolUseBlock = struct {
    cache_control: ?std.json.Value = null,
    caller: ?std.json.Value = null,
    id: []const u8,
    type: []const u8,
    input: std.json.Value,
    name: []const u8,
};

pub const RequestRedactedThinkingBlock = struct {
    data: []const u8,
    type: []const u8,
};

pub const CodeExecutionToolResultErrorCode = []const u8;

pub const RequestEncryptedCodeExecutionResultBlock = struct {
    encrypted_stdout: []const u8,
    return_code: i64,
    stderr: []const u8,
    type: []const u8,
    content: []const RequestCodeExecutionOutputBlock,
};

pub const RequestBashCodeExecutionToolResultError = struct {
    error_code: []const u8,
    type: []const u8,
};

pub const RequestBashCodeExecutionToolResultBlockContent = union(enum) {
    request_bash_code_execution_tool_result_error: RequestBashCodeExecutionToolResultError,
    request_bash_code_execution_result_block: RequestBashCodeExecutionResultBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(RequestBashCodeExecutionToolResultError, allocator, source, options)) |value| {
            return .{ .request_bash_code_execution_tool_result_error = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestBashCodeExecutionResultBlock, allocator, source, options)) |value| {
            return .{ .request_bash_code_execution_result_block = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .request_bash_code_execution_tool_result_error => |value| try jw.write(value),
            .request_bash_code_execution_result_block => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const RequestBashCodeExecutionToolResultBlock = struct {
    cache_control: ?std.json.Value = null,
    tool_use_id: []const u8,
    type: []const u8,
    content: RequestBashCodeExecutionToolResultBlockContent,
};

pub const RequestSearchResultBlock = struct {
    source: []const u8,
    cache_control: ?std.json.Value = null,
    citations: ?RequestCitationsConfig = null,
    type: []const u8,
    title: []const u8,
    content: []const RequestTextBlock,
};

pub const AuthenticationError = struct {
    message: []const u8,
    type: []const u8,
};

pub const RequestWebFetchToolResultBlockContent = union(enum) {
    request_web_fetch_tool_result_error: RequestWebFetchToolResultError,
    request_web_fetch_result_block: RequestWebFetchResultBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(RequestWebFetchToolResultError, allocator, source, options)) |value| {
            return .{ .request_web_fetch_tool_result_error = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestWebFetchResultBlock, allocator, source, options)) |value| {
            return .{ .request_web_fetch_result_block = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .request_web_fetch_tool_result_error => |value| try jw.write(value),
            .request_web_fetch_result_block => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const RequestWebFetchToolResultBlock = struct {
    cache_control: ?std.json.Value = null,
    tool_use_id: []const u8,
    caller: ?std.json.Value = null,
    type: []const u8,
    content: RequestWebFetchToolResultBlockContent,
};

pub const PermissionError = struct {
    message: []const u8,
    type: []const u8,
};

pub const ResponseBashCodeExecutionOutputBlock = struct {
    file_id: []const u8,
    type: []const u8,
};

pub const RequestTextEditorCodeExecutionCreateResultBlock = struct {
    is_file_update: bool,
    type: []const u8,
};

pub const ResponseTextEditorCodeExecutionStrReplaceResultBlock = struct {
    old_lines: ?i64,
    new_lines: ?i64,
    old_start: ?i64,
    type: []const u8,
    lines: ?[]const []const u8,
    new_start: ?i64,
};

pub const ResponseToolSearchToolResultError = struct {
    error_code: []const u8,
    error_message: ?[]const u8,
    type: []const u8,
};

pub const WebSearchToolResultErrorCode = []const u8;

pub const ResponseContentBlockLocationCitation = struct {
    end_block_index: i64,
    file_id: ?[]const u8,
    document_index: i64,
    start_block_index: i64,
    cited_text: []const u8,
    type: []const u8,
    document_title: ?[]const u8,
};

pub const TextEditorCodeExecutionToolResultErrorCode = []const u8;

pub const RequestToolResultBlockContentVariant0 = []const u8;

pub const RequestToolResultBlockContentVariant1 = []const std.json.Value;

pub const RequestToolResultBlockContent = union(enum) {
    string: []const u8,
    items_1: []const std.json.Value,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky([]const u8, allocator, source, options)) |value| {
            return .{ .string = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky([]const std.json.Value, allocator, source, options)) |value| {
            return .{ .items_1 = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .string => |value| try jw.write(value),
            .items_1 => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const RequestToolResultBlock = struct {
    cache_control: ?std.json.Value = null,
    tool_use_id: []const u8,
    is_error: ?bool = null,
    type: []const u8,
    content: ?RequestToolResultBlockContent = null,
};

pub const ResponseToolSearchToolSearchResultBlock = struct {
    tool_references: []const ResponseToolReferenceBlock,
    type: []const u8,
};

pub const ResponseTextEditorCodeExecutionViewResultBlock = struct {
    total_lines: ?i64,
    file_type: []const u8,
    num_lines: ?i64,
    start_line: ?i64,
    type: []const u8,
    content: []const u8,
};

pub const URLImageSource = struct {
    url: []const u8,
    type: []const u8,
};

pub const UserLocation = struct {
    city: ?[]const u8 = null,
    country: ?[]const u8 = null,
    type: []const u8,
    region: ?[]const u8 = null,
    timezone: ?[]const u8 = null,
};

pub const ThinkingConfigParam = union(enum) {
    thinking_config_enabled: ThinkingConfigEnabled,
    thinking_config_disabled: ThinkingConfigDisabled,
    thinking_config_adaptive: ThinkingConfigAdaptive,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(ThinkingConfigEnabled, allocator, source, options)) |value| {
            return .{ .thinking_config_enabled = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ThinkingConfigDisabled, allocator, source, options)) |value| {
            return .{ .thinking_config_disabled = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(ThinkingConfigAdaptive, allocator, source, options)) |value| {
            return .{ .thinking_config_adaptive = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .thinking_config_enabled => |value| try jw.write(value),
            .thinking_config_disabled => |value| try jw.write(value),
            .thinking_config_adaptive => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const OutputTokensDetails = struct {
    thinking_tokens: i64,
};

pub const CodeExecutionTool_20250825 = struct {
    cache_control: ?std.json.Value = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    type: []const u8,
    allowed_callers: ?[]const AllowedCaller = null,
    name: []const u8,
};

pub const RequestContentBlockLocationCitation = struct {
    end_block_index: i64,
    start_block_index: i64,
    document_index: i64,
    cited_text: []const u8,
    type: []const u8,
    document_title: ?[]const u8,
};

pub const RequestWebSearchToolResultError = struct {
    error_code: []const u8,
    type: []const u8,
};

pub const RequestCodeExecutionToolResultBlockContent = union(enum) {
    request_code_execution_tool_result_error: RequestCodeExecutionToolResultError,
    request_code_execution_result_block: RequestCodeExecutionResultBlock,
    request_encrypted_code_execution_result_block: RequestEncryptedCodeExecutionResultBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(RequestCodeExecutionToolResultError, allocator, source, options)) |value| {
            return .{ .request_code_execution_tool_result_error = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestCodeExecutionResultBlock, allocator, source, options)) |value| {
            return .{ .request_code_execution_result_block = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky(RequestEncryptedCodeExecutionResultBlock, allocator, source, options)) |value| {
            return .{ .request_encrypted_code_execution_result_block = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .request_code_execution_tool_result_error => |value| try jw.write(value),
            .request_code_execution_result_block => |value| try jw.write(value),
            .request_encrypted_code_execution_result_block => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const RequestCodeExecutionToolResultBlock = struct {
    cache_control: ?std.json.Value = null,
    tool_use_id: []const u8,
    type: []const u8,
    content: RequestCodeExecutionToolResultBlockContent,
};

pub const CodeExecutionTool_20260120 = struct {
    cache_control: ?std.json.Value = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    type: []const u8,
    allowed_callers: ?[]const AllowedCaller = null,
    name: []const u8,
};

pub const ResponseWebSearchResultLocationCitation = struct {
    url: []const u8,
    encrypted_index: []const u8,
    cited_text: []const u8,
    title: ?[]const u8,
    type: []const u8,
};

pub const CodeExecutionTool_20260521 = struct {
    cache_control: ?std.json.Value = null,
    strict: ?bool = null,
    defer_loading: ?bool = null,
    type: []const u8,
    allowed_callers: ?[]const AllowedCaller = null,
    name: []const u8,
};

pub const Message = struct {
    container: ?Container,
    stop_details: ?RefusalStopDetails,
    stop_reason: ?[]const u8,
    role: []const u8,
    usage: Usage,
    model: []const u8,
    id: []const u8,
    type: []const u8,
    stop_sequence: ?[]const u8,
    content: []const ContentBlock,
};

pub const RefusalCategory = []const u8;

pub const RequestCodeExecutionToolResultError = struct {
    error_code: []const u8,
    type: []const u8,
};

pub const ResponseWebSearchToolResultBlockContentVariant1 = []const ResponseWebSearchResultBlock;

pub const ResponseWebSearchToolResultBlockContent = union(enum) {
    response_web_search_tool_result_error: ResponseWebSearchToolResultError,
    response_web_search_result_block_items: []const ResponseWebSearchResultBlock,
    raw: std.json.Value,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(allocator: std.mem.Allocator, source: std.json.Value, options: std.json.ParseOptions) !@This() {
        if (std.json.parseFromValueLeaky(ResponseWebSearchToolResultError, allocator, source, options)) |value| {
            return .{ .response_web_search_tool_result_error = value };
        } else |_| {}
        if (std.json.parseFromValueLeaky([]const ResponseWebSearchResultBlock, allocator, source, options)) |value| {
            return .{ .response_web_search_result_block_items = value };
        } else |_| {}
        return .{ .raw = source };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .response_web_search_tool_result_error => |value| try jw.write(value),
            .response_web_search_result_block_items => |value| try jw.write(value),
            .raw => |value| try jw.write(value),
        }
    }
};

pub const ResponseWebSearchToolResultBlock = struct {
    tool_use_id: []const u8,
    caller: std.json.Value,
    type: []const u8,
    content: ResponseWebSearchToolResultBlockContent,
};

pub const GatewayTimeoutError = struct {
    message: []const u8,
    type: []const u8,
};

pub const ResponseCodeExecutionOutputBlock = struct {
    file_id: []const u8,
    type: []const u8,
};

pub const RequestTextEditorCodeExecutionStrReplaceResultBlock = struct {
    old_lines: ?i64 = null,
    new_lines: ?i64 = null,
    old_start: ?i64 = null,
    type: []const u8,
    lines: ?[]const []const u8 = null,
    new_start: ?i64 = null,
};

pub const ResponseDocumentBlock = struct {
    source: std.json.Value,
    citations: ?ResponseCitationsConfig,
    type: []const u8,
    title: ?[]const u8,
};
