//! Crash report capture and submission.
//!
//! A run that fails writes a markdown report into the puny config directory.
//! The next interactive startup finds it and offers to file it as a GitHub
//! issue.

const std = @import("std");
const builtin = @import("builtin");
const core_session = @import("session.zig");
const version = @import("../version.zig");

/// Directory holding pending crash reports, inside the puny config directory.
/// The returned slice is owned by `allocator`.
pub fn crashDir(allocator: std.mem.Allocator, environ_map: *const std.process.Environ.Map) ![]const u8 {
    const dir = try core_session.configPunyDir(allocator, environ_map);
    defer allocator.free(dir);
    return std.fs.path.join(allocator, &.{ dir, "crashes" });
}

test "crashDir places reports under the puny config dir" {
    const allocator = std.testing.allocator;
    var env = std.process.Environ.Map.init(allocator);
    defer env.deinit();

    if (comptime builtin.os.tag == .windows) {
        try env.put("APPDATA", "C:\\Users\\test\\AppData\\Roaming");
        const dir = try crashDir(allocator, &env);
        defer allocator.free(dir);
        try std.testing.expectEqualStrings("C:\\Users\\test\\AppData\\Roaming\\puny\\crashes", dir);
    } else {
        try env.put("XDG_CONFIG_HOME", "/tmp/test-xdg");
        const dir = try crashDir(allocator, &env);
        defer allocator.free(dir);
        try std.testing.expectEqualStrings("/tmp/test-xdg/puny/crashes", dir);
    }
}

/// File name prefix shared by every crash report.
pub const file_prefix = "puny_crash_";

/// Absolute path of the crash report for `session_id`. The returned slice is
/// owned by `allocator`.
pub fn reportPath(
    allocator: std.mem.Allocator,
    environ_map: *const std.process.Environ.Map,
    session_id: []const u8,
) ![]const u8 {
    const dir = try crashDir(allocator, environ_map);
    defer allocator.free(dir);
    const name = try std.fmt.allocPrint(allocator, file_prefix ++ "{s}.md", .{session_id});
    defer allocator.free(name);
    return std.fs.path.join(allocator, &.{ dir, name });
}

test "reportPath names the file after the session id inside the crash dir" {
    const allocator = std.testing.allocator;
    var env = std.process.Environ.Map.init(allocator);
    defer env.deinit();
    if (comptime builtin.os.tag == .windows) {
        try env.put("APPDATA", "C:/Users/test");
    } else {
        try env.put("XDG_CONFIG_HOME", "/tmp/test-xdg");
    }

    const dir = try crashDir(allocator, &env);
    defer allocator.free(dir);

    const path = try reportPath(allocator, &env, "8f14e45f-ceea-467a-9dc3-0f0e0b1e1e1e");
    defer allocator.free(path);

    try std.testing.expectEqualStrings(dir, std.fs.path.dirname(path).?);
    try std.testing.expectEqualStrings(
        "puny_crash_8f14e45f-ceea-467a-9dc3-0f0e0b1e1e1e.md",
        std.fs.path.basename(path),
    );
}

/// What a crash report says about the failed run. Deliberately narrow: no
/// prompts, conversation content, file paths, argv values or credentials, so a
/// report can be pasted into a public issue as-is.
pub const Details = struct {
    session_id: []const u8,
    /// Error name without the `error.` prefix, as `@errorName` returns it.
    error_name: []const u8,
    /// What puny was doing when it failed, e.g. "startup" or "chat turn".
    phase: []const u8,
    provider: ?[]const u8 = null,
    model: ?[]const u8 = null,
};

/// Renders `details` as the markdown body of a crash report. The returned
/// slice is owned by `allocator`.
pub fn formatReport(allocator: std.mem.Allocator, details: Details) ![]const u8 {
    var body = std.Io.Writer.Allocating.init(allocator);
    errdefer body.deinit();
    const w = &body.writer;

    try w.print("# puny crash report\n\n", .{});
    try w.print("- **Error**: error.{s}\n", .{details.error_name});
    try w.print("- **Phase**: {s}\n", .{details.phase});
    try w.print("- **Version**: {s}\n", .{version.version});
    try w.print("- **Commit**: {s}\n", .{version.git_commit});
    try w.print("- **Platform**: {s}-{s}\n", .{
        @tagName(builtin.target.cpu.arch),
        @tagName(builtin.target.os.tag),
    });
    try w.print("- **Build**: {s}\n", .{@tagName(builtin.mode)});
    try w.print("- **Session**: {s}\n", .{details.session_id});
    if (details.provider) |p| try w.print("- **Provider**: {s}\n", .{p});
    if (details.model) |m| try w.print("- **Model**: {s}\n", .{m});
    try w.print(
        "\nThis report was generated by puny. It contains no prompts, conversation\n" ++
            "content, file paths or credentials.\n",
        .{},
    );

    return body.toOwnedSlice();
}

test "formatReport records the failure and the session it came from" {
    const allocator = std.testing.allocator;
    const report = try formatReport(allocator, .{
        .session_id = "abc-123",
        .error_name = "OutOfMemory",
        .phase = "chat turn",
        .provider = "GitHub Copilot",
        .model = "gpt-5",
    });
    defer allocator.free(report);

    try std.testing.expect(std.mem.indexOf(u8, report, "error.OutOfMemory") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, "abc-123") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, "chat turn") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, "GitHub Copilot") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, "gpt-5") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, version.version) != null);
}

test "formatReport omits provider and model when they are unknown" {
    const allocator = std.testing.allocator;
    const report = try formatReport(allocator, .{
        .session_id = "abc-123",
        .error_name = "AccessDenied",
        .phase = "startup",
    });
    defer allocator.free(report);

    try std.testing.expect(std.mem.indexOf(u8, report, "Provider") == null);
    try std.testing.expect(std.mem.indexOf(u8, report, "Model") == null);
    try std.testing.expect(std.mem.indexOf(u8, report, "error.AccessDenied") != null);
}
