//! Crash report capture and submission.
//!
//! A run that fails writes a markdown report into the puny config directory.
//! The next interactive startup finds it and offers to file it as a GitHub
//! issue.

const std = @import("std");
const builtin = @import("builtin");
const core_session = @import("session.zig");
const version = @import("../version.zig");

/// Directory holding pending crash reports, inside the puny config directory.
/// The returned slice is owned by `allocator`.
pub fn crashDir(allocator: std.mem.Allocator, environ_map: *const std.process.Environ.Map) ![]const u8 {
    const dir = try core_session.configPunyDir(allocator, environ_map);
    defer allocator.free(dir);
    return std.fs.path.join(allocator, &.{ dir, "crashes" });
}

test "crashDir places reports under the puny config dir" {
    const allocator = std.testing.allocator;
    var env = std.process.Environ.Map.init(allocator);
    defer env.deinit();

    if (comptime builtin.os.tag == .windows) {
        try env.put("APPDATA", "C:\\Users\\test\\AppData\\Roaming");
        const dir = try crashDir(allocator, &env);
        defer allocator.free(dir);
        try std.testing.expectEqualStrings("C:\\Users\\test\\AppData\\Roaming\\puny\\crashes", dir);
    } else {
        try env.put("XDG_CONFIG_HOME", "/tmp/test-xdg");
        const dir = try crashDir(allocator, &env);
        defer allocator.free(dir);
        try std.testing.expectEqualStrings("/tmp/test-xdg/puny/crashes", dir);
    }
}

/// File name prefix shared by every crash report.
pub const file_prefix = "puny_crash_";

/// Absolute path of the crash report for `session_id`. The returned slice is
/// owned by `allocator`.
pub fn reportPath(
    allocator: std.mem.Allocator,
    environ_map: *const std.process.Environ.Map,
    session_id: []const u8,
) ![]const u8 {
    const dir = try crashDir(allocator, environ_map);
    defer allocator.free(dir);
    const name = try std.fmt.allocPrint(allocator, file_prefix ++ "{s}.md", .{session_id});
    defer allocator.free(name);
    return std.fs.path.join(allocator, &.{ dir, name });
}

test "reportPath names the file after the session id inside the crash dir" {
    const allocator = std.testing.allocator;
    var env = std.process.Environ.Map.init(allocator);
    defer env.deinit();
    if (comptime builtin.os.tag == .windows) {
        try env.put("APPDATA", "C:/Users/test");
    } else {
        try env.put("XDG_CONFIG_HOME", "/tmp/test-xdg");
    }

    const dir = try crashDir(allocator, &env);
    defer allocator.free(dir);

    const path = try reportPath(allocator, &env, "8f14e45f-ceea-467a-9dc3-0f0e0b1e1e1e");
    defer allocator.free(path);

    try std.testing.expectEqualStrings(dir, std.fs.path.dirname(path).?);
    try std.testing.expectEqualStrings(
        "puny_crash_8f14e45f-ceea-467a-9dc3-0f0e0b1e1e1e.md",
        std.fs.path.basename(path),
    );
}

/// What a crash report says about the failed run. Deliberately narrow: no
/// prompts, conversation content, file paths, argv values or credentials, so a
/// report can be pasted into a public issue as-is.
pub const Details = struct {
    session_id: []const u8,
    /// Error name without the `error.` prefix, as `@errorName` returns it.
    error_name: []const u8,
    /// What puny was doing when it failed, e.g. "startup" or "chat turn".
    phase: []const u8,
    provider: ?[]const u8 = null,
    model: ?[]const u8 = null,
};

/// Renders `details` as the markdown body of a crash report. The returned
/// slice is owned by `allocator`.
pub fn formatReport(allocator: std.mem.Allocator, details: Details) ![]const u8 {
    var body = std.Io.Writer.Allocating.init(allocator);
    errdefer body.deinit();
    const w = &body.writer;

    try w.print("# puny crash report\n\n", .{});
    try w.print("- **Error**: error.{s}\n", .{details.error_name});
    try w.print("- **Phase**: {s}\n", .{details.phase});
    try w.print("- **Version**: {s}\n", .{version.version});
    try w.print("- **Commit**: {s}\n", .{version.git_commit});
    try w.print("- **Platform**: {s}-{s}\n", .{
        @tagName(builtin.target.cpu.arch),
        @tagName(builtin.target.os.tag),
    });
    try w.print("- **Build**: {s}\n", .{@tagName(builtin.mode)});
    try w.print("- **Session**: {s}\n", .{details.session_id});
    if (details.provider) |p| try w.print("- **Provider**: {s}\n", .{p});
    if (details.model) |m| try w.print("- **Model**: {s}\n", .{m});
    try w.print(
        "\nThis report was generated by puny. It contains no prompts, conversation\n" ++
            "content, file paths or credentials.\n",
        .{},
    );

    return body.toOwnedSlice();
}

test "formatReport records the failure and the session it came from" {
    const allocator = std.testing.allocator;
    const report = try formatReport(allocator, .{
        .session_id = "abc-123",
        .error_name = "OutOfMemory",
        .phase = "chat turn",
        .provider = "GitHub Copilot",
        .model = "gpt-5",
    });
    defer allocator.free(report);

    try std.testing.expect(std.mem.indexOf(u8, report, "error.OutOfMemory") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, "abc-123") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, "chat turn") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, "GitHub Copilot") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, "gpt-5") != null);
    try std.testing.expect(std.mem.indexOf(u8, report, version.version) != null);
}

test "formatReport omits provider and model when they are unknown" {
    const allocator = std.testing.allocator;
    const report = try formatReport(allocator, .{
        .session_id = "abc-123",
        .error_name = "AccessDenied",
        .phase = "startup",
    });
    defer allocator.free(report);

    try std.testing.expect(std.mem.indexOf(u8, report, "Provider") == null);
    try std.testing.expect(std.mem.indexOf(u8, report, "Model") == null);
    try std.testing.expect(std.mem.indexOf(u8, report, "error.AccessDenied") != null);
}

/// Writes a crash report for `details` into the crash directory, creating it
/// when missing. Callers on the failure path should ignore errors: a crash
/// report that cannot be written must not replace the original failure.
pub fn write(
    io: std.Io,
    allocator: std.mem.Allocator,
    environ_map: *const std.process.Environ.Map,
    details: Details,
) !void {
    const path = try reportPath(allocator, environ_map, details.session_id);
    defer allocator.free(path);
    const body = try formatReport(allocator, details);
    defer allocator.free(body);

    const cwd = std.Io.Dir.cwd();
    try cwd.createDirPath(io, std.fs.path.dirname(path).?);
    var file = try cwd.createFile(io, path, .{});
    defer file.close(io);
    try file.writeStreamingAll(io, body);
}

/// A crash report waiting to be submitted or discarded.
pub const Report = struct {
    /// Absolute path of the report file.
    path: []const u8,
    /// Session the crashed run belonged to, taken from the file name.
    session_id: []const u8,
    modified_ns: i96,
};

/// Frees a slice returned by `list`.
pub fn freeReports(allocator: std.mem.Allocator, reports: []const Report) void {
    for (reports) |r| {
        allocator.free(r.path);
        allocator.free(r.session_id);
    }
    allocator.free(reports);
}

fn newerFirst(_: void, a: Report, b: Report) bool {
    return a.modified_ns > b.modified_ns;
}

/// Lists the pending crash reports, most recent first. A missing crash
/// directory yields an empty slice. The result is owned by `allocator`; free it
/// with `freeReports`.
pub fn list(
    io: std.Io,
    allocator: std.mem.Allocator,
    environ_map: *const std.process.Environ.Map,
) ![]const Report {
    const dir_path = try crashDir(allocator, environ_map);
    defer allocator.free(dir_path);

    var dir = std.Io.Dir.cwd().openDir(io, dir_path, .{ .iterate = true }) catch |err| switch (err) {
        error.FileNotFound => return &[_]Report{},
        else => |e| return e,
    };
    defer dir.close(io);

    var reports: std.ArrayList(Report) = .empty;
    errdefer {
        for (reports.items) |r| {
            allocator.free(r.path);
            allocator.free(r.session_id);
        }
        reports.deinit(allocator);
    }

    var it = dir.iterate();
    while (try it.next(io)) |entry| {
        if (entry.kind != .file) continue;
        const id = sessionIdFromFileName(entry.name) orelse continue;

        const path = try std.fs.path.join(allocator, &.{ dir_path, entry.name });
        errdefer allocator.free(path);
        const stat = std.Io.Dir.cwd().statFile(io, path, .{}) catch {
            allocator.free(path);
            continue;
        };
        const session_id = try allocator.dupe(u8, id);
        errdefer allocator.free(session_id);

        try reports.append(allocator, .{
            .path = path,
            .session_id = session_id,
            .modified_ns = stat.mtime.nanoseconds,
        });
    }

    const owned = try reports.toOwnedSlice(allocator);
    std.mem.sort(Report, owned, {}, newerFirst);
    return owned;
}

/// Deletes a crash report. A file that is already gone is not an error.
pub fn discard(io: std.Io, path: []const u8) !void {
    std.Io.Dir.cwd().deleteFile(io, path) catch |err| switch (err) {
        error.FileNotFound => {},
        else => |e| return e,
    };
}

/// Extracts the session id from a crash report file name, or null when the
/// name does not belong to puny.
fn sessionIdFromFileName(name: []const u8) ?[]const u8 {
    if (!std.mem.startsWith(u8, name, file_prefix)) return null;
    if (!std.mem.endsWith(u8, name, ".md")) return null;
    const id = name[file_prefix.len .. name.len - ".md".len];
    return if (id.len == 0) null else id;
}

/// Environment map pointing the config dir at a scratch directory, wiped so a
/// crashed run's leftovers cannot leak into the next test run.
fn testEnv(allocator: std.mem.Allocator, io: std.Io, base: []const u8) !std.process.Environ.Map {
    var env = std.process.Environ.Map.init(allocator);
    errdefer env.deinit();
    const cwd = try std.process.currentPathAlloc(io, allocator);
    defer allocator.free(cwd);
    const dir = try std.fs.path.join(allocator, &.{ cwd, "zig-out", base });
    defer allocator.free(dir);
    std.Io.Dir.cwd().deleteTree(io, dir) catch {};
    if (comptime builtin.os.tag == .windows) {
        try env.put("APPDATA", dir);
    } else {
        try env.put("XDG_CONFIG_HOME", dir);
    }
    return env;
}

fn testEnvCleanup(allocator: std.mem.Allocator, io: std.Io, env: *std.process.Environ.Map) void {
    if (crashDir(allocator, env)) |dir| {
        defer allocator.free(dir);
        std.Io.Dir.cwd().deleteTree(io, dir) catch {};
    } else |_| {}
    env.deinit();
}

test "write stores the report at the path reportPath resolves" {
    const allocator = std.testing.allocator;
    const io = std.testing.io;
    var env = try testEnv(allocator, io, "test-crash-write");
    defer testEnvCleanup(allocator, io, &env);

    try write(io, allocator, &env, .{
        .session_id = "write-1",
        .error_name = "OutOfMemory",
        .phase = "chat turn",
    });

    const path = try reportPath(allocator, &env, "write-1");
    defer allocator.free(path);
    const content = try std.Io.Dir.cwd().readFileAlloc(io, path, allocator, std.Io.Limit.limited(64 * 1024));
    defer allocator.free(content);

    try std.testing.expect(std.mem.indexOf(u8, content, "error.OutOfMemory") != null);
    try std.testing.expect(std.mem.indexOf(u8, content, "write-1") != null);
}

fn writeTestReport(
    allocator: std.mem.Allocator,
    io: std.Io,
    env: *const std.process.Environ.Map,
    session_id: []const u8,
    modified_ns: i96,
) !void {
    try write(io, allocator, env, .{
        .session_id = session_id,
        .error_name = "OutOfMemory",
        .phase = "chat turn",
    });
    const path = try reportPath(allocator, env, session_id);
    defer allocator.free(path);
    var file = try std.Io.Dir.cwd().openFile(io, path, .{ .mode = .read_write });
    defer file.close(io);
    try file.setTimestamps(io, .{ .modify_timestamp = .{ .new = std.Io.Timestamp.fromNanoseconds(modified_ns) } });
}

test "list returns pending reports newest first and ignores other files" {
    const allocator = std.testing.allocator;
    const io = std.testing.io;
    var env = try testEnv(allocator, io, "test-crash-list");
    defer testEnvCleanup(allocator, io, &env);

    try writeTestReport(allocator, io, &env, "older", 1_000_000_000_000);
    try writeTestReport(allocator, io, &env, "newer", 2_000_000_000_000);

    const dir = try crashDir(allocator, &env);
    defer allocator.free(dir);
    const stray = try std.fs.path.join(allocator, &.{ dir, "notes.txt" });
    defer allocator.free(stray);
    var stray_file = try std.Io.Dir.cwd().createFile(io, stray, .{});
    stray_file.close(io);

    const reports = try list(io, allocator, &env);
    defer freeReports(allocator, reports);

    try std.testing.expectEqual(@as(usize, 2), reports.len);
    try std.testing.expectEqualStrings("newer", reports[0].session_id);
    try std.testing.expectEqualStrings("older", reports[1].session_id);
}

test "list is empty when no crash directory exists" {
    const allocator = std.testing.allocator;
    const io = std.testing.io;
    var env = try testEnv(allocator, io, "test-crash-empty");
    defer testEnvCleanup(allocator, io, &env);

    const reports = try list(io, allocator, &env);
    defer freeReports(allocator, reports);
    try std.testing.expectEqual(@as(usize, 0), reports.len);
}

test "discard removes a report and tolerates a missing file" {
    const allocator = std.testing.allocator;
    const io = std.testing.io;
    var env = try testEnv(allocator, io, "test-crash-discard");
    defer testEnvCleanup(allocator, io, &env);

    try writeTestReport(allocator, io, &env, "gone", 1_000_000_000_000);
    const path = try reportPath(allocator, &env, "gone");
    defer allocator.free(path);

    try discard(io, path);
    try std.testing.expectError(error.FileNotFound, std.Io.Dir.cwd().statFile(io, path, .{}));
    try discard(io, path);
}
